{
  "hash": "085fdee4e99c56a6b2d6ff005fad87c2",
  "result": {
    "engine": "knitr",
    "markdown": "---\nnumber-offset: 15\n---\n\n# Time Series Forecasting {#sec-ch16}\n\n\n\nMuch of the data that organisations keep is recorded over time: patients admitted each day, products sold each month, rainfall each week. Such a sequence of measurements taken at regular intervals is a **time series**, and it calls for a different way of thinking from the surveys of the previous chapters. The observations are not independent: this week's value is related to last week's, and the order of the observations carries information. The patterns are also of a particular kind. A series usually combines a slow **trend**, a **seasonal** pattern that repeats over a fixed period, and irregular **noise**, and understanding a series largely means separating these parts. Finally, the future of a series can never be known exactly, so a forecast is honestly a range of plausible values, not a single number.\n\nThis chapter develops these ideas and the methods built on them, using the **fable** family of packages. The example comes from outside the thesis. The doctors at the university counselling service have heard about Elaf's wellbeing study and ask her to analyse their records: five years of weekly visit counts, with the service overwhelmed before exams and quiet in the summer, and staffing planned by guesswork. They want to know how many visits to expect next year, week by week. This is an **internal analysis**, done for the service rather than for publication, and a common situation for anyone who knows some data analysis: being asked to analyse someone else's data.\n\n::: {.callout-tip appearance=\"simple\"}\n## By the end of this chapter you will be able to\n\n- Explain dependence over time, the parts of a time series (trend, seasonality, and noise), and why forecasts are ranges.\n- Store a time series as a tsibble, and plot it.\n- Recognise trend, seasonality, and unusual observations, using time plots, seasonal plots, and autocorrelation.\n- Decompose a series into trend, seasonal, and remainder components with STL.\n- Produce benchmark forecasts, and forecasts from exponential smoothing (ETS) and ARIMA models, with fable.\n- Evaluate forecasts on a test period, and report forecasts with prediction intervals.\n:::\n::: {.callout-note appearance=\"simple\" icon=\"false\"}\n**Teaching & Practice:** [Interactive Lecture Slides](../slides/16-time-series.html) · [Browser Playground Exercises](../playground/chapter16.html)\n:::\n\n\n## Time series data\n\nMost of this book's methods assume that observations are independent: one student's answers tell you nothing about another's. In a time series the opposite is true. The number of visits this week is closely related to the number last week, and the order of the observations is essential. The methods of this chapter are built around that dependence.\n\n### A small example\n\nTwo weeks of daily visits to a small clinic, starting on a Monday, show how a time series is stored:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(tsibble)\nlibrary(fable)\nlibrary(feasts)\n\nclinic <- tsibble(\n  day    = 1:14,\n  visits = c(12, 10, 9, 11, 7, 3, 2,   14, 11, 10, 12, 8, 4, 2),\n  index  = day\n)\nclinic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tsibble: 14 x 2 [1]\n     day visits\n   <int>  <dbl>\n 1     1     12\n 2     2     10\n 3     3      9\n 4     4     11\n 5     5      7\n 6     6      3\n 7     7      2\n 8     8     14\n 9     9     11\n10    10     10\n11    11     12\n12    12      8\n13    13      4\n14    14      2\n```\n\n\n:::\n:::\n\n\nA **tsibble** (time series tibble) is a data frame that knows which column is time, its **index**. Here the index is the day number; the output header shows that the observations are one unit apart (`[1]`). tsibbles check that each time appears only once, and fable's functions use the index to keep everything in order. There is a clear weekly pattern: busy at the start of the week, quiet at the weekend.\n\n### The parts of a pattern\n\nA time series is easiest to understand as a sum of parts. The code below builds an artificial weekly series for three years from three ingredients: a trend that rises slowly, a seasonal pattern that repeats every 52 weeks, and random noise. @fig-parts shows each part and their sum.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(4)\nweek <- 1:156\nparts <- tibble(\n  week     = week,\n  trend    = 30 + 0.05 * week,\n  seasonal = 12 * sin(2 * pi * week / 52),\n  noise    = rnorm(156, sd = 3)\n) |>\n  mutate(series = trend + seasonal + noise)\n\nparts |>\n  tidyr::pivot_longer(-week, names_to = \"part\", values_to = \"value\") |>\n  mutate(part = factor(part, levels = c(\"trend\", \"seasonal\", \"noise\", \"series\"))) |>\n  ggplot(aes(x = week, y = value)) +\n  geom_line(colour = \"#2f6793\") +\n  facet_wrap(~ part, ncol = 1, scales = \"free_y\") +\n  labs(x = \"Week\", y = NULL) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![An artificial weekly series built from three parts: a rising trend, a seasonal pattern that repeats every 52 weeks, and random noise. The bottom panel is their sum.](16-time-series_files/figure-html/fig-parts-1.png){#fig-parts fig-alt='Four stacked panels over three years. The trend is a straight line rising slowly. The seasonal part is a wave repeating every year. The noise is irregular small ups and downs. The sum is a wavy series that rises gently and has a jagged look.' width=720}\n:::\n:::\n\n\nIn a real series, only the bottom panel is observed; the parts must be recovered from it. The trend says where the series is heading, the seasonal pattern says what happens at each point in the year, and the noise is what no pattern explains. Forecasting extends the trend and the seasonal pattern into the future. The noise cannot be forecast, and it is the main reason every forecast comes with a range. The decomposition later in this chapter recovers these parts from the counselling data.\n\n## The counselling service data\n\nThe counselling records are in `counselling_visits`: the date of the Monday of each week, and the number of visits that week.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounselling_visits |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  week_start visits\n1 2020-09-07     32\n2 2020-09-14     28\n3 2020-09-21     24\n4 2020-09-28     37\n5 2020-10-05     32\n6 2020-10-12     39\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(counselling_visits$week_start)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-09-07\" \"2025-08-25\"\n```\n\n\n:::\n:::\n\n\nThe data covers five academic years, from September 2020 to August 2025, 260 weeks in all. The function `yearweek()` turns each date into a week, which becomes the index:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits <- counselling_visits |>\n  mutate(week = yearweek(week_start)) |>\n  as_tsibble(index = week)\nvisits\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tsibble: 260 x 3 [1W]\n   week_start visits     week\n   <date>      <int>   <week>\n 1 2020-09-07     32 2020 W37\n 2 2020-09-14     28 2020 W38\n 3 2020-09-21     24 2020 W39\n 4 2020-09-28     37 2020 W40\n 5 2020-10-05     32 2020 W41\n 6 2020-10-12     39 2020 W42\n 7 2020-10-19     31 2020 W43\n 8 2020-10-26     36 2020 W44\n 9 2020-11-02     37 2020 W45\n10 2020-11-09     34 2020 W46\n# ℹ 250 more rows\n```\n\n\n:::\n:::\n\n\nThe header now reads `[1W]`: one week between observations. The first step with any time series is to plot it, and `autoplot()` from the fable family draws a **time plot**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(visits, visits) +\n  labs(x = NULL, y = \"Visits per week\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Weekly visits to the university counselling service, September 2020 to August 2025.](16-time-series_files/figure-html/fig-timeplot-1.png){#fig-timeplot fig-alt='Line chart of weekly visits over five years. Every year shows the same pattern: moderate visits in autumn, two sharp peaks before the exam periods, short dips at the mid-year and spring breaks, and a long low period each summer. The peaks get slightly higher each year. One week in autumn 2023 stands out, far above the weeks around it.' width=768}\n:::\n:::\n\n\n@fig-timeplot shows the parts of a pattern described above, and one feature the doctors did not mention. There is a **seasonal pattern** that repeats every academic year: peaks before and during the two exam periods, dips during the breaks, and very few visits in the summer, when the service is reduced. There is a gentle upward **trend**, each year a little busier than the last, and there is **noise**, week-to-week variation that follows no pattern. Finally, there is one **unusual week**, in the autumn of 2023, far busier than the weeks around it.\n\n### Seasonal patterns\n\nA **seasonal plot** puts the years on top of each other, so the seasonal pattern and the differences between years are easier to see. The academic year starts in September, so the weeks are numbered from the start of each academic year:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits |>\n  mutate(academic_year = paste0(20 + (row_number() - 1) %/% 52, \"/\", 21 + (row_number() - 1) %/% 52),\n         week_of_year  = (row_number() - 1) %% 52 + 1) |>\n  ggplot(aes(x = week_of_year, y = visits, colour = academic_year)) +\n  geom_line() +\n  scale_colour_viridis_d(end = 0.9) +\n  labs(x = \"Week of the academic year\", y = \"Visits per week\", colour = \"Academic year\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Seasonal plot: weekly visits by week of the academic year, one line per year.](16-time-series_files/figure-html/fig-seasonal-1.png){#fig-seasonal fig-alt='Five overlapping lines, one per academic year, of visits against week of the academic year from 1 to 52. All five follow the same shape, with two peaks, short dips, and a long summer low. Later years lie slightly above earlier ones.' width=720}\n:::\n:::\n\n\nEvery year has the same shape, and later years lie slightly above earlier ones. The period of the seasonal pattern is 52 weeks.\n\n### Autocorrelation\n\nDependence over time can be seen directly by plotting each week's visits against the visits one week earlier, as in @fig-lag1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits |>\n  mutate(last_week = lag(visits)) |>\n  ggplot(aes(x = last_week, y = visits)) +\n  geom_point(alpha = 0.6, colour = \"#2f6793\") +\n  labs(x = \"Visits in the previous week\", y = \"Visits this week\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Weekly visits against the visits of the previous week. Busy weeks tend to follow busy weeks, and quiet weeks quiet weeks.](16-time-series_files/figure-html/fig-lag1-1.png){#fig-lag1 fig-alt='Scatter plot of this week\\'s visits against last week\\'s visits. The points form a clear rising band from bottom left to top right.' width=480}\n:::\n:::\n\n\nThe points rise from left to right: knowing last week's visits says a good deal about this week's. The **autocorrelation** at lag $k$ puts a number on this relationship: it is the correlation between the series and itself $k$ steps earlier, between each week and the week before (lag 1), two weeks before (lag 2), and so on. The function `ACF()` calculates it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits_acf <- visits |> ACF(visits, lag_max = 60)\nvisits_acf |> slice(c(1, 2, 26, 52))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tsibble: 4 x 2 [1W]\n       lag    acf\n  <cf_lag>  <dbl>\n1       1W  0.690\n2       2W  0.572\n3      26W -0.244\n4      52W  0.684\n```\n\n\n:::\n:::\n\n\nThe autocorrelation is 0.69 at lag 1, as the scatter plot suggested, and 0.68 at lag 52: a week tends to be like the same week a year earlier. At lag 26 it is negative: half a year apart, a busy term week is often matched with a quiet summer week. @fig-acf shows all the lags. Strong autocorrelation at the seasonal lag is the signature of seasonality; if a series had no autocorrelation at all, there would be nothing to forecast beyond its average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(visits_acf) + theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Autocorrelation of weekly visits for lags of 1 to 60 weeks. The dashed lines mark the range expected for a series with no autocorrelation.](16-time-series_files/figure-html/fig-acf-1.png){#fig-acf fig-alt='Bar chart of autocorrelations for lags 1 to 60. The bars are high for the first few lags, fall and turn negative around lag 20 to 30, and rise again to a peak at lag 52, well outside the dashed lines.' width=672}\n:::\n:::\n\n\n## Decomposition\n\n**Decomposition** recovers the parts of a pattern from an observed series: a smooth **trend**, a repeating **seasonal** component, and the **remainder**, what is left over, which corresponds to the noise of @fig-parts. **STL** (seasonal and trend decomposition using loess) is a flexible, widely used method. `season(period = 52)` tells it the length of the seasonal pattern, and `robust = TRUE` stops unusual weeks from distorting the trend and season:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits_stl <- visits |>\n  model(STL(visits ~ season(period = 52), robust = TRUE)) |>\n  components()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(visits_stl) + theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![STL decomposition of weekly visits into trend, seasonal pattern, and remainder.](16-time-series_files/figure-html/fig-stl-1.png){#fig-stl fig-alt='Four stacked panels sharing a time axis. Top: the original series. Second: the trend, rising slowly and levelling off in the last year. Third: the seasonal component, the same shape each year with exam peaks and summer lows. Bottom: the remainder, mostly small, with one large positive spike in autumn 2023.' width=768}\n:::\n:::\n\n\nIn @fig-stl the series is the sum of the three components below it, just as in the artificial example. The trend rises from about 28 to about 38 visits a week, levelling off in the last year; the seasonal component repeats the academic year; and the remainder is mostly small noise. The largest remainder is the unusual week:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits_stl |>\n  as_tibble() |>\n  slice_max(abs(remainder), n = 3) |>\n  select(week, visits, trend, season_52, remainder)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n      week visits trend season_52 remainder\n    <week>  <int> <dbl>     <dbl>     <dbl>\n1 2023 W43     71  35.2      8.08      27.7\n2 2024 W48     32  38.4     12.1      -18.5\n3 2024 W20     51  37.1     31.3      -17.5\n```\n\n\n:::\n:::\n\n\n\n\nIn the week of 23 October 2023, there were 71 visits, about 28 more than trend and season would predict. When asked, the doctors remember at once: it was the university's mental health awareness week, with posters everywhere encouraging students to seek help. The remainder is where such events show up. It is a real week, not an error, so it is kept, and the robust decomposition makes sure it does not distort the forecasts.\n\nNotice also that the seasonal swings grow slightly as the trend rises: the peaks get higher and the summer lows stay low. When the seasonal pattern grows in proportion to the level of the series, it is usual to model the **logarithm** of the series, on which the swings become constant. fable handles this automatically: write `log(visits)` in the model, and the forecasts are transformed back to visits.\n\n## Forecasting\n\n### Simple benchmarks\n\nEvery forecasting method should be compared with simple **benchmark** methods, just as every predictive model in Chapters 11 to 13 was compared with a baseline. The three most common are the **mean** method, which forecasts the average of all past observations; the **naive** method, which forecasts the last observed value; and the **seasonal naive** method, which forecasts the value from the same season in the last cycle (the same day last week, or the same week last year). For the clinic example, with its weekly cycle of 7 days, they give:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclinic_fc <- clinic |>\n  model(\n    mean   = MEAN(visits),\n    naive  = NAIVE(visits),\n    snaive = SNAIVE(visits ~ lag(7))\n  ) |>\n  forecast(h = 7)\n\nclinic_fc |>\n  as_tibble() |>\n  select(.model, day, .mean) |>\n  tidyr::pivot_wider(names_from = .model, values_from = .mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n    day  mean naive snaive\n  <dbl> <dbl> <dbl>  <dbl>\n1    15  8.21     2     14\n2    16  8.21     2     11\n3    17  8.21     2     10\n4    18  8.21     2     12\n5    19  8.21     2      8\n6    20  8.21     2      4\n7    21  8.21     2      2\n```\n\n\n:::\n:::\n\n\nThe function `model()` fits several models at once, each named; `forecast(h = 7)` forecasts 7 steps ahead; and `.mean` holds the point forecasts. The mean method forecasts 8.2 visits every day; the naive method repeats the last value, a quiet Sunday, for the whole week; and the seasonal naive method repeats last week's pattern, which for this series is clearly the most sensible.\n\n### Two families of models\n\nTwo families of models go beyond the benchmarks. **Exponential smoothing (ETS)** forecasts with weighted averages of past observations, with weights that decrease the further back the observations are, so that recent weeks count most. ETS models can track a changing level, a trend, and a seasonal pattern, each estimated from the data; the name stands for the three components it models, error, trend, and season. **ARIMA** models describe how each observation depends on earlier observations and on earlier random shocks, and use the autocorrelation of the series to forecast it.\n\nThe functions `ETS()` and `ARIMA()` in fable choose the details of each model automatically, by a criterion like the BIC of Chapter 14. Both work best with short seasonal periods, such as 4 quarters, 7 days, or 12 months. A 52-week season is long, so two strategies are common for weekly data. The first is to **decompose first**: remove the seasonal pattern with STL, forecast the **seasonally adjusted** series (trend and remainder) with ETS, and add the seasonal pattern back, all of which `decomposition_model()` does in one step. The second uses **Fourier terms**: the seasonal pattern is described with a few smooth waves (sines and cosines) of different lengths, used as predictors in an ARIMA model; `fourier(period = 52, K = 6)` uses six pairs of waves.\n\n### Training and test periods\n\nAs in machine learning, forecasts must be judged on data the model has not seen. For time series, the test data must come *after* the training data, because a forecast can only use the past. The models are trained on the first four academic years and tested on the fifth:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits_train <- visits |> filter(week_start < as.Date(\"2024-09-01\"))\nvisits_test  <- visits |> filter(week_start >= as.Date(\"2024-09-01\"))\n\nvisits_fit <- visits_train |>\n  model(\n    mean     = MEAN(visits),\n    naive    = NAIVE(visits),\n    snaive   = SNAIVE(visits ~ lag(52)),\n    stl_ets  = decomposition_model(\n                 STL(log(visits) ~ season(period = 52), robust = TRUE),\n                 ETS(season_adjust ~ season(\"N\"))\n               ),\n    fourier  = ARIMA(log(visits) ~ fourier(period = 52, K = 6) + PDQ(0, 0, 0))\n  )\n```\n:::\n\n\nIn the STL model, `ETS(season_adjust ~ season(\"N\"))` forecasts the seasonally adjusted series with no seasonal component of its own (\"N\" for none), because the seasonal pattern is added back from the decomposition. In the Fourier model, `PDQ(0, 0, 0)` tells ARIMA not to model the season itself, because the Fourier terms do that.\n\nEach model forecasts the 52 weeks of the test year, and `accuracy()` compares the forecasts with what actually happened, using the RMSE and MAE of Chapter 13:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits_fc <- visits_fit |> forecast(h = 52)\n\nvisits_fc |>\n  accuracy(visits) |>\n  select(.model, RMSE, MAE) |>\n  arrange(RMSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  .model   RMSE   MAE\n  <chr>   <dbl> <dbl>\n1 stl_ets  7.40  5.57\n2 snaive   9.16  6.96\n3 fourier 10.3   7.81\n4 mean    18.7  16.3 \n5 naive   27.5  23.5 \n```\n\n\n:::\n:::\n\n\n\n\nThe STL and ETS model is best: its forecasts are off by 5.6 visits a week on average (MAE), against 7.0 for the seasonal naive benchmark, which simply repeats the previous year. The mean and naive methods, which ignore the seasonal pattern, are far worse. The Fourier model does worse than the seasonal naive benchmark: the counselling service's pattern has sharp steps (the summer drop happens from one week to the next), and smooth waves struggle to follow them. @fig-test-forecasts compares the two best models with the actual visits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits_fc |>\n  filter(.model %in% c(\"stl_ets\", \"snaive\")) |>\n  autoplot(visits_test, level = NULL) +\n  labs(x = NULL, y = \"Visits per week\", colour = \"Model\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Forecasts for the test year (September 2024 to August 2025) from the STL and ETS model and the seasonal naive benchmark, with the actual visits in black.](16-time-series_files/figure-html/fig-test-forecasts-1.png){#fig-test-forecasts fig-alt='Line chart of weekly visits in the test year. The black line of actual visits shows the usual exam peaks and summer low. The STL and ETS forecast follows the actual line closely for most of the year. The seasonal naive forecast, a copy of the previous year, is more jagged, and in October 2024 it shows a spike that did not happen.' width=768}\n:::\n:::\n\n\nThe seasonal naive forecast copies last year's noise along with its pattern: it even repeats the awareness week of October 2023 as a spike in October 2024. The STL and ETS model smooths the noise away and adds the trend, so its forecasts are both smoother and closer.\n\n### Forecasting next year\n\nWith the model chosen, it is refitted on all five years, so the forecasts use the most recent information, and the next 52 weeks are forecast:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_fit <- visits |>\n  model(stl_ets = decomposition_model(\n    STL(log(visits) ~ season(period = 52), robust = TRUE),\n    ETS(season_adjust ~ season(\"N\"))\n  ))\n\nnext_year <- final_fit |> forecast(h = 52)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnext_year |>\n  autoplot(visits |> filter(week_start >= as.Date(\"2023-09-01\"))) +\n  labs(x = NULL, y = \"Visits per week\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Forecast of weekly visits for the academic year 2025/26, with 80% and 95% prediction intervals, after the last two years of data.](16-time-series_files/figure-html/fig-forecast-1.png){#fig-forecast fig-alt='Line chart of the last two years of weekly visits, followed by a forecast for the next 52 weeks. The forecast line repeats the seasonal pattern at a slightly higher level, with shaded bands around it: a darker 80% band and a wider, lighter 95% band. The bands are widest around the exam peaks.' width=768}\n:::\n:::\n\n\nA forecast is never a single number. The shaded bands in @fig-forecast are **prediction intervals**: the ranges within which the actual visits are expected to fall with 80% and 95% probability. The function `hilo()` shows them as numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnext_year |>\n  hilo(95) |>\n  select(week, .mean, `95%`) |>\n  head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tsibble: 4 x 3 [1W]\n      week .mean                  `95%`\n    <week> <dbl>                 <hilo>\n1 2025 W36  39.0 [23.60596, 60.76414]95\n2 2025 W37  35.2 [21.32399, 54.89014]95\n3 2025 W38  47.5 [28.74758, 73.99921]95\n4 2025 W39  48.8 [29.58119, 76.14503]95\n```\n\n\n:::\n:::\n\n\nIn the first week of the new year, about 39 visits are expected, but anything from about 24 to 61 would not be surprising. The doctors also asked for the year as a whole. Adding up the weekly forecasts gives the expected total, but not its uncertainty, because weeks do not vary independently. The function `generate()` solves this by **simulation**: it produces 1,000 possible futures from the model, and the totals of those futures show the range of likely totals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfutures <- final_fit |> generate(h = 52, times = 1000)\n\nyearly_totals <- futures |>\n  as_tibble() |>\n  summarise(total = sum(.sim), .by = .rep)\n\nquantile(yearly_totals$total, c(0.025, 0.5, 0.975)) |> round()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5%   50% 97.5% \n 1952  2111  2286 \n```\n\n\n:::\n:::\n\n\n\n\nThe report to the service therefore says: about 2,111 visits are expected in 2025/26 (95% interval 1,952 to 2,286), compared with 1,954 in 2024/25; the busiest weeks will again be just before and during the two exam periods, when they should plan the most staff; and an awareness campaign can raise demand sharply for a week, so extra capacity should be planned for any such event.\n\n::: {.callout-warning}\n## Forecasts assume the future resembles the past\n\nEvery forecast in this chapter assumes that the patterns of the last five years continue. A change the data cannot know about, such as a new online booking system, a change in the exam calendar, or a crisis like the COVID-19 pandemic, can make any forecast wrong. Report forecasts with their intervals, say what they assume, and update them as new data arrives. (You may also meet **Prophet**, a forecasting tool from Meta that was popular for business data; it is no longer actively developed, and fable's models are a well-supported alternative.)\n:::\n\n::: {.callout-note icon=\"false\"}\n## In your field: environmental science\n\nR's `co2` dataset records the monthly concentration of carbon dioxide in the atmosphere, measured at the Mauna Loa observatory in Hawaii from 1959 to 1997: a famous series with a strong upward trend and a yearly cycle, as plants absorb CO~2~ in the northern summer. With a 12-month season, ETS and ARIMA can model the seasonal pattern directly. Training on the years to 1990 and testing on 1991 to 1997:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nco2_ts <- as_tsibble(co2)\n\nco2_fit <- co2_ts |>\n  filter(index <= yearmonth(\"1990 Dec\")) |>\n  model(\n    snaive = SNAIVE(value),\n    ets    = ETS(value),\n    arima  = ARIMA(value)\n  )\n\nco2_accuracy <- co2_fit |>\n  forecast(h = \"7 years\") |>\n  accuracy(co2_ts) |>\n  select(.model, RMSE, MAE)\nco2_accuracy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .model  RMSE   MAE\n  <chr>  <dbl> <dbl>\n1 arima   1.34  1.24\n2 ets     1.16  1.03\n3 snaive  6.07  5.26\n```\n\n\n:::\n:::\n\n\nThe function `as_tsibble()` converts R's older time series objects, and `h = \"7 years\"` gives the forecast horizon in words. Both ETS and ARIMA forecast seven years ahead with an average error (MAE) of only 1.0 and 1.2 parts per million, while the seasonal naive method, which ignores the trend, falls further behind every year.\n:::\n\n## Common misconceptions\n\nTime series have their own traps, most of them versions of forgetting that time has an order.\n\n- **\"A forecast is a prediction of the exact value.\"** A forecast is a range; the point forecast is only its centre, and the noise in a series makes exact prediction impossible.\n- **\"More history always gives better forecasts.\"** Only if the old patterns still hold; a change in circumstances can make older data misleading.\n- **\"The test data can be any random subset.\"** In a time series, the test period must come after the training period, since a forecast can only use the past.\n- **\"An unusual week should be removed.\"** It is part of the record; robust methods keep it from distorting the forecast, and it may be exactly what the service needs to plan for.\n\n## Chapter review\n\n### Summary\n\n- A time series is a sequence of observations over time, in which order matters and neighbouring observations are related. It can be understood as a sum of parts: trend, seasonal pattern, and noise. A tsibble stores it with a time index.\n- Time plots, seasonal plots, and the autocorrelation function reveal trend, seasonality, and unusual observations.\n- STL decomposes a series into trend, seasonal, and remainder components; unusual events show up in the remainder. A logarithm makes growing seasonal swings constant.\n- Compare every forecasting method with benchmarks: mean, naive, and seasonal naive.\n- ETS forecasts with weighted averages that favour recent observations; ARIMA uses the autocorrelation of the series. For long seasons such as 52 weeks, decompose first or use Fourier terms.\n- Evaluate forecasts on a test period that comes after the training period, and report forecasts with prediction intervals. Simulating futures with `generate()` gives intervals for totals.\n- Forecasts assume that past patterns continue.\n\n### Key terms\n\nTime series, tsibble, index, time plot, trend, seasonality, seasonal period, seasonal plot, autocorrelation, lag, decomposition, STL, remainder, seasonally adjusted series, benchmark forecast, mean method, naive method, seasonal naive method, exponential smoothing (ETS), ARIMA, Fourier terms, forecast horizon, prediction interval, simulation.\n\n## Exercises\n\nThe [playground](../playground/chapter16.html) has these and more, with hints and solutions.\n\n1. Predict which of the three benchmarks would be best for a series with a trend but no seasonality, then test your prediction on `clinic` after adding a steady increase of one visit a day.\n2. Plot the seasonally adjusted series (`season_adjust` in `visits_stl`), and describe what it shows that the original series hides.\n3. Refit the Fourier model with `K = 2` and `K = 12`, and explain how and why the test accuracy changes.\n4. Train the models on the first three years and test on the fourth, and check whether the STL and ETS model is still the best.\n5. Use `generate()` to estimate how many visits to expect in the four weeks before the first exam period of 2025/26, with a 95% interval.\n6. Write a short paragraph for the counselling service explaining what a 95% prediction interval means.\n7. In the artificial series of @fig-parts, double the standard deviation of the noise. Describe how the sum changes, and explain what this would mean for the width of forecast intervals.\n\n## Further reading\n\n- *Forecasting: Principles and Practice* [@hyndman2021], free online, is the standard introduction to forecasting, written around the fable packages used in this chapter.\n",
    "supporting": [
      "16-time-series_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}