{
  "hash": "957561b47cd3738615ebaab263f20cbc",
  "result": {
    "engine": "knitr",
    "markdown": "# ANOVA and Regression {#sec-ch07}\n\n\n\nChapter 6 compared two groups at a time. Elaf's next questions need more. Do stress levels differ between the five faculties, and between full-time and part-time students (RQ4)? What explains why some students get better grades than others (RQ5)? And what makes a student more likely to consider dropping out (RQ9)?\n\nThis chapter introduces two of the most widely used tools in research. **ANOVA** compares the averages of three or more groups. **Regression** models how an outcome depends on one or more predictors: linear regression for numeric outcomes such as GPA, and logistic regression for yes-or-no outcomes such as considering dropout.\n\n::: {.callout-tip appearance=\"simple\"}\n## By the end of this chapter you will be able to\n\n- Compare three or more groups with one-way ANOVA, and find which groups differ with post-hoc tests.\n- Analyse two grouping factors and their interaction with two-way ANOVA.\n- Fit and interpret simple and multiple linear regression models, including categorical predictors.\n- Use regression to separate a real effect from a confounder, and model curves and interactions.\n- Check a regression model's assumptions.\n- Fit and interpret a logistic regression model in terms of odds ratios and probabilities.\n- Report ANOVA and regression results in a thesis.\n:::\n\nThe chapter uses each student's first-semester records, their background information, and their questionnaire scores, calculated as in Chapter 3:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\n\nscores <- questionnaire |>\n  mutate(\n    stress_4 = 6 - stress_4,\n    stress   = rowMeans(pick(stress_1:stress_6), na.rm = TRUE),\n    support  = rowMeans(pick(support_1:support_6), na.rm = TRUE)\n  ) |>\n  select(student_id, stress, support)\n\nstudy <- students |>\n  left_join(scores, join_by(student_id)) |>\n  left_join(semesters |> filter(semester == 1), join_by(student_id))\n```\n:::\n\n\n## Comparing three or more groups: one-way ANOVA\n\nElaf wants to know whether stress differs between the five faculties. She could run a t-test for every pair of faculties, but that is 10 tests. Chapter 6 showed that each test has a 5% chance of a false alarm, and the chances add up: across 10 independent tests, the chance of at least one false alarm is about 40%. **Analysis of variance** (ANOVA) avoids the problem by asking one question first: do the faculty averages differ *at all*?\n\n### The idea\n\nANOVA compares two kinds of variation. Here are stress scores for three small groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_scores <- tibble(\n  group  = rep(c(\"A\", \"B\", \"C\"), each = 4),\n  stress = c(2.5, 3.0, 2.8, 3.1,   3.4, 3.8, 3.5, 3.9,   2.9, 3.3, 3.0, 3.4)\n)\ngroup_scores |> summarise(mean = mean(stress), .by = group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  group  mean\n  <chr> <dbl>\n1 A      2.85\n2 B      3.65\n3 C      3.15\n```\n\n\n:::\n:::\n\n\nThe group averages differ (variation *between* groups), and the scores within each group differ too (variation *within* groups). If the groups really are the same, the between-group variation should be no larger than you would expect from the within-group variation alone. ANOVA's **F statistic** is the ratio of the two:\n\n$$\nF = \\frac{\\text{variation between groups}}{\\text{variation within groups}}\n$$\n\nAn F close to 1 means the group averages differ no more than chance would produce; a large F means they differ more. `aov()` fits the model, and `summary()` shows the test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(stress ~ group, data = group_scores))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \ngroup        2  1.307  0.6533   10.69 0.00419 **\nResiduals    9  0.550  0.0611                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe p-value is small: these three groups differ.\n\n### Elaf's data\n\nFirst look at the data. @fig-stress-faculty shows stress in each faculty.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(study, aes(x = faculty, y = stress)) +\n  geom_boxplot() +\n  labs(x = NULL, y = \"Stress score (1 to 5)\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Stress scores by faculty.](07-anova-regression_files/figure-html/fig-stress-faculty-1.png){#fig-stress-faculty fig-alt='Five box plots of stress scores, one per faculty. Health Sciences is highest and Humanities lowest, with much overlap between all faculties.' width=672}\n:::\n:::\n\n\nThe faculties overlap a lot, but Health Sciences sits a little higher and Humanities a little lower. Now the test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstress_anova <- aov(stress ~ faculty, data = study)\nsummary(stress_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value  Pr(>F)   \nfaculty       4   8.72  2.1788   4.152 0.00252 **\nResiduals   595 312.19  0.5247                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nThe p-value is 0.003: the faculties do differ in stress. How much? **Eta squared** ($\\eta^2$), the share of all the variation in stress that lies between faculties, measures the size of the effect:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nss <- summary(stress_anova)[[1]][[\"Sum Sq\"]]\nss[1] / sum(ss)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02715776\n```\n\n\n:::\n:::\n\n\nOnly about 3% of the differences in stress between students have to do with their faculty; the rest is about the individual students. By common guidelines, an $\\eta^2$ of 0.01 is small, 0.06 medium, and 0.14 large [@cohen1988], so this is a real but small effect.\n\n### Which faculties differ? Post-hoc tests\n\nANOVA says that the faculties differ, but not which ones. **Post-hoc tests** compare every pair while keeping the overall chance of a false alarm at 5%. Tukey's test is the most common:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(stress_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = stress ~ faculty, data = study)\n\n$faculty\n                                        diff          lwr         upr     p adj\nHealth Sciences-Education         0.19429917 -0.033842346  0.42244068 0.1367660\nHumanities-Education             -0.14304647 -0.403603347  0.11751041 0.5614602\nNatural Sciences-Education       -0.05877343 -0.326527149  0.20898029 0.9749738\nSocial Sciences-Education         0.12216527 -0.123607736  0.36793827 0.6535324\nHumanities-Health Sciences       -0.33734564 -0.595910542 -0.07878073 0.0035331\nNatural Sciences-Health Sciences -0.25307260 -0.518888282  0.01274309 0.0707118\nSocial Sciences-Health Sciences  -0.07213390 -0.315794100  0.17152630 0.9275445\nNatural Sciences-Humanities       0.08427304 -0.209834619  0.37838070 0.9352210\nSocial Sciences-Humanities        0.26521174 -0.009035651  0.53945912 0.0635851\nSocial Sciences-Natural Sciences  0.18093870 -0.100155231  0.46203263 0.3973784\n```\n\n\n:::\n:::\n\n\nEach row compares two faculties: the difference in average stress, its confidence interval, and an adjusted p-value (`p adj`). Only one comparison is significant: Health Sciences students are more stressed than Humanities students, by about a third of a point. The other differences are small enough to be chance.\n\n### Checking the assumptions\n\nANOVA makes the same assumptions as the t-test: independent observations, roughly normal data within each group (or large groups), and similar spread in each group. The spread can be checked with **Levene's test**, from the **car** package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nleveneTest(stress ~ factor(faculty), data = study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   4  0.9429 0.4386\n      595               \n```\n\n\n:::\n:::\n\n\nThe p-value is large, so there is no evidence that the spread differs between faculties. When the assumptions fail, the **Kruskal-Wallis test** is the non-parametric alternative, comparing ranks instead of averages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(stress ~ faculty, data = study)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  stress by faculty\nKruskal-Wallis chi-squared = 15.46, df = 4, p-value = 0.003836\n```\n\n\n:::\n:::\n\n\nIt agrees with the ANOVA.\n\n## Two factors at once: two-way ANOVA\n\nDoes wellbeing depend on the programme (Master's or PhD), on study mode (full-time or part-time), or on both? A **two-way ANOVA** answers all three questions at once:\n\n- the **main effect** of programme: do Master's and PhD students differ, on average?\n- the **main effect** of study mode: do full-time and part-time students differ?\n- the **interaction**: does the effect of study mode *depend on* the programme? For example, is part-time study harder on PhD students than on Master's students?\n\nAn **interaction plot** shows the group averages as lines. If the lines are parallel, there is no interaction: the effect of study mode is the same in both programmes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy |>\n  summarise(wellbeing = mean(wellbeing), .by = c(programme, study_mode)) |>\n  ggplot(aes(x = programme, y = wellbeing, colour = study_mode, group = study_mode)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 3) +\n  scale_colour_viridis_d(end = 0.8) +\n  labs(x = NULL, y = \"Average wellbeing\", colour = \"Study mode\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Average first-semester wellbeing by programme and study mode.](07-anova-regression_files/figure-html/fig-interaction-1.png){#fig-interaction fig-alt='Two lines, for full-time and part-time students, across Master\\'s and PhD. Part-time is lower in both programmes; the lines are roughly parallel.' width=576}\n:::\n:::\n\n\nPart-time students have lower wellbeing in both programmes, and the lines are close to parallel. In the formula, `programme * study_mode` asks for both main effects and their interaction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(wellbeing ~ programme * study_mode, data = study))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      Df Sum Sq Mean Sq F value   Pr(>F)    \nprogramme              1    316   315.6   2.230 0.135913    \nstudy_mode             1   1640  1640.2  11.587 0.000709 ***\nprogramme:study_mode   1    119   118.6   0.838 0.360341    \nResiduals            596  84364   141.6                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nStudy mode has a clear effect. Programme does not, and neither does the interaction: part-time study lowers wellbeing by about the same amount whether a student is doing a Master's or a PhD. When an interaction *is* significant, interpret it before the main effects, because it means that no single \"effect of study mode\" describes everyone.\n\n## Linear regression\n\nANOVA compares groups. **Regression** goes further: it models how an outcome changes with one or more **predictors**, which can be numeric or categorical. It is the workhorse of quantitative research, and ANOVA is in fact a special case of it.\n\n### A straight line through the data\n\nHere are five students' sleep and GPA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfive <- tibble(\n  sleep = c(5, 6, 6.5, 7, 8),\n  gpa   = c(2.8, 3.0, 3.2, 3.1, 3.4)\n)\n```\n:::\n\n\n**Simple linear regression** fits the straight line that best describes how GPA changes with sleep:\n\n$$\n\\text{GPA} = b_0 + b_1 \\times \\text{sleep} + \\text{error}\n$$\n\n$b_0$ is the **intercept**, the predicted GPA for a student who sleeps zero hours, and $b_1$ is the **slope**, the change in predicted GPA for each extra hour of sleep. \"Best\" means the line that makes the squared vertical distances between the points and the line, the **residuals**, as small as possible, a method called **least squares**. `lm()`, for *linear model*, finds it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(gpa ~ sleep, data = five)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = gpa ~ sleep, data = five)\n\nCoefficients:\n(Intercept)        sleep  \n      1.865        0.190  \n```\n\n\n:::\n:::\n\n\nEach extra hour of sleep goes with a GPA that is about 0.19 higher. The intercept is where the line would cross zero hours of sleep, which no one does; it is needed to place the line, but it rarely means anything on its own.\n\n### Elaf's data\n\nNow all of Elaf's students. `summary()` gives the full results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_simple <- lm(gpa ~ sleep_hours, data = study)\nsummary(gpa_simple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = gpa ~ sleep_hours, data = study)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.97283 -0.20475 -0.00188  0.21898  0.94606 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.57713    0.08316   30.99  < 2e-16 ***\nsleep_hours  0.08081    0.01267    6.38 3.57e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3189 on 592 degrees of freedom\n  (6 observations deleted due to missingness)\nMultiple R-squared:  0.06433,\tAdjusted R-squared:  0.06275 \nF-statistic:  40.7 on 1 and 592 DF,  p-value: 3.573e-10\n```\n\n\n:::\n:::\n\n\nThe output has three parts:\n\n- **Coefficients**: the estimate of each coefficient, its standard error, a t statistic, and a p-value testing whether it is zero. The slope for `sleep_hours` is about 0.08: each extra hour of sleep goes with a GPA about 0.08 higher, and the p-value shows that this is not chance.\n- **R-squared**: the share of the variation in GPA that the model explains. Here it is only 0.06: sleep explains about 6% of the differences in GPA. Sleep matters, but it is far from the whole story, just as the scatter plot in Chapter 4 suggested.\n- **Residual standard error**: the typical distance between a student's actual GPA and the line, about 0.3 points.\n\n### Multiple regression\n\nMany things affect grades at once. **Multiple regression** includes several predictors in one model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_model <- lm(gpa ~ sleep_hours + study_hours + stress + support, data = study)\nsummary(gpa_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = gpa ~ sleep_hours + study_hours + stress + support, \n    data = study)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.86953 -0.19437  0.00526  0.18957  0.76429 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.137403   0.145279  14.712  < 2e-16 ***\nsleep_hours  0.106041   0.014163   7.487 2.62e-13 ***\nstudy_hours  0.006928   0.001105   6.270 7.06e-10 ***\nstress      -0.083526   0.017827  -4.685 3.48e-06 ***\nsupport      0.110733   0.016696   6.632 7.57e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2857 on 582 degrees of freedom\n  (13 observations deleted due to missingness)\nMultiple R-squared:  0.2525,\tAdjusted R-squared:  0.2473 \nF-statistic: 49.14 on 4 and 582 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nEach coefficient now means the change in predicted GPA for a one-unit increase in that predictor, **holding the other predictors constant**. Among students with the same study hours, stress, and support, each extra hour of sleep goes with a GPA about 0.11 higher. Each extra hour of study per week adds about 0.007, each point of stress lowers GPA by about 0.08, and each point of supervisor support raises it by about 0.11. All four are significant.\n\nTogether, the four predictors explain about 25% of the variation in GPA. That may sound modest, but grades depend on many things no survey measures, from ability to luck on exam day. In social and educational research, models that explain a quarter of the variation are common and useful. The **adjusted R-squared** is slightly lower, because it corrects for the number of predictors: adding any predictor, even a useless one, raises R-squared a little, but only a useful one raises the adjusted version.\n\nNotice the line `(13 observations deleted due to missingness)`: `lm()` leaves out students with a missing value in any variable of the model. Report the number of students each model is based on.\n\n### Categorical predictors\n\nCategorical variables can be predictors too. Does gender matter, once the other predictors are taken into account?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_gender <- lm(gpa ~ sleep_hours + study_hours + stress + support + gender, data = study)\nsummary(gpa_gender)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate  Std. Error    t value     Pr(>|t|)\n(Intercept)  2.123737610 0.147260520 14.4216360 1.592391e-40\nsleep_hours  0.106600187 0.014203710  7.5050947 2.318148e-13\nstudy_hours  0.006995075 0.001111694  6.2922647 6.163042e-10\nstress      -0.082830266 0.017877519 -4.6332081 4.447816e-06\nsupport      0.110525008 0.016709773  6.6143931 8.474218e-11\ngenderMale   0.013815196 0.023831664  0.5796992 5.623422e-01\n```\n\n\n:::\n:::\n\n\nR turns a categorical predictor into a comparison with a **reference category**, by default the first in alphabetical order: here `Female`. The coefficient `genderMale` is the difference between men and women, holding everything else constant. It is tiny and far from significant: there is no evidence that gender affects GPA. That is a finding too, and worth reporting.\n\nFor a variable with more categories, such as faculty, R compares each category with the reference, giving one coefficient for each of the others. To choose a different reference, use `relevel(factor(faculty), ref = \"Humanities\")`.\n\n### Separating an effect from a confounder\n\nIn Chapter 5, students who took more caffeine had lower GPAs, but they also slept less. Does caffeine harm grades, or is sleep the real reason? Regression can tell the two explanations apart. First caffeine alone:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(gpa ~ caffeine_mg, data = study))$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate   Std. Error    t value     Pr(>|t|)\n(Intercept)  3.1849088129 2.195535e-02 145.063026 0.000000e+00\ncaffeine_mg -0.0004331688 9.239351e-05  -4.688303 3.418851e-06\n```\n\n\n:::\n:::\n\n\nCaffeine has a significant negative effect. Now add sleep:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(gpa ~ caffeine_mg + sleep_hours, data = study))$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate   Std. Error    t value     Pr(>|t|)\n(Intercept)  2.6380932284 0.1238298172 21.3041841 4.534485e-75\ncaffeine_mg -0.0000780726 0.0001194238 -0.6537443 5.135321e-01\nsleep_hours  0.0738597698 0.0165663746  4.4584148 9.891313e-06\n```\n\n\n:::\n:::\n\n\nOnce sleep is held constant, caffeine's effect shrinks to almost nothing and is no longer significant, while sleep stays significant. Among students who sleep the same amount, caffeine makes no difference to grades. Caffeine looked harmful only because heavy caffeine users sleep less: sleep was a **confounder**.\n\n::: {.callout-important}\n## Regression adjusts only for what you include\n\nRegression can remove the effect of a confounder only if you measured it and put it in the model. It cannot adjust for anything you did not measure. That is why, outside a randomised experiment like Elaf's workshop, regression shows associations *adjusted for* the variables in the model, not proof of cause.\n:::\n\n### Curved relationships\n\nA straight line assumes that every extra hour of study adds the same amount to GPA. Is that realistic? Adding a squared term lets the line curve:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_curve <- lm(gpa ~ study_hours + I(study_hours^2), data = study)\nsummary(gpa_curve)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      Estimate   Std. Error   t value      Pr(>|t|)\n(Intercept)       2.8630064457 5.380474e-02 53.211044 3.718109e-227\nstudy_hours       0.0183480169 3.914705e-03  4.686947  3.448155e-06\nI(study_hours^2) -0.0002874497 6.488183e-05 -4.430358  1.121887e-05\n```\n\n\n:::\n:::\n\n\n`I()` tells R to calculate `study_hours^2` before fitting. The squared term is negative and significant: the line bends downwards. @fig-curve shows the shape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(study, aes(x = study_hours, y = gpa)) +\n  geom_point(alpha = 0.3) +\n  geom_smooth(method = \"lm\", formula = y ~ x + I(x^2)) +\n  labs(x = \"Study hours per week\", y = \"GPA\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![GPA and weekly study hours, with a curved (quadratic) trend line.](07-anova-regression_files/figure-html/fig-curve-1.png){#fig-curve fig-alt='Scatter plot of GPA against study hours, with a curve that rises steeply at first and flattens out at around 30 hours a week.' width=624}\n:::\n:::\n\n\nThe first hours of study make a real difference; beyond about 30 hours a week, more study brings little or nothing extra. Economists call this **diminishing returns**, and it is worth knowing for any student tempted to study all night instead of sleeping.\n\n### Interactions\n\nDoes supervisor support matter equally for every student? An **interaction** term lets the effect of one predictor depend on another. `support * programme` gives the effect of support, the effect of programme, and how the effect of support differs between programmes. To make the coefficients easier to read, support is first **centred**: the average is subtracted, so that zero means \"average support\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy <- study |> mutate(support_c = support - mean(support))\ngpa_interaction <- lm(gpa ~ support_c * programme + sleep_hours + study_hours, data = study)\nsummary(gpa_interaction)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         Estimate  Std. Error    t value     Pr(>|t|)\n(Intercept)            2.15459277 0.112180214 19.2065312 5.044803e-64\nsupport_c              0.10210747 0.018389506  5.5524856 4.288901e-08\nprogrammePhD           0.01173221 0.026136331  0.4488851 6.536819e-01\nsleep_hours            0.11771209 0.014038094  8.3851901 3.842792e-16\nstudy_hours            0.00656252 0.001109605  5.9142870 5.691946e-09\nsupport_c:programmePhD 0.13416356 0.035844599  3.7429227 1.999717e-04\n```\n\n\n:::\n:::\n\n\n\n\nFor Master's students (the reference category), each point of support goes with a GPA about 0.10 higher. The interaction coefficient, `support_c:programmePhD`, says that for PhD students the effect is larger, by about 0.13, making it about 0.24. Supervisor support matters more than twice as much for PhD students, which makes sense: a PhD depends more heavily on the supervisor.\n\n### Checking the model\n\nLinear regression assumes that the relationship is linear (or modelled as curved, as above), that the residuals have similar spread everywhere, and that they are roughly normal. As always, graphs are the best check. `plot()` on a model draws four diagnostic plots; the first two matter most:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(gpa_model, which = 1:2)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Diagnostic plots for the GPA model: residuals against fitted values (left), and a Q-Q plot of the residuals (right).](07-anova-regression_files/figure-html/fig-diagnostics-1.png){#fig-diagnostics fig-alt='Left: residuals scattered evenly around zero across all fitted values, with no pattern. Right: residual Q-Q plot with points close to the diagonal.' width=768}\n:::\n:::\n\n\nIn the left plot, the residuals should form a shapeless band around zero, with no curve and no funnel. In the right plot, they should follow the line. Both look good for Elaf's model. A curve in the left plot would suggest a missing curved term; a funnel shape would mean the spread is not constant; and points far off the line on the right would point to unusual cases worth looking at.\n\n### Reporting a regression\n\nThe **broom** package turns model results into tidy tables, ready for a thesis. `tidy()` gives the coefficients with confidence intervals, and `glance()` the overall fit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\ntidy(gpa_model, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)  2.14      0.145       14.7  6.89e-42  1.85      2.42   \n2 sleep_hours  0.106     0.0142       7.49 2.62e-13  0.0782    0.134  \n3 study_hours  0.00693   0.00111      6.27 7.06e-10  0.00476   0.00910\n4 stress      -0.0835    0.0178      -4.69 3.48e- 6 -0.119    -0.0485 \n5 support      0.111     0.0167       6.63 7.57e-11  0.0779    0.144  \n```\n\n\n:::\n\n```{.r .cell-code}\nglance(gpa_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.252         0.247 0.286      49.1 1.25e-35     4  -95.0  202.  228.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-tip}\n## Writing it up\n\nA multiple regression of first-semester GPA on sleep, study hours, stress, and supervisor support explained 25% of the variance in GPA, *F*(4, 582) = 49.14, *p* < .001, *N* = 587. Holding the other predictors constant, each additional hour of sleep was associated with a GPA 0.11 points higher (95% CI [0.08, 0.13]).\n:::\n\n## Logistic regression\n\nElaf's third question is about a yes-or-no outcome: has a student considered dropping out? Linear regression is the wrong tool here: it could predict probabilities below 0 or above 1, which make no sense. **Logistic regression** models the probability of a \"yes\" in a way that always stays between 0 and 1.\n\n### Odds and odds ratios\n\nLogistic regression works with **odds** rather than probabilities. The odds of an event are the probability that it happens divided by the probability that it does not. Take the table from Chapter 6:\n\n\n::: {.cell}\n\n```{.r .cell-code}\njobs <- table(students$employment, students$considering_dropout)\njobs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                 No Yes\n  Full-time job  72  25\n  None          265  42\n  Part-time job 173  23\n```\n\n\n:::\n:::\n\n\nAmong students with a full-time job, 25 have considered dropping out and 72 have not: odds of 25/72, about 0.35. Among students without a job, the odds are 42/265, about 0.16. The **odds ratio** compares them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodds_full <- 25 / 72\nodds_none <- 42 / 265\nodds_full / odds_none\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.190807\n```\n\n\n:::\n:::\n\n\nStudents with a full-time job have about twice the odds of considering dropout. An odds ratio of 1 means no difference, above 1 means higher odds, and below 1 means lower odds.\n\n### Elaf's model\n\n`glm()`, for *generalised linear model*, fits logistic regression when told `family = binomial`. The outcome must be coded 0 and 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy <- study |> mutate(dropout = as.integer(considering_dropout == \"Yes\"))\n\ndropout_model <- glm(\n  dropout ~ stress + support + financial_worry + employment + study_mode,\n  data = study, family = binomial\n)\nsummary(dropout_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Estimate Std. Error   z value     Pr(>|z|)\n(Intercept)             -4.0185658  1.2316928 -3.262636 1.103811e-03\nstress                   1.2822937  0.2398794  5.345576 9.012973e-08\nsupport                 -1.1102419  0.2039547 -5.443572 5.222263e-08\nfinancial_worry          0.4537396  0.1216263  3.730605 1.910209e-04\nemploymentNone          -0.5892840  0.4378768 -1.345776 1.783748e-01\nemploymentPart-time job -0.5387011  0.4522237 -1.191227 2.335644e-01\nstudy_modePart-time      0.2763818  0.3674127  0.752238 4.519079e-01\n```\n\n\n:::\n:::\n\n\nThe coefficients are on the scale of **log-odds**, which is hard to interpret directly. `exp()` turns them into odds ratios, and `confint.default()` gives their confidence intervals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(odds_ratio = coef(dropout_model), confint.default(dropout_model))) |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        odds_ratio 2.5 % 97.5 %\n(Intercept)                   0.02  0.00   0.20\nstress                        3.60  2.25   5.77\nsupport                       0.33  0.22   0.49\nfinancial_worry               1.57  1.24   2.00\nemploymentNone                0.55  0.24   1.31\nemploymentPart-time job       0.58  0.24   1.42\nstudy_modePart-time           1.32  0.64   2.71\n```\n\n\n:::\n:::\n\n\n\n\nReading the odds ratios, holding the other predictors constant:\n\n- Each extra point of **stress** multiplies the odds of considering dropout by about 3.6.\n- Each extra point of **supervisor support** multiplies them by about 0.33, cutting them by two thirds.\n- Each extra point of **financial worry** multiplies them by about 1.6.\n\nSomething interesting has happened to **employment**. In Chapter 6, and in the odds ratio above, students with full-time jobs were about twice as likely to consider dropping out. In this model, the confidence intervals for employment include 1: once stress and financial worry are taken into account, having a job adds little on its own. The likely explanation is that a full-time job matters *because* of the stress and money pressure that come with it. This is the kind of insight multiple regression makes possible.\n\n### Predicted probabilities\n\nOdds ratios are hard for many readers. Predicted probabilities are easier. What is the predicted probability of considering dropout for two example students, identical except for their stress and support?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexamples <- tibble(\n  stress          = c(2.5, 4.0),\n  support         = c(4.0, 2.0),\n  financial_worry = 3,\n  employment      = \"None\",\n  study_mode      = \"Full-time\"\n)\npredict(dropout_model, newdata = examples, type = \"response\") |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   1    2 \n0.01 0.42 \n```\n\n\n:::\n:::\n\n\n`type = \"response\"` asks for probabilities rather than log-odds. A student with low stress and good support has about a 1% chance of considering dropout; a stressed student with little support, about 42%. For Elaf's recommendations, that contrast is more persuasive than any coefficient.\n\nHow well does the model *predict* who will consider dropping out, and how should that be tested fairly? That is a different question, about prediction rather than explanation, and it is the subject of Chapters 10 and 11.\n\n::: {.callout-note icon=\"false\"}\n## In your field: forestry and agriculture\n\nR's `trees` dataset records the girth, height, and timber volume of 31 felled black cherry trees. Foresters need to estimate a standing tree's volume from measurements they can take without cutting it down, a classic job for multiple regression:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntree_model <- lm(Volume ~ Girth + Height, data = trees)\nsummary(tree_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error   t value     Pr(>|t|)\n(Intercept) -57.9876589  8.6382259 -6.712913 2.749507e-07\nGirth         4.7081605  0.2642646 17.816084 8.223304e-17\nHeight        0.3392512  0.1301512  2.606594 1.449097e-02\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(tree_model)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.94795\n```\n\n\n:::\n:::\n\n\nGirth and height together explain about 95% of the variation in volume. Physical measurements are often far more predictable than human behaviour: compare this with the 25% of Elaf's GPA model.\n:::\n\n## Chapter review\n\n### Summary\n\n- One-way ANOVA tests whether three or more group averages differ, with one test instead of many. The F statistic compares variation between groups with variation within them; $\\eta^2$ measures the size of the effect.\n- Post-hoc tests, such as Tukey's, find which groups differ while controlling false alarms. Levene's test checks equal spread; Kruskal-Wallis is the non-parametric alternative.\n- Two-way ANOVA tests two main effects and their interaction. An interaction means the effect of one factor depends on the other; parallel lines in an interaction plot mean no interaction.\n- Linear regression models a numeric outcome. A slope is the change in the outcome for a one-unit change in the predictor; in multiple regression, holding the other predictors constant. R-squared is the share of variation explained.\n- Categorical predictors are compared with a reference category. Adding a confounder to the model can remove a misleading effect, but only confounders that were measured.\n- Squared terms model curves; interaction terms let one predictor's effect depend on another. Check residual plots for patterns.\n- Logistic regression models the probability of a yes-or-no outcome. `exp()` of its coefficients gives odds ratios; `predict(..., type = \"response\")` gives probabilities.\n\n### Key terms\n\nANOVA, F statistic, between-group variation, within-group variation, eta squared, post-hoc test, Tukey's test, Levene's test, Kruskal-Wallis test, two-way ANOVA, main effect, interaction, interaction plot, linear regression, predictor, outcome, intercept, slope, residual, least squares, R-squared, adjusted R-squared, multiple regression, reference category, confounder, quadratic term, diminishing returns, centring, diagnostic plot, logistic regression, odds, odds ratio, log-odds, predicted probability.\n\n## Exercises\n\nThe [playground](../playground/chapter07.html) has these and more, with hints and solutions.\n\n1. Does first-semester wellbeing differ between faculties? Run a one-way ANOVA, calculate $\\eta^2$, and, if the ANOVA is significant, run Tukey's test.\n2. Fit a simple regression of first-semester wellbeing on sleep hours. Interpret the slope and R-squared.\n3. Add stress and support to the model from Exercise 2. What happens to the slope of sleep, and to R-squared?\n4. Add `study_mode` to the model from Exercise 3. What is the reference category, and what does its coefficient mean?\n5. Fit a logistic regression of considering dropout on `burnout` score alone (calculate it from the questionnaire first), and report its odds ratio. What does it mean?\n\n## Further reading\n\n- *Introduction to Modern Statistics* [@cetinkaya2024ims]: chapters \"Linear regression with a single predictor\", \"Linear regression with multiple predictors\", \"Logistic regression\", and \"Inference for comparing many means\".\n- *Regression and Other Stories* [@gelman2020] is an excellent next step, with a strong focus on interpreting and checking regression models in real research.\n",
    "supporting": [
      "07-anova-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}