{
  "hash": "855c39cbc200ec25d7b105c09fe8f168",
  "result": {
    "engine": "knitr",
    "markdown": "# Hypothesis Testing and Statistical Inference {#sec-ch06}\n\n\n\nElaf's sample is described. Now come the questions her thesis was designed to answer. Do graduate students sleep less than the recommended 7 hours (RQ2)? Did the wellbeing workshop improve wellbeing (RQ3)? Is having a job related to thinking about dropping out?\n\nEach question is about graduate students *in general*, but Elaf has data on only 600 of them. **Statistical inference** is the set of tools for drawing conclusions about a whole population from a sample, and for saying how confident we can be. This chapter builds up those tools, from the idea of a sampling distribution to the tests that appear in almost every thesis.\n\n::: {.callout-tip appearance=\"simple\"}\n## By the end of this chapter you will be able to\n\n- Explain sampling distributions, the standard error, and the central limit theorem.\n- Calculate and interpret confidence intervals, including bootstrap intervals.\n- Explain the logic of a hypothesis test, p-values, and the two kinds of error.\n- Carry out one-sample, two-sample, and paired t-tests, and measure the size of an effect.\n- Check the assumptions of a test, and choose non-parametric tests when they fail.\n- Test relationships between categorical variables with chi-square tests.\n- Choose the right test for a question, and report the result in a thesis.\n:::\n\n## From sample to population\n\nThe **population** is everyone you want to draw conclusions about: here, graduate students. The **sample** is the people you actually measured: Elaf's 600 students. A number that describes the population, such as the true average sleep of all graduate students, is a **parameter**. We never know it exactly. The same number calculated from the sample, such as the average sleep of Elaf's 600, is a **statistic**, and it is our estimate of the parameter.\n\nThe problem is that a different sample would give a slightly different estimate. How much would it vary? To see, pretend for a moment that Elaf's 600 students *are* the whole population, draw many small samples from them, and watch what happens.\n\n### Sampling distributions\n\nCaffeine intake is strongly skewed (Chapter 5): most students take a moderate amount, and a few take a great deal. Draw a sample of 5 students, and calculate their average caffeine. Then do it again, and again, a thousand times. `sample()` draws a random sample, and `replicate()` repeats the whole thing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\n\nfirst_sem <- semesters |>\n  filter(semester == 1) |>\n  left_join(students, join_by(student_id))\n\ncaffeine <- first_sem$caffeine_mg[!is.na(first_sem$caffeine_mg)]\n\nset.seed(2026)\nmeans_5  <- replicate(1000, mean(sample(caffeine, 5)))\nmeans_30 <- replicate(1000, mean(sample(caffeine, 30)))\n```\n:::\n\n\n`set.seed()` fixes R's random number generator, so that the \"random\" samples are the same every time the code runs, and you get the same results as in this book. Use it whenever your analysis involves randomness.\n\nThe thousand averages form a **sampling distribution**: the distribution of a statistic over many possible samples. @fig-clt compares the sampling distributions for samples of 5 and of 30 students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  mean_caffeine = c(means_5, means_30),\n  sample_size   = rep(c(\"Samples of 5\", \"Samples of 30\"), each = 1000)\n) |>\n  mutate(sample_size = factor(sample_size, levels = c(\"Samples of 5\", \"Samples of 30\"))) |>\n  ggplot(aes(x = mean_caffeine)) +\n  geom_histogram(bins = 40, fill = \"grey70\", colour = \"white\") +\n  facet_wrap(~ sample_size) +\n  labs(x = \"Average caffeine in the sample (mg)\", y = \"Number of samples\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![The sampling distribution of average caffeine intake, for samples of 5 and of 30 students drawn from Elaf's data.](06-hypothesis-testing_files/figure-html/fig-clt-1.png){#fig-clt fig-alt='Two histograms. For samples of 5, the averages are widely spread and skewed to the right. For samples of 30, they are narrow and nearly symmetrical, centred on the same value.' width=672}\n:::\n:::\n\n\nThree things stand out, and together they are the foundation of statistical inference:\n\n1. **Both are centred on the true average.** The average of all 600 students is 189 mg, and both sampling distributions centre on it. A sample average is an unbiased estimate.\n2. **Larger samples vary less.** Averages of 5 students range widely; averages of 30 are much more tightly packed. Larger samples give more precise estimates.\n3. **Larger samples give a bell shape, even from skewed data.** Caffeine itself is strongly skewed, and so are the averages of 5 students. But the averages of 30 students are almost symmetrical and bell-shaped.\n\nThe third point is the **central limit theorem**: whatever the shape of the data, the averages of reasonably large samples follow an approximately normal distribution. It is why tests based on the normal distribution work for so many kinds of data. As a rule of thumb, samples of 30 or more are usually large enough, unless the data is extremely skewed.\n\n### The standard error\n\nThe spread of a sampling distribution has its own name: the **standard error** (SE). It measures how much an estimate would vary from sample to sample, which is exactly the uncertainty we want to know. In practice we have only one sample, so we cannot draw a thousand. Fortunately, the standard error of an average can be calculated from a single sample:\n\n$$\nSE = \\frac{s}{\\sqrt{n}}\n$$\n\nwhere $s$ is the standard deviation and $n$ the sample size. Compare the formula with the simulation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(means_30)                       # spread of the 1,000 simulated averages\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.69209\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(caffeine) / sqrt(30)            # the formula, from the data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 26.22184\n```\n\n\n:::\n:::\n\n\nThey agree closely. Notice the $\\sqrt{n}$: to halve the standard error, you need four times as many people.\n\n### Confidence intervals\n\nAn estimate on its own says nothing about how precise it is. A **confidence interval** (CI) adds that information: a range of values that are plausible for the population parameter, given the data. A 95% confidence interval for a mean is approximately\n\n$$\n\\bar{x} \\pm 2 \\times SE\n$$\n\n(more precisely, the 2 is a value from the *t*-distribution, which R works out for you). `t.test()` calculates the confidence interval for you. Here it is for the average sleep of Elaf's students in their first semester:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(first_sem$sleep_hours)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.400196 6.566808\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nThe average sleep of graduate students is plausibly between about 6.4 and 6.6 hours. The interval is narrow because the sample is large.\n\nWhat does \"95%\" mean? If the study were repeated many times, and a 95% confidence interval calculated each time, about 95% of those intervals would contain the true population value. It is a statement about the method, not a 95% probability that this particular interval is right.\n\n::: {.callout-warning}\n## Mean ± SE is not a confidence interval\n\nTheses often report \"mean ± SE\" and treat it as if it were a confidence interval. It is not: the SE is only half the width of an approximate 95% CI. Report the confidence interval itself, and say what it is.\n:::\n\n### Bootstrap confidence intervals\n\nThe formula above works for averages. For other statistics, such as the median, there is no simple formula. The **bootstrap** gets around this with a clever idea: treat the sample as if it were the population, and draw many new samples from it *with replacement*, so that each new sample contains some people twice and leaves others out. The spread of the statistic across these resamples estimates its sampling distribution.\n\nSuppose Elaf had surveyed only 40 students and wanted a confidence interval for their median caffeine intake:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nsmall_sample <- sample(caffeine, 40)\nmedian(small_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150\n```\n\n\n:::\n\n```{.r .cell-code}\nboot_medians <- replicate(2000, median(sample(small_sample, replace = TRUE)))\nquantile(boot_medians, c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5% 97.5% \n110.0 177.5 \n```\n\n\n:::\n:::\n\n\n`replace = TRUE` is what makes it a bootstrap. The middle 95% of the 2,000 bootstrap medians, from the 2.5th to the 97.5th percentile, is the 95% bootstrap confidence interval. The median of all 600 students, 160 mg, lies inside it. The same few lines work for almost any statistic.\n\n## The logic of hypothesis testing\n\nA confidence interval says what values are plausible. A **hypothesis test** answers a yes-or-no question: is the data consistent with a particular claim?\n\nEvery test starts with two statements:\n\n- The **null hypothesis**, $H_0$, is the claim of \"no effect\": no difference, no relationship. For example: *the workshop has no effect on wellbeing*.\n- The **alternative hypothesis**, $H_1$, is what the researcher suspects: *the workshop does affect wellbeing*.\n\nThe test then asks: **if the null hypothesis were true, how surprising would our data be?** The answer is the **p-value**: the probability of getting a result at least as extreme as ours, if the null hypothesis were true.\n\n- A small p-value means the data would be surprising if $H_0$ were true, so we **reject** $H_0$. By convention, \"small\" means below 0.05, a threshold called the **significance level**, $\\alpha$. Such a result is called **statistically significant**.\n- A large p-value means the data is consistent with $H_0$, so we **fail to reject** it. This is not proof that $H_0$ is true. It means only that the data does not provide strong evidence against it.\n\n::: {.callout-important}\n## What a p-value is not\n\nA p-value is **not** the probability that the null hypothesis is true, and **not** the probability that the result happened by chance. It is the probability of data like yours, *assuming* the null hypothesis is true. A p-value of 0.03 means: if the workshop had no effect, a difference this large would appear in only 3% of studies like this one.\n:::\n\n### Two kinds of error\n\nBecause tests work with probabilities, they can be wrong in two ways:\n\n| | $H_0$ is really true | $H_0$ is really false |\n|---|---|---|\n| **Reject $H_0$** | Type I error (a false alarm) | Correct |\n| **Fail to reject $H_0$** | Correct | Type II error (a missed effect) |\n\n: The two kinds of error in hypothesis testing {#tbl-errors}\n\nThe significance level controls Type I errors: with $\\alpha = 0.05$, about 5% of tests of a true null hypothesis will be \"significant\" by chance alone. You can see this happen. Split Elaf's students into two groups completely at random, so that there can be no real difference, and test whether their wellbeing differs. Then do it a thousand times:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\np_values <- replicate(1000, {\n  random_group <- sample(rep(c(\"A\", \"B\"), 300))\n  t.test(first_sem$wellbeing ~ random_group)$p.value\n})\nmean(p_values < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.065\n```\n\n\n:::\n:::\n\n\nAbout 6% of the tests are \"significant\", even though every difference is pure chance: close to the 5% the significance level predicts (with only 1,000 repetitions, a little variation is expected). This is one reason a single significant result is never the final word, and why running many tests and reporting only the significant ones is misleading.\n\nType II errors are reduced by larger samples: the more data, the easier it is to detect a real effect.\n\n### One-tailed and two-tailed tests\n\nA **two-tailed** test looks for a difference in either direction: the workshop might raise *or* lower wellbeing. A **one-tailed** test looks in one direction only. One-tailed tests are easier to pass, which makes them tempting, but they are justified only when the opposite direction is truly impossible or irrelevant, and when the direction was decided before seeing the data. Use two-tailed tests unless you have a strong reason not to. R's tests are two-tailed by default.\n\n### Statistical and practical significance\n\nA statistically significant result is not necessarily an important one. With a large enough sample, even a tiny, meaningless difference becomes significant. Always report *how big* the effect is, not just whether it is significant. The rest of this chapter does that for each test.\n\n## Comparing a mean with a value: the one-sample t-test\n\nElaf's second research question asks whether graduate students sleep less than the recommended 7 hours (RQ2). The hypotheses are:\n\n- $H_0$: the average sleep of graduate students is 7 hours.\n- $H_1$: it is not 7 hours.\n\nA **one-sample t-test** compares a sample average with a fixed value, given by the argument `mu`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_test <- t.test(first_sem$sleep_hours, mu = 7)\nsleep_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  first_sem$sleep_hours\nt = -12.177, df = 593, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 7\n95 percent confidence interval:\n 6.400196 6.566808\nsample estimates:\nmean of x \n 6.483502 \n```\n\n\n:::\n:::\n\n\n\n\nThe output has three parts to read:\n\n- **The estimate**: the sample average, 6.48 hours.\n- **The confidence interval**: 6.40 to 6.57 hours. It does not include 7.\n- **The test**: the *t* statistic measures how far the average is from 7, in standard errors: more than 12 standard errors below. The p-value is so small that R prints it as \"< 2.2e-16\", meaning less than 0.0000000000000002.\n\nGraduate students sleep about half an hour less than recommended, and the difference is far too large to be chance. The confidence interval also answers the practical question: the shortfall is somewhere between about 26 and 36 minutes a night.\n\n::: {.callout-note}\n## One value per student\n\nThe test uses first-semester records only, one value per student. A t-test assumes that the observations are **independent**. Using all four semesters would count each student up to four times, as if they were four different people, and make the result look more certain than it is. Chapter 9 shows how to analyse repeated measurements properly.\n:::\n\n## Comparing two groups: the two-sample t-test {#sec-comparing-groups}\n\nNow Elaf's central question (RQ3). Half of her students were invited, at random, to a six-week wellbeing workshop after their first semester. **Did the workshop improve their wellbeing?**\n\n### The idea on a handful of numbers\n\nImagine only five students in each group, with these wellbeing scores (out of 100):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninvited     <- c(68, 72, 65, 75, 70)\nnot_invited <- c(62, 66, 60, 69, 64)\n\nmean(invited)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(not_invited)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64.2\n```\n\n\n:::\n:::\n\n\nThe invited group is 5.8 points higher on average. Is that more than chance? A **two-sample t-test** compares the averages of two independent groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmall_test <- t.test(invited, not_invited)\nsmall_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  invited and not_invited\nt = 2.5099, df = 7.9411, p-value = 0.03658\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n  0.4642934 11.1357066\nsample estimates:\nmean of x mean of y \n     70.0      64.2 \n```\n\n\n:::\n:::\n\n\nThe p-value is 0.037: if the workshop had no effect, a difference this large would appear in about 4 studies in 100. By the usual 0.05 threshold, it is statistically significant, though with only five students per group, it is fragile evidence.\n\n### Elaf's data\n\nNow the real study. First, combine each student's workshop group with their semester 2 wellbeing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemester2 <- semesters |>\n  filter(semester == 2) |>\n  left_join(students, join_by(student_id))\nnrow(semester2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 600\n```\n\n\n:::\n:::\n\n\nAlways look before testing. @fig-workshop shows wellbeing in each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(semester2, aes(x = workshop, y = wellbeing, fill = workshop)) +\n  geom_boxplot(show.legend = FALSE, width = 0.5) +\n  labs(x = NULL, y = \"Wellbeing (0 to 100)\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Wellbeing at the end of semester 2, by workshop group. Each box shows the middle half of the students; the line inside is the median.](06-hypothesis-testing_files/figure-html/fig-workshop-1.png){#fig-workshop fig-alt='Box plot of wellbeing scores for invited and not-invited students. The invited group\\'s box sits a few points higher.' width=576}\n:::\n:::\n\n\nThe invited group sits a little higher, but the groups overlap a lot. Now the test. The formula `wellbeing ~ workshop` reads \"wellbeing by workshop group\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- t.test(wellbeing ~ workshop, data = semester2)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  wellbeing by workshop\nt = 5.469, df = 597.52, p-value = 6.66e-08\nalternative hypothesis: true difference in means between group Invited and group Not invited is not equal to 0\n95 percent confidence interval:\n 3.364699 7.135301\nsample estimates:\n    mean in group Invited mean in group Not invited \n                    65.47                     60.22 \n```\n\n\n:::\n:::\n\n\n\n\nInvited students scored 5.2 points higher on average (65.5 against 60.2). The 95% confidence interval for the difference runs from 3.4 to 7.1 points, and the p-value is below 0.001. The difference is very unlikely to be chance. And because students were invited **at random**, Elaf can conclude that the workshop *caused* the improvement, not just that it went with it: randomisation makes the two groups alike in everything except the invitation.\n\nThe heading of the output, \"Welch Two Sample t-test\", names the version R uses by default. It does not assume that the two groups have equal spread, which makes it the safer choice. Use it unless you have a reason not to.\n\n### How big is the difference?\n\nFive points on a 100-point scale: is that a lot? One common way to judge is **Cohen's *d***, the difference between the means divided by the standard deviation. It expresses the difference in standard deviations, so it can be compared across studies and scales:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninv <- semester2$wellbeing[semester2$workshop == \"Invited\"]\nnot <- semester2$wellbeing[semester2$workshop == \"Not invited\"]\nd <- (mean(inv) - mean(not)) / sqrt((var(inv) + var(not)) / 2)\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4465413\n```\n\n\n:::\n:::\n\n\nCohen's guidelines call 0.2 a small effect, 0.5 medium, and 0.8 large [@cohen1988]. At about 0.45, the workshop's effect is small to medium: a real improvement, but not a transformation. For a six-week workshop, that is a worthwhile result, and exactly the kind of judgement a thesis discussion should make.\n\n## Comparing the same people twice: the paired t-test\n\nThe two-sample t-test compared two different groups of students. Elaf can also ask a different question: did the invited students' own wellbeing rise from semester 1 to semester 2? Now the same students are measured twice, so the two sets of scores are **paired**. Each student is compared with themselves, which removes the large differences *between* students and makes the test more sensitive.\n\nThe data needs one row per student, with the two semesters side by side (Chapter 3):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\n\ninvited_wide <- semesters |>\n  filter(semester %in% c(1, 2)) |>\n  left_join(students, join_by(student_id)) |>\n  filter(workshop == \"Invited\") |>\n  select(student_id, semester, wellbeing) |>\n  pivot_wider(names_from = semester, values_from = wellbeing,\n              names_prefix = \"semester_\")\n\nt.test(invited_wide$semester_2, invited_wide$semester_1, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  invited_wide$semester_2 and invited_wide$semester_1\nt = 10.936, df = 299, p-value < 2.2e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 3.955360 5.691307\nsample estimates:\nmean difference \n       4.823333 \n```\n\n\n:::\n:::\n\n\nThe invited students' wellbeing rose by 4.8 points on average, and the change is clearly significant.\n\nBut notice what this test cannot tell Elaf: *why* wellbeing rose. It could be the workshop, or it could be that semester 2 is simply less stressful than semester 1 for everyone. The paired test has no comparison group. The two-sample test above, comparing invited with not-invited students, is the one that answers the causal question. Choosing the design that actually answers your question is as important as running the test correctly.\n\n## Checking the assumptions\n\nEvery test rests on assumptions. For t-tests, they are:\n\n1. **Independence**: each observation comes from a different person (or, for the paired test, each *pair* does). This is a matter of study design, not something you can test.\n2. **Approximate normality**: the data in each group is roughly normal, or the sample is large enough for the central limit theorem to help. With 30 or more per group, moderate skewness is not a problem.\n3. **Similar spread**: required only by the classic version of the two-sample test; Welch's version, R's default, does not need it.\n\nCheck normality with graphs: a histogram and a Q-Q plot (Chapter 5). There are formal tests of normality too, such as the Shapiro-Wilk test, but they have a trap:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(first_sem$sleep_hours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  first_sem$sleep_hours\nW = 0.99291, p-value = 0.006536\n```\n\n\n:::\n:::\n\n\nThe test says sleep is *not* normal (p < 0.05). Yet in Chapter 5, the histogram and Q-Q plot of sleep looked almost perfectly normal. Both are right: with 600 students, the test is sensitive enough to detect tiny departures from normality that make no practical difference. In large samples, normality tests reject almost everything; in small samples, where normality matters most, they can miss real problems. Trust the graphs, and let the sample size guide you.\n\n## Categorical data: chi-square tests\n\nThe t-test compares averages of a numeric variable. For categorical variables, the **chi-square test** ($\\chi^2$) compares counts: how many cases fall into each category, against how many would be expected if the null hypothesis were true.\n\n### Goodness of fit\n\nThe **goodness-of-fit test** compares the counts of one categorical variable with expected proportions. Is Elaf's sample evenly split between women and men?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(students$gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFemale   Male \n   312    288 \n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(table(students$gender), p = c(0.5, 0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  table(students$gender)\nX-squared = 0.96, df = 1, p-value = 0.3272\n```\n\n\n:::\n:::\n\n\nWith 312 women and 288 men, the split is a little uneven, but the p-value is large: a difference this size is quite likely in a random sample from an evenly split population. There is no evidence against a 50/50 split. (Not every test has to be significant, and a non-significant result is still a result.)\n\n### Test of independence\n\nThe **test of independence** asks whether two categorical variables are related. Is having a job related to considering dropping out?\n\n\n::: {.cell}\n\n```{.r .cell-code}\njobs <- table(students$employment, students$considering_dropout)\njobs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                 No Yes\n  Full-time job  72  25\n  None          265  42\n  Part-time job 173  23\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(jobs, margin = 1) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                  No  Yes\n  Full-time job 0.74 0.26\n  None          0.86 0.14\n  Part-time job 0.88 0.12\n```\n\n\n:::\n:::\n\n\n`prop.table(..., margin = 1)` turns the counts into proportions within each row. About a quarter of students with full-time jobs have considered dropping out, compared with about one in eight of the others. Is the difference larger than chance?\n\n\n::: {.cell}\n\n```{.r .cell-code}\njob_test <- chisq.test(jobs)\njob_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  jobs\nX-squared = 10.888, df = 2, p-value = 0.004322\n```\n\n\n:::\n:::\n\n\nYes: the p-value is 0.004. Students with full-time jobs are more likely to consider dropping out. (This is an association, not proof that jobs cause dropout thoughts: students who work full-time may differ in other ways too, such as financial pressure.)\n\nThe chi-square test is reliable when the **expected** counts, the counts you would expect if the variables were unrelated, are at least 5 in every cell. The test stores them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(job_test$expected, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                   No  Yes\n  Full-time job  82.4 14.6\n  None          261.0 46.0\n  Part-time job 166.6 29.4\n```\n\n\n:::\n:::\n\n\nAll are well above 5. When some are not, use `fisher.test()` instead, which is exact for small counts.\n\n## When assumptions fail: non-parametric tests\n\nWhen data is clearly not normal and the sample is small, or when the data is ordinal (ranks, or answers on a short scale), **non-parametric tests** are the alternative. Instead of the values themselves, they compare the **ranks** of the values, so extreme values and skewness do not throw them off.\n\nThe **Mann-Whitney U test** (called the Wilcoxon rank-sum test in R) replaces the two-sample t-test. Caffeine is strongly skewed; do women and men differ in caffeine intake?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(first_sem$caffeine_mg, first_sem$gender, median, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemale   Male \n 152.5  170.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(caffeine_mg ~ gender, data = first_sem)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  caffeine_mg by gender\nW = 40551, p-value = 0.06319\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nThe medians differ a little, but the p-value is above 0.05: no clear evidence of a difference. Report medians, not means, alongside a non-parametric test.\n\nThe **Wilcoxon signed-rank test** replaces the paired t-test. Applied to the invited students' wellbeing in semesters 1 and 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(invited_wide$semester_2, invited_wide$semester_1, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  invited_wide$semester_2 and invited_wide$semester_1\nV = 33026, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nIt agrees with the paired t-test. When the parametric and non-parametric tests agree, you can report either with confidence; when they disagree, look again at the data, and trust the one whose assumptions fit.\n\n## Which test when?\n\n@tbl-choose-test and @fig-choose-test summarise the tests of this chapter and the next.\n\n| Question | Data | Test | In R |\n|---|---|---|---|\n| Is a mean equal to a value? | Numeric, one group | One-sample t-test | `t.test(x, mu = )` |\n| Do two groups differ? | Numeric, two independent groups | Two-sample t-test | `t.test(y ~ group)` |\n| Do the same people differ at two times? | Numeric, paired | Paired t-test | `t.test(x2, x1, paired = TRUE)` |\n| Do three or more groups differ? | Numeric, 3+ groups | ANOVA (Chapter 7) | `aov()` |\n| Do two groups differ (skewed or ordinal)? | Ranks, two groups | Mann-Whitney U | `wilcox.test(y ~ group)` |\n| Paired, skewed or ordinal? | Ranks, paired | Wilcoxon signed-rank | `wilcox.test(x2, x1, paired = TRUE)` |\n| Do counts match expected proportions? | One categorical variable | Chi-square goodness of fit | `chisq.test(table, p = )` |\n| Are two categorical variables related? | Two categorical variables | Chi-square test of independence | `chisq.test(table)` |\n\n: Choosing a test {#tbl-choose-test}\n\n```{mermaid}\n%%| label: fig-choose-test\n%%| fig-cap: \"Choosing a test for comparing groups.\"\nflowchart TD\n  A[What is the outcome?] -->|Numeric| B{How many groups?}\n  A -->|Categorical| K[Chi-square test]\n  B -->|One, against a value| C[One-sample t-test]\n  B -->|Two| D{Same people twice?}\n  B -->|Three or more| F[ANOVA, Chapter 7]\n  D -->|No, different people| G[Two-sample t-test]\n  D -->|Yes| H[Paired t-test]\n  G -.->|Very skewed, small sample, or ordinal| I[Mann-Whitney U test]\n  H -.->|Very skewed, small sample, or ordinal| J[Wilcoxon signed-rank test]\n```\n\n## Reporting results in a thesis\n\nReport each test with the statistic, its degrees of freedom (df, printed by R), the p-value, and, most importantly, the size of the effect with a confidence interval. Give exact p-values to two or three decimal places, and write \"*p* < .001\" for very small ones. For example:\n\n::: {.callout-tip}\n## Example write-ups\n\n**One-sample t-test.** Students slept less than the recommended 7 hours (*M* = 6.48, 95% CI [6.40, 6.57]), *t*(593) = -12.18, *p* < .001.\n\n**Two-sample t-test.** Students invited to the wellbeing workshop reported higher wellbeing at the end of semester 2 (*M* = 65.5) than those not invited (*M* = 60.2), a difference of 5.2 points, 95% CI [3.4, 7.1], *t*(598) = 5.47, *p* < .001, *d* = 0.45.\n\n**Chi-square test.** Considering dropout was related to employment, $\\chi^2$(2) = 10.89, *p* = .004: 26% of students with full-time jobs had considered dropping out, compared with 14% of those without a job.\n:::\n\nAll the numbers in these examples are filled in by the code, so they cannot drift out of step with the analysis.\n\n::: {.callout-note icon=\"false\"}\n## In your field: health research\n\nThe t-test was invented to analyse small medical experiments [@student1908]. R still includes one of the original datasets, `sleep`: the extra hours of sleep that 10 patients gained with each of two sleeping drugs. Because the *same* patients took both drugs, this calls for a **paired** t-test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug1 <- sleep$extra[sleep$group == 1]\ndrug2 <- sleep$extra[sleep$group == 2]\nt.test(drug2, drug1, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  drug2 and drug1\nt = 4.0621, df = 9, p-value = 0.002833\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.7001142 2.4598858\nsample estimates:\nmean difference \n           1.58 \n```\n\n\n:::\n:::\n\n\nPatients slept on average 1.6 hours longer with the second drug. With only 10 patients, the confidence interval is wide, from about 0.7 to 2.5 hours: a clear effect, but an imprecise estimate of its size.\n:::\n\n## Chapter review\n\n### Summary\n\n- A statistic estimates a population parameter. Its sampling distribution shows how it would vary across samples; its spread is the standard error, $s / \\sqrt{n}$.\n- The central limit theorem: averages of reasonably large samples are approximately normal, whatever the shape of the data.\n- A 95% confidence interval gives the plausible values of a parameter. The bootstrap gives confidence intervals for almost any statistic.\n- A hypothesis test asks how surprising the data would be if the null hypothesis were true. The p-value is that probability; below 0.05 is conventionally called significant. Significance is not importance: always report the size of the effect.\n- Type I errors are false alarms (about 5% of tests of true null hypotheses); Type II errors are missed effects.\n- t-tests compare a mean with a value, two independent groups, or paired measurements. Random assignment allows causal conclusions.\n- Check assumptions with graphs; in large samples, formal normality tests reject trivial departures.\n- Chi-square tests compare counts of categorical variables; Mann-Whitney and Wilcoxon tests are non-parametric alternatives to t-tests.\n\n### Key terms\n\nPopulation, sample, parameter, statistic, sampling distribution, central limit theorem, standard error, confidence interval, bootstrap, null hypothesis, alternative hypothesis, p-value, significance level, statistically significant, Type I error, Type II error, one-tailed test, two-tailed test, one-sample t-test, two-sample t-test, Welch test, paired t-test, effect size, Cohen's *d*, independence, chi-square test, expected count, non-parametric test, Mann-Whitney U test, Wilcoxon signed-rank test.\n\n## Exercises\n\nThe [playground](../playground/chapter06.html) has these and more, with hints and solutions.\n\n1. Draw 1,000 samples of 10 students' first-semester `study_hours` and plot the sample averages. Then try samples of 50. How do the two sampling distributions differ?\n2. Calculate a 95% confidence interval for the average first-semester GPA. What does it tell you?\n3. Is the average first-semester wellbeing different from 60? State the hypotheses, run the test, and write a one-sentence conclusion.\n4. Do full-time and part-time students differ in first-semester GPA? Run a two-sample t-test and calculate Cohen's *d*.\n5. Is living away from family (`lives_away`) related to considering dropout? Run a chi-square test and check the expected counts.\n\n## Further reading\n\n- *Introduction to Modern Statistics* [@cetinkaya2024ims], a free online textbook, explains sampling distributions, bootstrapping, and hypothesis tests with many more examples, using simulation throughout.\n- *Statistical Power Analysis for the Behavioral Sciences* [@cohen1988] on effect sizes.\n",
    "supporting": [
      "06-hypothesis-testing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}