{
  "hash": "fd526322190c15212904f7925546aadb",
  "result": {
    "engine": "knitr",
    "markdown": "# Mixed-Effects Models {#sec-ch09}\n\n\n\nElaf followed her students for two years, recording their wellbeing and grades every semester. That design is her study's great strength: she can see how students *change*, and whether the workshop's effect lasted. But it breaks a rule that every test so far has relied on. The four measurements of one student are not independent: a student who is doing well in semester 1 is likely to be doing well in semester 2. And students share supervisors, so students of the same supervisor may be more alike than students of different supervisors.\n\n**Mixed-effects models**, also called **multilevel models**, are designed for exactly this kind of data. This chapter answers Elaf's eighth research question: how do wellbeing and GPA change over the two years, and how much do supervisors matter (RQ8)? And it returns to the workshop to ask whether its effect faded.\n\n::: {.callout-tip appearance=\"simple\"}\n## By the end of this chapter you will be able to\n\n- Recognise repeated-measures and nested data, and explain why ordinary regression is wrong for them.\n- Fit mixed-effects models with random intercepts and random slopes using lme4.\n- Interpret fixed effects, random effects, and the intraclass correlation.\n- Test whether an effect changes over time, and compare models.\n- Model a count outcome with a generalised linear mixed model.\n- Report a mixed-effects model in a thesis.\n:::\n\n## Data with a structure\n\nTwo kinds of structure are common in research:\n\n- **Repeated measures**: the same people are measured several times, as Elaf's students are over four semesters. Measurements are grouped within people.\n- **Nested data**: people belong to groups, such as students within supervisors, pupils within classes within schools, or patients within hospitals.\n\nIn both cases, observations within a group are more alike than observations from different groups. Ordinary regression assumes every observation is independent, so it gets the uncertainty wrong. Sometimes it is far too confident; sometimes it misses real effects. Mixed-effects models include the structure in the model, and get it right.\n\n## A first example: sleep deprivation\n\nBefore Elaf's data, a small real study. R's `sleepstudy` data, from the **lme4** package, records the reaction times of 18 people over 10 days of sleep restriction, one measurement per person per day [@belenky2003]:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)\nlibrary(dplyr)\nlibrary(ggplot2)\n\nhead(sleepstudy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Reaction Days Subject\n1 249.5600    0     308\n2 258.7047    1     308\n3 250.8006    2     308\n4 321.4398    3     308\n5 356.8519    4     308\n6 414.6901    5     308\n```\n\n\n:::\n:::\n\n\n@fig-sleepstudy shows each person's reaction times, with their own trend line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sleepstudy, aes(x = Days, y = Reaction)) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 0.7) +\n  facet_wrap(~ Subject, ncol = 6) +\n  labs(x = \"Days of sleep restriction\", y = \"Reaction time (ms)\") +\n  theme_minimal(base_size = 10)\n```\n\n::: {.cell-output-display}\n![Reaction times over 10 days of sleep restriction, one panel per person, with each person's own trend line.](09-mixed-models_files/figure-html/fig-sleepstudy-1.png){#fig-sleepstudy fig-alt='Eighteen small scatter plots, one per person. In almost every panel, reaction time rises over the days, but people start at different levels and rise at different rates.' width=768}\n:::\n:::\n\n\nTwo things are clear. Almost everyone gets slower as the days go by. And people differ: some start faster than others (different **intercepts**), and some slow down more than others (different **slopes**).\n\n### Random intercepts\n\nAn ordinary regression would fit one line through all 180 points, as if they came from 180 different people. A **random intercept model** fits one average line, but lets each person have their own starting level. In the formula, `(1 | Subject)` means \"a separate intercept for each subject\". `lmer()` fits it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_ri <- lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)\nsummary(sleep_ri)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: Reaction ~ Days + (1 | Subject)\n   Data: sleepstudy\n\nREML criterion at convergence: 1786.5\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.2257 -0.5529  0.0109  0.5188  4.2506 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 1378.2   37.12   \n Residual              960.5   30.99   \nNumber of obs: 180, groups:  Subject, 18\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept) 251.4051     9.7467   25.79\nDays         10.4673     0.8042   13.02\n\nCorrelation of Fixed Effects:\n     (Intr)\nDays -0.371\n```\n\n\n:::\n:::\n\n\nThe output has two important parts:\n\n- **Fixed effects**: the average line, as in ordinary regression. On day 0, the average reaction time is about 251 ms, and each day of sleep restriction adds about 10.5 ms.\n- **Random effects**: how much people vary around the average line. The standard deviation of the intercepts, about 37 ms, says that people's starting levels differ by about 37 ms from the average; the residual standard deviation, about 31 ms, is the day-to-day variation within a person.\n\n### The intraclass correlation\n\nHow much of the total variation lies between people rather than within them? The **intraclass correlation** (ICC) answers:\n\n$$\n\\text{ICC} = \\frac{\\text{variance between groups}}{\\text{variance between groups} + \\text{variance within groups}}\n$$\n\n`VarCorr()` extracts the variances:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvc <- as.data.frame(VarCorr(sleep_ri))\nvc$vcov[1] / sum(vc$vcov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5893089\n```\n\n\n:::\n:::\n\n\nAbout 59% of the variation in reaction times is due to stable differences between people. An ICC of 0 would mean the grouping does not matter; the higher it is, the more wrong an ordinary regression would be.\n\n### Random slopes\n\nThe random intercept model still assumes that everyone slows down at the same rate, which @fig-sleepstudy shows is not true. A **random slope model** lets each person have their own slope as well. `(Days | Subject)` means \"a separate intercept *and* slope of `Days` for each subject\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_rs <- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy)\nsummary(sleep_rs)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate Std. Error   t value\n(Intercept) 251.40510   6.824597 36.838090\nDays         10.46729   1.545790  6.771481\n```\n\n\n:::\n\n```{.r .cell-code}\nVarCorr(sleep_rs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups   Name        Std.Dev. Corr \n Subject  (Intercept) 24.7407       \n          Days         5.9221  0.066\n Residual             25.5918       \n```\n\n\n:::\n:::\n\n\nThe average effect of a day of sleep restriction is the same, about 10.5 ms, but its standard error is larger. People's slopes vary with a standard deviation of about 6 ms per day: some slow down by only 5 ms a day, others by 15 or more. Ignoring that variation made the random intercept model too confident about the average.\n\nIs the random slope worth adding? `anova()` compares the two models with a **likelihood ratio test**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(sleep_ri, sleep_rs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: sleepstudy\nModels:\nsleep_ri: Reaction ~ Days + (1 | Subject)\nsleep_rs: Reaction ~ Days + (Days | Subject)\n         npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nsleep_ri    4 1802.1 1814.8 -897.04    1794.1                         \nsleep_rs    6 1763.9 1783.1 -875.97    1751.9 42.139  2  7.072e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe p-value is tiny: the random slopes improve the model clearly. The **AIC** column agrees. AIC balances fit against complexity, and lower is better.\n\n## Elaf's data: change over two years\n\nNow Elaf's study. Each student has up to four semester records, joined with their background information. `time` counts semesters from the first, so that time 0 is semester 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npanel <- semesters |>\n  left_join(students, join_by(student_id)) |>\n  mutate(time = semester - 1)\nnrow(panel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2326\n```\n\n\n:::\n:::\n\n\n@fig-spaghetti shows the wellbeing of 30 randomly chosen students across the four semesters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(9)\nsome_students <- sample(unique(panel$student_id), 30)\n\npanel |>\n  filter(student_id %in% some_students) |>\n  ggplot(aes(x = semester, y = wellbeing, group = student_id)) +\n  geom_line(alpha = 0.6) +\n  labs(x = \"Semester\", y = \"Wellbeing (0 to 100)\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Wellbeing over four semesters for 30 randomly chosen students.](09-mixed-models_files/figure-html/fig-spaghetti-1.png){#fig-spaghetti fig-alt='Thirty thin lines across four semesters. The lines are spread widely, from about 30 to 90, and each stays at roughly its own level, with small ups and downs.' width=624}\n:::\n:::\n\n\nStudents differ enormously in their overall level, much more than any student changes from one semester to the next. How much, exactly? A model with no predictors, only a random intercept for each student, gives the ICC:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_null <- lmer(wellbeing ~ 1 + (1 | student_id), data = panel)\nvc_null <- as.data.frame(VarCorr(wb_null))\nvc_null$vcov[1] / sum(vc_null$vcov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7809117\n```\n\n\n:::\n:::\n\n\nAbout 78% of all the variation in wellbeing is between students. Treating the 2326 records as independent would be seriously wrong.\n\n### Why ordinary regression misleads\n\nDoes wellbeing decline over time? First, the *wrong* way, with an ordinary regression that ignores the structure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(wellbeing ~ time, data = panel))$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error    t value   Pr(>|t|)\n(Intercept) 61.6319636  0.4124650 149.423511 0.00000000\ntime        -0.3794867  0.2235408  -1.697618 0.08971384\n```\n\n\n:::\n:::\n\n\nThe slope is slightly negative, but not significant. Now the mixed model, with a random intercept and slope for each student:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_growth <- lmer(wellbeing ~ time + (time | student_id), data = panel)\nsummary(wb_growth)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error    t value\n(Intercept) 61.6455545  0.4764479 129.385717\ntime        -0.4342392  0.1107653  -3.920355\n```\n\n\n:::\n:::\n\n\nThe average slope is similar, about -0.43 points per semester, but now its standard error is half as large, and the decline is clearly significant (a *t* value of about -3.9). Why? The ordinary regression lumps the large, stable differences *between* students into its error term, which drowns the small change *within* each student. The mixed model separates the two, and sees the change clearly.\n\nIn the `sleepstudy` example, ignoring the structure made the results look *more* certain than they were; here it makes them look *less* certain. Either way, ordinary regression gets the uncertainty wrong for grouped data, and you cannot know in advance in which direction.\n\n### Getting confidence intervals and p-values\n\nThe lme4 package deliberately prints no p-values for fixed effects, because calculating them exactly for mixed models is not straightforward. There are three common solutions:\n\n- **Confidence intervals**, which are often more informative than p-values anyway. `confint()` calculates them; `method = \"Wald\"` is quick:\n\n\n  ::: {.cell}\n  \n  ```{.r .cell-code}\n  confint(wb_growth, parm = \"beta_\", method = \"Wald\")\n  ```\n  \n  ::: {.cell-output .cell-output-stdout}\n  \n  ```\n                   2.5 %     97.5 %\n  (Intercept) 60.7117337 62.5793752\n  time        -0.6513351 -0.2171432\n  ```\n  \n  \n  :::\n  :::\n\n\n  `parm = \"beta_\"` asks for the fixed effects only. The interval for `time` lies entirely below zero: wellbeing declines.\n\n- **Likelihood ratio tests**, comparing models with and without a term, with `anova()`, as for the random slopes above.\n\n- The **lmerTest** package, which adds p-values to the `summary()` output. Most published research uses it. Once it is loaded, `lmer()` models fitted afterwards include a p-value for each fixed effect:\n\n\n  ::: {.cell}\n  \n  ```{.r .cell-code}\n  library(lmerTest)\n  wb_growth_p <- lmer(wellbeing ~ time + (time | student_id), data = panel)\n  summary(wb_growth_p)$coefficients\n  ```\n  \n  ::: {.cell-output .cell-output-stdout}\n  \n  ```\n                Estimate Std. Error       df    t value     Pr(>|t|)\n  (Intercept) 61.6455545  0.4764479 598.9342 129.385717 0.000000e+00\n  time        -0.4342392  0.1107653 571.4997  -3.920355 9.914491e-05\n  ```\n  \n  \n  :::\n  :::\n\n\n  The new columns are the degrees of freedom (estimated by Satterthwaite's method) and the p-value, `Pr(>|t|)`. The decline over time is clearly significant, in agreement with the confidence interval.\n\n### Did the workshop's effect last?\n\nChapter 6 showed that the workshop raised wellbeing in semester 2. Did the effect last? A mixed model can compare the two groups in every semester at once, using every record, including the first year of the students who later left. Treating `semester` as a factor lets each semester have its own average, and the interaction with `workshop` lets the gap between the groups differ from semester to semester:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_workshop <- lmer(wellbeing ~ factor(semester) * workshop + (time | student_id),\n                    data = panel)\nround(summary(wb_workshop)$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                      Estimate Std. Error      df t value\n(Intercept)                              60.65       0.69  667.20   87.89\nfactor(semester)2                         4.82       0.42 1452.39   11.38\nfactor(semester)3                         2.49       0.45 1595.59    5.51\nfactor(semester)4                         0.21       0.48  667.71    0.43\nworkshopNot invited                      -0.38       0.98  667.20   -0.39\nfactor(semester)2:workshopNot invited    -4.87       0.60 1452.39   -8.13\nfactor(semester)3:workshopNot invited    -3.75       0.64 1597.01   -5.85\nfactor(semester)4:workshopNot invited    -2.26       0.68  668.47   -3.30\n                                      Pr(>|t|)\n(Intercept)                               0.00\nfactor(semester)2                         0.00\nfactor(semester)3                         0.00\nfactor(semester)4                         0.67\nworkshopNot invited                       0.70\nfactor(semester)2:workshopNot invited     0.00\nfactor(semester)3:workshopNot invited     0.00\nfactor(semester)4:workshopNot invited     0.00\n```\n\n\n:::\n:::\n\n\nThe coefficients are easier to understand as predicted averages. `predict()` with `re.form = NA` gives the predictions for the average student, ignoring the random effects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted <- expand.grid(semester = 1:4, workshop = c(\"Invited\", \"Not invited\")) |>\n  mutate(time = semester - 1)\npredicted$wellbeing <- predict(wb_workshop, newdata = predicted, re.form = NA)\n\nggplot(predicted, aes(x = semester, y = wellbeing, colour = workshop)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2.5) +\n  scale_colour_viridis_d(end = 0.8) +\n  labs(x = \"Semester\", y = \"Predicted wellbeing\", colour = \"Workshop\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Predicted wellbeing in each semester by workshop group, from the mixed-effects model.](09-mixed-models_files/figure-html/fig-workshop-fade-1.png){#fig-workshop-fade fig-alt='Two lines over semesters 1 to 4. They start together; the invited group rises about 5 points above the other in semester 2, and the gap narrows in semesters 3 and 4.' width=624}\n:::\n:::\n\n\n\n\nThe gap between the groups is 0.4 points in semester 1, before the workshop, 5.2 in semester 2, 4.1 in semester 3, and 2.6 in semester 4. The workshop's effect is real, but it fades over the following year. For Elaf's recommendations, that matters: perhaps a short follow-up session each year would keep the benefit going.\n\nThe interaction coefficients test whether the gap in each semester differs from the gap in semester 1, and all three are clearly different from zero.\n\n### What about GPA?\n\nDoes GPA change over the two years, too?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_growth <- lmer(gpa ~ time + (time | student_id), data = panel)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n:::\n\n\nR warns that the fit is **singular**. This message is common, and worth understanding. It means the model is more complex than the data supports: here, the students' GPA slopes hardly vary at all, so the model cannot estimate their spread. The solution is to simplify, keeping only the random intercept:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_growth <- lmer(gpa ~ time + (1 | student_id), data = panel)\nsummary(gpa_growth)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate  Std. Error        df     t value  Pr(>|t|)\n(Intercept)  3.0921628374 0.013015341  806.5702 237.5783101 0.0000000\ntime        -0.0004749256 0.003392086 1738.6474  -0.1400099 0.8886684\n```\n\n\n:::\n:::\n\n\nThe slope of `time` is almost exactly zero: grades stay stable over the two years, even though wellbeing falls. A non-change is a finding too, and here an interesting one.\n\n## Students within supervisors\n\nElaf's students are nested within supervisors. How much does the supervisor matter? A model can include random intercepts for both levels at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwb_levels <- lmer(wellbeing ~ time + (1 | supervisor_id) + (1 | student_id), data = panel)\nVarCorr(wb_levels)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Groups        Name        Std.Dev.\n student_id    (Intercept) 9.7748  \n supervisor_id (Intercept) 4.4098  \n Residual                  5.6189  \n```\n\n\n:::\n:::\n\n\nBecause every student ID is unique, R knows that students are nested within supervisors. Dividing each variance by the total shows where the variation lies:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvc_levels <- as.data.frame(VarCorr(wb_levels))\ndata.frame(level = vc_levels$grp, share = round(vc_levels$vcov / sum(vc_levels$vcov), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          level share\n1    student_id  0.65\n2 supervisor_id  0.13\n3      Residual  0.22\n```\n\n\n:::\n:::\n\n\n\n\nAbout 13% of all the variation in wellbeing lies between supervisors: students of the same supervisor are noticeably more alike. Most of the variation, 65%, lies between students within the same supervisor, and the remaining 22% is change within students from semester to semester. For the university, the supervisor share is a practical finding: who supervises a student makes a measurable difference to their wellbeing.\n\n## Counts and yes-or-no outcomes\n\nLike ordinary regression, mixed models extend to other kinds of outcome. `glmer()` fits a **generalised linear mixed model**: `family = binomial` for yes-or-no outcomes, as in Chapter 7's logistic regression, and `family = poisson` for **counts**, such as the number of meetings a student had with their supervisor each semester.\n\nDo students who feel more supported meet their supervisor more often? Support is calculated from the questionnaire, as before:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupport_scores <- questionnaire |>\n  mutate(support = rowMeans(pick(support_1:support_6), na.rm = TRUE)) |>\n  select(student_id, support)\n\nmeetings_model <- glmer(\n  supervisor_meetings ~ support + programme + (1 | supervisor_id) + (1 | student_id),\n  data = panel |> left_join(support_scores, join_by(student_id)),\n  family = poisson\n)\nsummary(meetings_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Estimate Std. Error    z value     Pr(>|z|)\n(Intercept)  0.06224346 0.07134373  0.8724446 3.829659e-01\nsupport      0.39258255 0.01975713 19.8704237 7.338090e-88\nprogrammePhD 0.17676057 0.02881998  6.1332638 8.609423e-10\n```\n\n\n:::\n:::\n\n\nPoisson coefficients are on a log scale. `exp()` turns them into **rate ratios**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(fixef(meetings_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)      support programmePhD \n    1.064221     1.480800     1.193345 \n```\n\n\n:::\n:::\n\n\nEach extra point of support goes with about 48% more meetings per semester, and PhD students have about 19% more meetings than Master's students, holding support constant. (As always with observational data, the direction is not certain: more meetings may also make students feel more supported.)\n\n::: {.callout-note}\n## Missing data and mixed models\n\nChapter 5 found that the students who left after the first year were not a random group. Mixed models handle this better than most methods: they use every record each student provided, including the first year of those who left, instead of dropping those students entirely. The results remain trustworthy as long as leaving depends on things the model can see, such as the students' earlier wellbeing, which is the \"missing at random\" situation of Chapter 5.\n:::\n\n## Reporting a mixed-effects model\n\nReport both parts of the model: the fixed effects, with confidence intervals, and the random effects, as standard deviations or variance shares. Say how many observations and groups the model used, and which random effects it included.\n\n\n\n::: {.callout-tip}\n## Writing it up\n\nA linear mixed-effects model with random intercepts and slopes for students (2326 observations of 600 students) showed that wellbeing declined slightly over the four semesters, by 0.43 points per semester (95% CI [0.22, 0.65]). Students differed considerably in their overall wellbeing (*SD* of intercepts = 10.7); 78% of the variation in wellbeing was between students.\n:::\n\n::: {.callout-note icon=\"false\"}\n## In your field: agriculture\n\nR's `ChickWeight` data records the weight of 50 chicks, measured every few days from birth to 21 days old, on one of four diets. It has exactly the structure of Elaf's data: repeated measurements of the same individuals, in groups. A random-slope model compares how fast chicks grow on each diet:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchick_model <- lmer(weight ~ Time * Diet + (Time | Chick), data = ChickWeight)\nround(summary(chick_model)$coefficients, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error    df t value Pr(>|t|)\n(Intercept)    33.66       2.92 47.54   11.53     0.00\nTime            6.28       0.76 46.99    8.24     0.00\nDiet2          -5.03       5.01 46.15   -1.00     0.32\nDiet3         -15.41       5.01 46.15   -3.08     0.00\nDiet4          -1.75       5.02 46.40   -0.35     0.73\nTime:Diet2      2.33       1.30 45.76    1.79     0.08\nTime:Diet3      5.15       1.30 45.76    3.95     0.00\nTime:Diet4      3.25       1.31 45.86    2.49     0.02\n```\n\n\n:::\n:::\n\n\nChicks on diet 1 gain about 6 grams a day. The interaction terms show how much faster chicks grow on the other diets: diet 3 adds about 5 grams a day, nearly doubling the rate of growth.\n:::\n\n## Chapter review\n\n### Summary\n\n- Repeated measures and nested data break the independence assumption of ordinary regression, which then gets the uncertainty wrong, in either direction.\n- Mixed-effects models have fixed effects (the average relationships) and random effects (how groups vary around them). `(1 | group)` gives each group its own intercept; `(x | group)` also its own slope of `x`.\n- The intraclass correlation is the share of variation between groups.\n- lme4 prints no p-values: use confidence intervals, likelihood ratio tests with `anova()`, or the lmerTest package.\n- Interactions with time show whether an effect grows or fades. `predict(..., re.form = NA)` gives predictions for the average case.\n- A singular fit means the model is too complex for the data: simplify the random effects.\n- `glmer()` fits mixed models for yes-or-no outcomes (`binomial`) and counts (`poisson`; `exp()` of the coefficients gives rate ratios).\n- Mixed models use all available records, which helps when participants drop out.\n\n### Key terms\n\nRepeated measures, nested data, mixed-effects model, multilevel model, fixed effect, random effect, random intercept, random slope, intraclass correlation, likelihood ratio test, AIC, singular fit, generalised linear mixed model, Poisson model, count outcome, rate ratio.\n\n## Exercises\n\nThe [playground](../playground/chapter09.html) has these and more, with hints and solutions.\n\n1. Fit a random intercept model for `sleep_hours` over time (`sleep_hours ~ time + (1 | student_id)`). What is the ICC? Does sleep change over the semesters?\n2. Add a random slope of `time` to the model in Exercise 1, and compare the two models with `anova()`. Is the random slope worth keeping?\n3. Fit `wellbeing ~ time * study_mode + (time | student_id)`. Do part-time students' wellbeing change at a different rate?\n4. How much of the variation in `study_hours` lies between supervisors? Fit a model with random intercepts for supervisors and students, and calculate the shares.\n5. In your own words, explain to a fellow student why an ordinary regression of all Elaf's semester records would be wrong.\n\n## Further reading\n\n- *Data Analysis Using Regression and Multilevel/Hierarchical Models* [@gelman2007] is a classic, readable introduction to multilevel models.\n- \"Fitting Linear Mixed-Effects Models Using lme4\" [@bates2015] describes the lme4 package and its formula syntax in detail.\n",
    "supporting": [
      "09-mixed-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}