{
  "hash": "c3b2a0891bb5786e4ae555ae5be0d522",
  "result": {
    "engine": "knitr",
    "markdown": "# Descriptive Statistics and Exploratory Data Analysis {#sec-ch05}\n\n\n\nElaf's data is clean, and she has looked at it in graphs. She is eager to start testing her hypotheses. Her supervisor stops her: \"Before you test anything, can you describe your sample? How long do the students sleep, typically? How much do they differ? Is anything unusual, or missing?\"\n\nThese are the questions of **descriptive statistics**: numbers that summarise what the data looks like. They are the first results in almost every thesis chapter, and they decide which tests are appropriate later. This chapter answers Elaf's first research question, *what does graduate student life look like?* (RQ1), with numbers, and checks the data for the problems that could mislead every later analysis.\n\n::: {.callout-tip appearance=\"simple\"}\n## By the end of this chapter you will be able to\n\n- Explain the difference between exploratory, inferential, and predictive analysis.\n- Summarise the centre and spread of a variable, and choose between the mean and the median.\n- Describe the shape of a distribution, and check it against the normal distribution.\n- Find unusual values, and decide what to do with them.\n- Describe how much data is missing, and why it matters.\n- Measure and interpret correlations, and explain why correlation is not causation.\n- Present a description of your sample in a thesis.\n:::\n\n## Three kinds of analysis\n\nData analysis in research serves three different purposes, and it helps to know which one you are doing:\n\n- **Exploratory analysis** gets to know the data: summaries, graphs, unusual values, missing values. It is open-ended. It does not prove anything, but it often suggests questions worth testing. This chapter is exploratory.\n- **Inferential analysis** uses a sample to draw conclusions about a wider population, and asks whether a result could be due to chance. Does the workshop improve wellbeing for graduate students in general, not just for these 600? Chapters 6 to 9 are inferential.\n- **Predictive analysis** builds models that make accurate predictions for new cases. Which students are likely to consider dropping out next year? Part 3 is predictive.\n\nThe three fit into one workflow, shown in @fig-workflow. Exploration comes first, and you return to it whenever a later result surprises you.\n\n```{mermaid}\n%%| label: fig-workflow\n%%| fig-cap: \"The research data analysis workflow. Exploration comes before testing and prediction, and you return to it when results surprise you.\"\nflowchart LR\n  A[Research question] --> B[Import]\n  B --> C[Clean]\n  C --> D[Explore:<br/>describe and visualise]\n  D --> E[Test or predict]\n  E --> F[Report]\n  E -. surprising result .-> D\n```\n\n## Where is the centre?\n\nThe first question about any variable is: what is a typical value? Three measures answer it.\n\nThe **mean** is the average: add up the values and divide by how many there are. In symbols, for values $x_1, x_2, \\ldots, x_n$:\n\n$$\n\\bar{x} = \\frac{1}{n} \\sum_{i=1}^{n} x_i\n$$\n\nThe **median** is the middle value when the values are sorted: half the values are below it and half above. The **mode** is the most common value, which is mainly useful for categories.\n\nThe mean and median can tell very different stories. Here is the daily caffeine intake, in milligrams, of five students:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaffeine <- c(0, 120, 150, 180, 900)\nmean(caffeine)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 270\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(caffeine)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150\n```\n\n\n:::\n:::\n\n\nOne student who takes 900 mg a day pulls the mean up to 270 mg, higher than four of the five students. The median, 150 mg, stays with the typical student. The mean is sensitive to extreme values; the median is not.\n\nNow Elaf's data. The code below keeps each student's first-semester record, together with their background information:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\n\nfirst_sem <- semesters |>\n  filter(semester == 1) |>\n  left_join(students, join_by(student_id))\n\nfirst_sem |>\n  summarise(\n    mean_sleep      = mean(sleep_hours, na.rm = TRUE),\n    median_sleep    = median(sleep_hours, na.rm = TRUE),\n    mean_caffeine   = mean(caffeine_mg, na.rm = TRUE),\n    median_caffeine = median(caffeine_mg, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_sleep median_sleep mean_caffeine median_caffeine\n1   6.483502          6.5      189.4054             160\n```\n\n\n:::\n:::\n\n\nFor sleep, the mean and median are almost identical. For caffeine, the mean is well above the median, just as in the five-student example: a minority of heavy caffeine users pull the mean up. @fig-caffeine-centre shows why.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(first_sem, aes(x = caffeine_mg)) +\n  geom_histogram(binwidth = 50, fill = \"grey70\", colour = \"white\") +\n  geom_vline(xintercept = mean(first_sem$caffeine_mg, na.rm = TRUE), linewidth = 1) +\n  geom_vline(xintercept = median(first_sem$caffeine_mg, na.rm = TRUE),\n             linewidth = 1, linetype = \"dashed\") +\n  labs(x = \"Caffeine per day (mg)\", y = \"Number of students\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Daily caffeine intake in the first semester, with the mean (solid line) and median (dashed line).](05-descriptive-statistics_files/figure-html/fig-caffeine-centre-1.png){#fig-caffeine-centre fig-alt='Histogram of caffeine intake with a long tail to the right, reaching 900 mg; the mean line sits to the right of the median line.' width=624}\n:::\n:::\n\n\nFor categories, the mode is simply the most common category, which `count()` shows at the top when sorted:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudents |> count(faculty, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           faculty   n\n1  Health Sciences 154\n2        Education 148\n3  Social Sciences 116\n4       Humanities  95\n5 Natural Sciences  87\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Which to report in your thesis\n\nUse the **mean** for variables that are roughly symmetrical, without extreme values. Use the **median** for skewed variables or when there are extreme values, such as caffeine or income. Use the **mode**, or the percentage in each category, for categorical variables.\n:::\n\n## How spread out are the values?\n\nTwo groups can have the same average and still be very different. Compare the sleep of two small groups of students:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_a <- c(6.0, 6.5, 6.5, 7.0, 6.5)\ngroup_b <- c(4.0, 8.5, 5.0, 9.0, 6.0)\nmean(group_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.5\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(group_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.5\n```\n\n\n:::\n:::\n\n\nBoth average 6.5 hours, but group A sleeps about the same every night, while group B ranges from 4 to 9 hours. Measures of **spread** capture this difference.\n\nThe **range** is the difference between the largest and smallest values. It is simple, but it depends only on the two most extreme values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(group_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4 9\n```\n\n\n:::\n:::\n\n\nThe **standard deviation** (SD) measures how far values typically lie from the mean. It starts from each value's **deviation** from the mean, $x_i - \\bar{x}$. The deviations always add up to zero, so they are squared before averaging; the average squared deviation is the **variance**, and its square root is the standard deviation:\n\n$$\ns = \\sqrt{\\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\bar{x})^2}\n$$\n\n(Dividing by $n - 1$ rather than $n$ gives a slightly better estimate when working with a sample.) The square root brings the result back to the original units, so the standard deviation of sleep is measured in hours:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(group_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3535534\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(group_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.179449\n```\n\n\n:::\n:::\n\n\nThe **interquartile range** (IQR) is the spread of the middle half of the values. The **quartiles** split the sorted values into four equal parts: a quarter of the values lie below the first quartile ($Q_1$), half below the median, and three quarters below the third quartile ($Q_3$). The IQR is $Q_3 - Q_1$. Like the median, it ignores the extremes. A box plot's box is exactly the IQR.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(first_sem$caffeine_mg, c(0.25, 0.5, 0.75), na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n25% 50% 75% \n105 160 240 \n```\n\n\n:::\n\n```{.r .cell-code}\nIQR(first_sem$caffeine_mg, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 135\n```\n\n\n:::\n:::\n\n\nThe same `summarise()` calculates spread for several variables at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_sem |>\n  summarise(\n    sd_sleep   = sd(sleep_hours, na.rm = TRUE),\n    sd_gpa     = sd(gpa, na.rm = TRUE),\n    iqr_caffeine = IQR(caffeine_mg, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sd_sleep   sd_gpa iqr_caffeine\n1 1.033795 0.329459          135\n```\n\n\n:::\n:::\n\n\n\n\nThe standard deviation of sleep is about 1 hours: a typical student sleeps within about an hour of the average of 6.5 hours. Pair the mean with the SD, and the median with the IQR.\n\n## The shape of a distribution\n\nThe centre and spread do not describe everything. The **shape** of a distribution matters too, because it decides which summaries and which tests are appropriate.\n\n- A distribution is **symmetrical** if its two sides mirror each other. Then the mean and median are about equal.\n- It is **skewed to the right** (positively skewed) if it has a long tail of high values, as caffeine does. Then the mean is above the median.\n- It is **skewed to the left** (negatively skewed) if it has a long tail of low values. Then the mean is below the median.\n- It is **unimodal** if it has one peak, and **bimodal** if it has two, which often means two different groups are mixed together.\n\n@fig-shapes compares the shape of sleep and caffeine in Elaf's data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\n\nfirst_sem |>\n  select(sleep_hours, caffeine_mg) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"value\") |>\n  ggplot(aes(x = value)) +\n  geom_density(fill = \"grey80\") +\n  facet_wrap(~ variable, scales = \"free\") +\n  labs(x = NULL, y = \"Density\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Sleep is roughly symmetrical; caffeine is skewed to the right.](05-descriptive-statistics_files/figure-html/fig-shapes-1.png){#fig-shapes fig-alt='Two density curves side by side. Sleep hours form a symmetrical bell shape; caffeine rises steeply near zero and has a long tail to the right.' width=672}\n:::\n:::\n\n\n`scales = \"free\"` lets each panel have its own axes, since hours and milligrams are on very different scales.\n\nThe **skewness** statistic puts a number on the asymmetry: 0 for perfect symmetry, positive for a tail to the right, negative for a tail to the left. As a rough guide, values between −1 and +1 are mild. The **psych** package calculates it (install it once with `install.packages(\"psych\")`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(psych)\nskew(first_sem$sleep_hours, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.09604954\n```\n\n\n:::\n\n```{.r .cell-code}\nskew(first_sem$caffeine_mg, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.739451\n```\n\n\n:::\n\n```{.r .cell-code}\nskew(students$age, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.340088\n```\n\n\n:::\n:::\n\n\nSleep is almost perfectly symmetrical, while caffeine and age are clearly skewed to the right: most graduate students are in their twenties, and fewer are older.\n\n### The normal distribution\n\nMany variables in nature and in research have a similar symmetrical, bell-shaped distribution, called the **normal distribution**. It matters because many statistical tests assume that data, or at least averages of data, follow it approximately (Chapter 6 explains why).\n\nA normal distribution is completely described by its mean and standard deviation, and it follows the **68–95–99.7 rule**: about 68% of values lie within one standard deviation of the mean, 95% within two, and 99.7% within three. How close is Elaf's sleep data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep <- first_sem$sleep_hours[!is.na(first_sem$sleep_hours)]\nz <- (sleep - mean(sleep)) / sd(sleep)\nc(within_1_sd = mean(abs(z) < 1),\n  within_2_sd = mean(abs(z) < 2),\n  within_3_sd = mean(abs(z) < 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwithin_1_sd within_2_sd within_3_sd \n  0.7070707   0.9579125   0.9949495 \n```\n\n\n:::\n:::\n\n\nVery close. The values `z` are **z-scores**: how many standard deviations each value is from the mean. They put any variable on the same scale, which makes them useful for spotting unusual values too.\n\nA graph gives a better check than any single number. A **Q-Q plot** (quantile-quantile plot) compares the data with what a normal distribution would give. If the data is normal, the points fall along a straight line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_sem |>\n  select(sleep_hours, caffeine_mg) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"value\") |>\n  ggplot(aes(sample = value)) +\n  stat_qq(alpha = 0.4) +\n  stat_qq_line() +\n  facet_wrap(~ variable, scales = \"free\") +\n  labs(x = \"Expected if normal\", y = \"Observed\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Q-Q plots: sleep follows the straight line closely; caffeine curves away from it.](05-descriptive-statistics_files/figure-html/fig-qq-1.png){#fig-qq fig-alt='Two Q-Q plots. For sleep, the points lie along the diagonal line. For caffeine, the points bend upwards away from the line at the right end.' width=672}\n:::\n:::\n\n\nSleep sits on the line. Caffeine bends away at the upper end, because its largest values are much larger than a normal distribution would produce: the long right tail again.\n\n## Unusual values\n\nAn **outlier** is a value far from the rest. Chapter 3 already removed values that were *impossible*, such as an age of 250. Outliers are different: they are possible, just unusual.\n\nTwo common rules flag them:\n\n- **The box plot rule**: values more than 1.5 × IQR below the first quartile or above the third quartile. These are the points a box plot draws separately.\n- **The z-score rule**: values more than 3 standard deviations from the mean. It suits roughly normal variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq1 <- quantile(first_sem$caffeine_mg, 0.25, na.rm = TRUE)\nq3 <- quantile(first_sem$caffeine_mg, 0.75, na.rm = TRUE)\nupper_fence <- q3 + 1.5 * (q3 - q1)\nupper_fence\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  75% \n442.5 \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(first_sem$caffeine_mg > upper_fence, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 35\n```\n\n\n:::\n:::\n\n\n\n\n35 students take more caffeine than the upper fence of 442 mg. For sleep, which is roughly normal, the z-score rule flags 3 students. Who are the most extreme?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_sem |>\n  filter(sleep_hours <= 4.5, caffeine_mg >= 600) |>\n  select(student_id, sleep_hours, caffeine_mg, study_hours, wellbeing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  student_id sleep_hours caffeine_mg study_hours wellbeing\n1      S0105         3.5         740          58        52\n2      S0124         4.0         845          46        58\n3      S0195         3.6         840          59        58\n4      S0310         3.5         885          57        38\n5      S0312         3.9         785          67        51\n6      S0371         4.1         650          36        53\n7      S0530         4.3         720          65        44\n8      S0554         3.5         900          26        56\n9      S0599         3.6         610          50        47\n```\n\n\n:::\n:::\n\n\nThese students sleep very little, take a lot of caffeine, and study long hours. Nothing about these values is impossible, and they describe a real and worrying group of students: exactly the kind of case Elaf's thesis is about.\n\n::: {.callout-important}\n## Never delete a value just because it is unusual\n\nFirst check whether it is an error (Chapter 3). If it is a real value, keep it: it is part of what you are studying. Report it, and choose summaries and tests that are not thrown off by it, such as the median, or check whether your conclusions change when the unusual cases are left out (a *sensitivity analysis*). Removing inconvenient values to get a cleaner result is a form of research misconduct.\n:::\n\n## Missing data\n\nAlmost every dataset has gaps. Elaf's has three kinds, and each teaches something.\n\nFirst, count them. How much is missing in each variable?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemesters |> summarise(across(everything(), ~ sum(is.na(.x))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  student_id semester gpa sleep_hours study_hours exercise_days caffeine_mg\n1          0        0   1          21          23            20          25\n  supervisor_meetings wellbeing\n1                   0         0\n```\n\n\n:::\n\n```{.r .cell-code}\nstudents |> summarise(across(everything(), ~ sum(is.na(.x))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  student_id supervisor_id age gender faculty programme study_mode employment\n1          0             0   1      0       0         0          0          0\n  has_children lives_away financial_worry workshop workshop_sessions\n1            0          0              38        0                 0\n  considering_dropout\n1                   0\n```\n\n\n:::\n:::\n\n\nA few semester measurements are missing (about 1% each), and 38 students did not answer the question about money worries.\n\nWhat matters most is not *how much* is missing, but *why*. Statisticians distinguish three situations:\n\n- **Missing completely at random**: the gaps have nothing to do with anything. A student skipped a question by accident. Analyses of the remaining data are unbiased, just a little less precise.\n- **Missing at random**: the gaps depend on something you did measure. Analyses can be corrected for it, if you include what it depends on.\n- **Missing not at random**: the gaps depend on the missing value itself. For example, students with the most serious money worries might be the least willing to answer the question about money. This is the hardest case: the students who answered are no longer typical.\n\nThe most important gap in Elaf's data is not a skipped question: it is the students who left the study after the first year. Chapter 3 found 37 of them. Were they like everyone else?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleft_ids <- setdiff(students$student_id,\n                    semesters$student_id[semesters$semester == 3])\n\nfirst_sem |>\n  mutate(left_study = student_id %in% left_ids) |>\n  summarise(\n    students            = n(),\n    wellbeing           = mean(wellbeing),\n    gpa                 = mean(gpa, na.rm = TRUE),\n    considering_dropout = mean(considering_dropout == \"Yes\"),\n    .by = left_study\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  left_study students wellbeing      gpa considering_dropout\n1      FALSE      563  60.66075 3.107620           0.1207815\n2       TRUE       37  57.35135 3.012973           0.5945946\n```\n\n\n:::\n:::\n\n\nThey were not. The students who left already had lower wellbeing in their first semester, and most of them had told Elaf they were considering dropping out. So the students still in the study in semesters 3 and 4 are, on average, the ones who were doing better. If Elaf simply averaged the later semesters, she would overestimate how well graduate students were doing.\n\nWhat should she do? At a minimum, report how many students left and how they differed, as above. Some methods cope with this kind of gap better than others: the mixed-effects models of Chapter 9 use every observation each student provided, including the first year of those who left. More advanced techniques, such as *multiple imputation*, are beyond this book, but worth knowing about if a large share of your data is missing.\n\n## Relationships between variables\n\nDescriptive statistics also describe how variables go together. The **correlation coefficient**, written $r$, measures how closely two numeric variables follow a straight-line relationship. It runs from −1 to +1:\n\n- $r$ near **+1**: as one variable rises, the other rises too.\n- $r$ near **−1**: as one rises, the other falls.\n- $r$ near **0**: no straight-line relationship.\n\nIn the social and behavioural sciences, correlations of about 0.1, 0.3, and 0.5 (positive or negative) are often described as small, medium, and large [@cohen1988]. These are rough guides, not rules.\n\nElaf's questionnaire scores are needed here. They are calculated as in Chapter 3, reversing `stress_4` first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscores <- questionnaire |>\n  mutate(\n    stress_4     = 6 - stress_4,\n    stress       = rowMeans(pick(stress_1:stress_6), na.rm = TRUE),\n    burnout      = rowMeans(pick(burnout_1:burnout_6), na.rm = TRUE),\n    support      = rowMeans(pick(support_1:support_6), na.rm = TRUE),\n    satisfaction = rowMeans(pick(satisfaction_1:satisfaction_4), na.rm = TRUE)\n  ) |>\n  select(student_id, stress, burnout, support, satisfaction)\n\nfirst_sem <- first_sem |> left_join(scores, join_by(student_id))\n\nfirst_sem |>\n  select(stress, burnout, support, wellbeing, gpa) |>\n  cor(use = \"pairwise.complete.obs\") |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          stress burnout support wellbeing   gpa\nstress      1.00    0.65   -0.33     -0.53 -0.31\nburnout     0.65    1.00   -0.24     -0.51 -0.27\nsupport    -0.33   -0.24    1.00      0.36  0.36\nwellbeing  -0.53   -0.51    0.36      1.00  0.32\ngpa        -0.31   -0.27    0.36      0.32  1.00\n```\n\n\n:::\n:::\n\n\n`use = \"pairwise.complete.obs\"` uses every student who has both values for each pair. The table is rich. Stress and burnout go together strongly; students who feel supported by their supervisor report less stress; stress and burnout go with lower wellbeing; support goes with higher GPA.\n\nA **scatter plot matrix** shows the same relationships as graphs, one small scatter plot for each pair of variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(first_sem[, c(\"stress\", \"support\", \"wellbeing\", \"gpa\")],\n      pch = 16, col = rgb(0, 0, 0, 0.25))\n```\n\n::: {.cell-output-display}\n![Scatter plot matrix of stress, support, wellbeing, and GPA in the first semester.](05-descriptive-statistics_files/figure-html/fig-pairs-1.png){#fig-pairs fig-alt='A 4 by 4 grid of small scatter plots, one for each pair of variables; stress and wellbeing slope downwards, support and GPA slope upwards.' width=624}\n:::\n:::\n\n\n`pairs()` comes with R; `pch = 16` draws filled dots, and the `rgb()` colour makes them transparent.\n\n### Correlation is not causation\n\nA correlation says that two variables go together. It does not say that one causes the other. Look at caffeine and GPA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_sem |>\n  select(caffeine_mg, sleep_hours, gpa) |>\n  cor(use = \"pairwise.complete.obs\") |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            caffeine_mg sleep_hours   gpa\ncaffeine_mg        1.00       -0.64 -0.19\nsleep_hours       -0.64        1.00  0.25\ngpa               -0.19        0.25  1.00\n```\n\n\n:::\n:::\n\n\nStudents who take more caffeine have lower GPAs. Does caffeine harm grades? Not necessarily. Caffeine also goes strongly with *less sleep*, and sleep goes with *higher* grades. Perhaps caffeine only looks harmful because heavy caffeine users sleep less. A third variable that produces a misleading correlation like this is called a **confounder**. Chapter 7 shows how regression can separate the two explanations. For now, the lesson is to describe correlations as associations, not as causes.\n\n## Describing your sample in a thesis\n\nThe methods chapter of almost every thesis includes a description of the sample: who took part, and what the main variables look like. It is usually a table. dplyr builds one directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_sem |>\n  summarise(\n    students       = n(),\n    female_pct     = 100 * mean(gender == \"Female\"),\n    phd_pct        = 100 * mean(programme == \"PhD\"),\n    part_time_pct  = 100 * mean(study_mode == \"Part-time\"),\n    age_mean       = mean(age, na.rm = TRUE),\n    age_sd         = sd(age, na.rm = TRUE)\n  ) |>\n  round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  students female_pct phd_pct part_time_pct age_mean age_sd\n1      600         52      29          29.5     29.7    4.8\n```\n\n\n:::\n:::\n\n\nAnd a second table for the main variables, with the mean and SD for symmetrical variables, the median and IQR for skewed ones, and the number missing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe_var <- function(x) {\n  c(mean = mean(x, na.rm = TRUE), sd = sd(x, na.rm = TRUE),\n    median = median(x, na.rm = TRUE), iqr = IQR(x, na.rm = TRUE),\n    missing = sum(is.na(x)))\n}\nsapply(first_sem[, c(\"sleep_hours\", \"study_hours\", \"caffeine_mg\", \"gpa\", \"wellbeing\")],\n       describe_var) |>\n  t() |>\n  round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              mean     sd median    iqr missing\nsleep_hours   6.48   1.03    6.5   1.40       6\nstudy_hours  27.64  13.06   26.0  19.00       8\ncaffeine_mg 189.41 143.62  160.0 135.00       3\ngpa           3.10   0.33    3.1   0.45       0\nwellbeing    60.46  12.01   60.0  17.00       0\n```\n\n\n:::\n:::\n\n\n`describe_var()` is a small function of our own that calculates the five summaries for one variable, and `sapply()` applies it to each column; `t()` turns the result so that each variable is a row. Writing your own functions is a skill for later; for now, you can reuse this one.\n\n\n\nIn the text, describe the sample in a sentence or two, for example:\n\n> The sample consisted of 600 graduate students (52% female; 29% PhD students), aged 23 to 52 (*M* = 29.7, *SD* = 4.8). Students slept 6.5 hours per night on average (*SD* = 1.0), and 65% slept less than the recommended 7 hours.\n\nEvery number in that sentence comes from the code, so it cannot drift out of step with the data.\n\n::: {.callout-tip}\n## An exploration checklist\n\nBefore any test, check for each variable you will use:\n\n1. How many values are missing, and why?\n2. What is the typical value, and how spread out are the values?\n3. What is the shape: symmetrical or skewed, one peak or two?\n4. Are there unusual values, and are they errors or real?\n5. How does it relate to the other variables?\n:::\n\n::: {.callout-note icon=\"false\"}\n## In your field: earth sciences\n\nR's `faithful` dataset records 272 eruptions of the Old Faithful geyser in Yellowstone National Park. The duration of the eruptions is a classic **bimodal** distribution: most eruptions last either about 2 minutes or about 4.5 minutes, and few last in between.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(faithful, aes(x = eruptions)) +\n  geom_histogram(binwidth = 0.2, fill = \"grey70\", colour = \"white\") +\n  labs(x = \"Eruption duration (minutes)\", y = \"Number of eruptions\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Old Faithful eruption durations: a bimodal distribution.](05-descriptive-statistics_files/figure-html/fig-faithful-1.png){#fig-faithful fig-alt='Histogram of eruption durations with two clear peaks, near 2 minutes and near 4.5 minutes.' width=576}\n:::\n:::\n\n\nThe mean of these durations, about 3.5 minutes, describes almost no actual eruption. For a bimodal variable, report the two groups separately, and look for what separates them.\n:::\n\n## Chapter review\n\n### Summary\n\n- Exploratory analysis describes the data; inferential analysis draws conclusions about a population; predictive analysis predicts new cases. Exploration comes first.\n- The mean is sensitive to extreme values; the median is not. Report the mean and SD for symmetrical variables, and the median and IQR for skewed ones.\n- The shape of a distribution can be symmetrical or skewed, and unimodal or bimodal. Skewness measures asymmetry; histograms, density plots, and Q-Q plots show it.\n- The normal distribution follows the 68–95–99.7 rule. z-scores give each value's distance from the mean in standard deviations.\n- Outliers can be flagged with the box plot rule or z-scores. Check them, but never delete real values just because they are unusual.\n- Why data is missing matters more than how much. Students who leave a study are rarely a random selection.\n- The correlation $r$ measures a straight-line relationship, from −1 to +1. Correlation is not causation: a confounder can create a misleading association.\n\n### Key terms\n\nDescriptive statistics, exploratory analysis, inferential analysis, predictive analysis, mean, median, mode, range, variance, standard deviation, quartile, interquartile range, skewness, symmetrical, unimodal, bimodal, normal distribution, z-score, Q-Q plot, outlier, missing completely at random, missing at random, missing not at random, attrition, correlation coefficient, confounder.\n\n## Exercises\n\nThe [playground](../playground/chapter05.html) has these and more, with hints and solutions.\n\n1. Calculate the mean, median, SD, and IQR of first-semester `study_hours`. Is the variable closer to symmetrical or skewed? Which pair of summaries would you report?\n2. Draw a Q-Q plot of first-semester `wellbeing`. Does it look normal?\n3. Using the box plot rule, how many students have unusually high `study_hours` in the first semester?\n4. Compare the first-semester `sleep_hours` of students who later left the study with those who stayed. Do they differ in sleep as they did in wellbeing?\n5. Find the correlation between `support` and `satisfaction`. Using Cohen's guidelines, is it small, medium, or large? Can you conclude that support causes satisfaction?\n\n## Further reading\n\n- *R for Data Science* [@wickham2023]: chapters \"Exploratory data analysis\" and \"Missing values\".\n- *Statistical Power Analysis for the Behavioral Sciences* [@cohen1988] is the source of the small, medium, and large guidelines for effect sizes, including correlations.\n",
    "supporting": [
      "05-descriptive-statistics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}