{
  "hash": "a6adf2a7c9bd44ea21bf9b4e791f12dc",
  "result": {
    "engine": "knitr",
    "markdown": "# Predictive Regression {#sec-ch13}\n\n\n\nResearch data often contains many possible predictors for rather few cases. A questionnaire with dozens of items, several rounds of measurement, and a background survey can easily supply 50 predictors for a sample of 60 or 100 people. Ordinary regression estimates a coefficient for every predictor, and with that much freedom it can fit its own data almost perfectly while predicting new cases badly: the overfitting of Chapter 11, now in its most common form. The problem is made worse when predictors are correlated, as questionnaire items usually are.\n\nThis chapter introduces two families of methods that make many predictors usable. **Regularised regression** (ridge, lasso, and elastic net) keeps the familiar linear model but shrinks its coefficients towards zero, trading a little fit on the training data for much better predictions. **Boosting** builds a flexible model from many small decision trees, each correcting the errors of the ones before. The chapter also introduces the measures used to judge numeric predictions. The outcome is now a number, so this is a **regression** problem in the machine learning sense of Chapter 11. In the study, it answers the tenth research question (RQ10): the university's academic advisers meet every student at the end of the first year, and would like to know from year-one information which students are heading for a low final GPA, so that extra support can be planned.\n\n::: {.callout-tip appearance=\"simple\"}\n## By the end of this chapter you will be able to\n\n- Measure the accuracy of numeric predictions with RMSE, MAE, and R², and compare them with a baseline.\n- Explain why ordinary regression overfits when there are many predictors.\n- Fit and tune ridge, lasso, and elastic net regression, and read which predictors the lasso keeps.\n- Explain how boosting builds a model from many small trees, and tune an XGBoost model.\n- Choose between models with cross-validation, and report the final model's accuracy on the test set.\n:::\n::: {.callout-note appearance=\"simple\" icon=\"false\"}\n**Teaching & Practice:** [Interactive Lecture Slides](../slides/13-predictive-regression.html) · [Browser Playground Exercises](../playground/chapter13.html)\n:::\n\n\n## Data for predicting final GPA\n\nThe advisers meet students at the end of year one, so the model may use only what is known by then: the students' background, their questionnaire answers, and their records from semesters 1 and 2. The outcome is GPA in semester 4.\n\nThis time, every questionnaire item is used as a separate predictor, rather than the four scale scores, to show how the methods cope with many related predictors. The semester records are in long format (one row per student per semester); for prediction, they are needed in wide format, one row per student, with a column for each measure in each semester. `pivot_wider()` from Chapter 3 does this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidymodels)\ntidymodels_prefer()\n\nyear_one <- semesters |>\n  filter(semester <= 2) |>\n  pivot_wider(id_cols = student_id, names_from = semester,\n              values_from = gpa:wellbeing, names_glue = \"{.value}_s{semester}\")\n\nfinal_gpa <- semesters |>\n  filter(semester == 4, !is.na(gpa)) |>\n  select(student_id, final_gpa = gpa)\n\ngpa_data <- students |>\n  left_join(questionnaire, join_by(student_id)) |>\n  left_join(year_one, join_by(student_id)) |>\n  inner_join(final_gpa, join_by(student_id)) |>\n  select(-student_id, -supervisor_id, -considering_dropout)\n\ndim(gpa_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 563  48\n```\n\n\n:::\n:::\n\n\nThe argument `names_glue` builds the new column names, such as `gpa_s1` and `sleep_hours_s2`, and `inner_join()` keeps only students who have a final GPA. That is an important limitation: the 37 students who left the programme have no final GPA, so the model can only predict the final GPA of students who stay. (Chapter 6 showed that the leavers were not a random group, so the model should not be used to judge them.)\n\nThe split, folds, and recipe follow Chapter 11. With a numeric outcome, `strata` splits the outcome into quartiles and samples within each, so that both sets cover the full range of GPAs. The recipe adds `step_impute_mode()` to fill in any missing categories:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ngpa_split <- initial_split(gpa_data, prop = 0.75, strata = final_gpa)\ngpa_train <- training(gpa_split)\ngpa_test  <- testing(gpa_split)\n\nset.seed(2026)\ngpa_folds <- vfold_cv(gpa_train, v = 10, strata = final_gpa)\n\ngpa_recipe <- recipe(final_gpa ~ ., data = gpa_train) |>\n  step_impute_median(all_numeric_predictors()) |>\n  step_impute_mode(all_nominal_predictors()) |>\n  step_dummy(all_nominal_predictors()) |>\n  step_normalize(all_numeric_predictors())\n\ngpa_recipe |> prep() |> bake(new_data = NULL) |> ncol()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52\n```\n\n\n:::\n:::\n\n\nAfter the dummy variables are created, there are 51 predictors, plus the outcome.\n\n## Measuring prediction error\n\nThe quality of a numeric prediction is judged by its errors. Five students whose final GPA a model has predicted show how:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntiny <- tibble(\n  actual    = c(3.2, 2.8, 3.6, 3.0, 2.5),\n  predicted = c(3.0, 2.9, 3.3, 3.1, 2.9)\n)\ntiny |> mutate(error = actual - predicted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  actual predicted  error\n   <dbl>     <dbl>  <dbl>\n1    3.2       3    0.200\n2    2.8       2.9 -0.100\n3    3.6       3.3  0.300\n4    3         3.1 -0.100\n5    2.5       2.9 -0.4  \n```\n\n\n:::\n:::\n\n\nEach **error** (or residual) is the actual value minus the prediction, and three measures summarise them. The **MAE** (mean absolute error) is the average size of the errors, ignoring their sign; here, (0.2 + 0.1 + 0.3 + 0.1 + 0.4) / 5 = 0.22 GPA points. The **RMSE** (root mean squared error) squares the errors, averages them, and takes the square root. Squaring gives large errors more weight, so the RMSE is always at least as large as the MAE, and much larger when there are a few big misses. **R²**, in yardstick, is the squared correlation between the predictions and the actual values: as in Chapter 8, the share of the variation in the outcome that the predictions capture, from 0 to 1. The yardstick package calculates all three:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression_metrics <- metric_set(rmse, mae, rsq)\ntiny |> regression_metrics(truth = actual, estimate = predicted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard       0.249\n2 mae     standard       0.220\n3 rsq     standard       0.785\n```\n\n\n:::\n:::\n\n\nMAE and RMSE are in the units of the outcome, here GPA points, which makes them easy to explain: \"the model's predictions are typically off by about 0.2 GPA points\". Lower is better. R² has no units; higher is better.\n\nA number on its own means little, so every model should be compared with a **baseline**: the simplest possible prediction. For a numeric outcome, the baseline predicts the same value, the training mean, for everyone, which is what parsnip's `null_model()` does:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_wf <- workflow(gpa_recipe, null_model(mode = \"regression\"))\n\nset.seed(2026)\nnull_cv <- fit_resamples(null_wf, resamples = gpa_folds, metrics = metric_set(rmse, mae))\ncollect_metrics(null_cv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  .metric .estimator  mean     n std_err .config        \n  <chr>   <chr>      <dbl> <int>   <dbl> <chr>          \n1 mae     standard   0.256    10 0.00738 pre0_mod0_post0\n2 rmse    standard   0.323    10 0.0104  pre0_mod0_post0\n```\n\n\n:::\n:::\n\n\n\n\nPredicting the average GPA for everyone gives an RMSE of 0.32. Any useful model must do clearly better. (The R² of the baseline cannot be calculated, because its predictions do not vary, so it is left out here.)\n\n## Ordinary regression with many predictors\n\nThe obvious model is the multiple regression of Chapter 8, using every predictor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_wf <- workflow(gpa_recipe, linear_reg())\n\nset.seed(2026)\nlm_cv <- fit_resamples(lm_wf, resamples = gpa_folds, metrics = regression_metrics)\ncollect_metrics(lm_cv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  .metric .estimator  mean     n std_err .config        \n  <chr>   <chr>      <dbl> <int>   <dbl> <chr>          \n1 mae     standard   0.172    10 0.00615 pre0_mod0_post0\n2 rmse    standard   0.218    10 0.0105  pre0_mod0_post0\n3 rsq     standard   0.564    10 0.0420  pre0_mod0_post0\n```\n\n\n:::\n:::\n\n\n\n\nA cross-validated RMSE of 0.218, much better than the baseline. With 422 training students and 51 predictors, ordinary regression works reasonably well. But watch what happens with fewer students. Many theses have samples of 50 or 60, so here is the same model fitted to 60 randomly chosen training students, and tested on the test set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\nsmall_train <- gpa_train |> slice_sample(n = 60)\n\nlm_small <- fit(lm_wf, data = small_train)\naugment(lm_small, new_data = small_train) |> regression_metrics(final_gpa, .pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard      0.115 \n2 mae     standard      0.0918\n3 rsq     standard      0.876 \n```\n\n\n:::\n\n```{.r .cell-code}\naugment(lm_small, new_data = gpa_test) |> regression_metrics(final_gpa, .pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard      0.526 \n2 mae     standard      0.430 \n3 rsq     standard      0.0456\n```\n\n\n:::\n:::\n\n\n\n\nOn its own 60 students, the model looks excellent: an RMSE of 0.11. On new students, its RMSE is 0.53, *worse than predicting the average GPA for everyone*. With 51 coefficients estimated from 60 students, the model has enough freedom to fit the noise in its sample, and the coefficients that fit the noise do not carry over. In the extreme, with as many predictors as students, a regression can fit its data perfectly and predict nothing.\n\nThe problem is made worse by **multicollinearity**: many of the predictors are strongly correlated (six stress items, two semesters of GPA), and regression struggles to divide the credit between correlated predictors. Their coefficients become large, unstable, and sometimes of opposite signs, cancelling each other out on the training data but not on new data.\n\n## Regularised regression\n\n**Regularisation** tackles this directly: it fits the regression while penalising large coefficients. Ordinary regression chooses the coefficients that minimise the sum of squared errors. Regularised regression minimises\n\n$$\n\\text{sum of squared errors} + \\lambda \\times \\text{size of the coefficients}.\n$$\n\nThe **penalty** $\\lambda$ (lambda) sets how much large coefficients cost. With $\\lambda = 0$, this is ordinary regression; as $\\lambda$ grows, the coefficients are pulled, or **shrunk**, towards zero. A little shrinkage costs almost nothing in fit to the training data, but makes the model much more stable on new data. Because the penalty depends on the size of the coefficients, the predictors must be on the same scale, which the recipe's `step_normalize()` ensures. There are three versions, which differ in how \"size\" is measured. **Ridge regression** uses the sum of the *squared* coefficients: it shrinks all coefficients towards zero and shares the credit among correlated predictors, but keeps every predictor in the model. The **lasso** (least absolute shrinkage and selection operator) uses the sum of the *absolute* coefficients [@tibshirani1996]. It shrinks too, but it also sets some coefficients to exactly zero, removing those predictors, so it also *selects* predictors and leaves a simpler model. The **elastic net** mixes the two, with a **mixture** parameter that runs from 0 (pure ridge) to 1 (pure lasso).\n\nIn tidymodels, all three are `linear_reg()` with the **glmnet** engine, with `penalty` for $\\lambda$ and `mixture` for the mix. The 60 students are now refitted with a lasso:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlasso_small <- workflow(gpa_recipe,\n                        linear_reg(penalty = 0.03, mixture = 1) |> set_engine(\"glmnet\")) |>\n  fit(data = small_train)\n\naugment(lasso_small, new_data = gpa_test) |> regression_metrics(final_gpa, .pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 rmse    standard       0.204\n2 mae     standard       0.168\n3 rsq     standard       0.616\n```\n\n\n:::\n:::\n\n\n\n\nFrom the same 60 students, the lasso's RMSE on new students is 0.20, against 0.53 for ordinary regression. The penalty kept the model from chasing noise.\n\nThe difference lies in the coefficients. @fig-shrinkage compares, predictor by predictor, the coefficients that ordinary regression and the lasso estimated from the same 60 students:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefficient_comparison <- tidy(lm_small) |>\n  select(term, ordinary = estimate) |>\n  inner_join(tidy(lasso_small) |> select(term, lasso = estimate), join_by(term)) |>\n  filter(term != \"(Intercept)\")\n\nggplot(coefficient_comparison, aes(x = ordinary, y = lasso)) +\n  geom_hline(yintercept = 0, colour = \"grey70\") +\n  geom_vline(xintercept = 0, colour = \"grey70\") +\n  geom_point(size = 2, alpha = 0.7, colour = \"#2f6793\") +\n  labs(x = \"Ordinary regression coefficient\", y = \"Lasso coefficient\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Coefficients estimated from the same 60 students by ordinary regression (horizontal axis) and by the lasso (vertical axis), one point per predictor. Ordinary regression spreads large coefficients over many predictors; the lasso sets most of them to zero and keeps a few, smaller ones.](13-predictive-regression_files/figure-html/fig-shrinkage-1.png){#fig-shrinkage fig-alt='Scatter plot with ordinary regression coefficients on the x axis, spread widely in both directions, and lasso coefficients on the y axis. Most points lie on the horizontal line at zero; a handful sit above or below it, close to zero compared with their spread along the x axis.' width=576}\n:::\n:::\n\n\n\n\nOrdinary regression gives every predictor a coefficient, many of them large and in both directions: with 60 students, it cannot tell real effects from the chance patterns of this sample, so it fits both. Some of its coefficients make no sense. Semester 1 GPA, one of the best predictors of final GPA, receives a negative coefficient (-0.03), and caffeine in semester 2 receives a larger one (0.17) than semester 2 GPA (0.16). The lasso gives both GPA measures positive coefficients (0.08 and 0.12) and almost nothing to caffeine. The lasso keeps only 12 of the 51 predictors and shrinks even those. This is the sense in which shrinkage trades fit for stability: coefficients pulled towards zero cannot chase the noise of one sample, so they carry over better to the next.\n\n### Choosing the penalty\n\nThe penalty and mixture are hyperparameters, so they are tuned with cross-validation, now on the full training set. The grid tries 20 penalties, spread evenly on a logarithmic scale from 0.0001 to 1, for ridge, an even elastic net, and lasso:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglmnet_wf <- workflow(gpa_recipe,\n                      linear_reg(penalty = tune(), mixture = tune()) |> set_engine(\"glmnet\"))\n\nglmnet_grid <- expand_grid(penalty = 10^seq(-4, 0, length.out = 20),\n                           mixture = c(0, 0.5, 1))\n\nset.seed(2026)\nglmnet_tuning <- tune_grid(glmnet_wf, resamples = gpa_folds, grid = glmnet_grid,\n                           metrics = metric_set(rmse))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(glmnet_tuning) + theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Cross-validated RMSE of ridge (mixture 0), elastic net (0.5), and lasso (1) regression for a range of penalties.](13-predictive-regression_files/figure-html/fig-glmnet-tuning-1.png){#fig-glmnet-tuning fig-alt='Line chart of RMSE against penalty on a logarithmic scale, with three lines. All three start at similar values for small penalties. The lasso and elastic net lines dip to a minimum at moderate penalties, then rise steeply to the baseline\\'s error. The ridge line stays almost flat and rises only for the largest penalties.' width=624}\n:::\n:::\n\n\n@fig-glmnet-tuning shows the typical pattern. With a tiny penalty, all three behave like ordinary regression. As the penalty grows, the RMSE improves, reaches a minimum, and then rises steeply once the penalty is so large that it shrinks away real effects too. At the far right, the lasso has shrunk every coefficient to zero and predicts the mean for everyone: its RMSE equals the baseline's.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow_best(glmnet_tuning, metric = \"rmse\", n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 8\n  penalty mixture .metric .estimator  mean     n std_err .config         \n    <dbl>   <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>           \n1  0.0127     1   rmse    standard   0.204    10 0.00871 pre0_mod33_post0\n2  0.0207     1   rmse    standard   0.205    10 0.00811 pre0_mod36_post0\n3  0.0336     0.5 rmse    standard   0.205    10 0.00813 pre0_mod38_post0\n```\n\n\n:::\n:::\n\n\n\n\nThe best combination is a mixture of 1 with a penalty of 0.013, but the top few are nearly identical. The function `select_best()` picks the winner, and `finalize_workflow()` plugs it in:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_penalty <- select_best(glmnet_tuning, metric = \"rmse\")\nlasso_fit <- glmnet_wf |>\n  finalize_workflow(best_penalty) |>\n  fit(data = gpa_train)\n```\n:::\n\n\n### Predictors kept by the lasso\n\nThe function `tidy()` lists the coefficients, most of which are exactly zero:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlasso_coefs <- tidy(lasso_fit)\nlasso_coefs |>\n  filter(estimate != 0) |>\n  arrange(desc(abs(estimate)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 3\n   term                  estimate penalty\n   <chr>                    <dbl>   <dbl>\n 1 (Intercept)           3.10      0.0127\n 2 gpa_s2                0.145     0.0127\n 3 gpa_s1                0.106     0.0127\n 4 satisfaction_2        0.00986   0.0127\n 5 stress_3             -0.00890   0.0127\n 6 study_mode_Part.time  0.00812   0.0127\n 7 burnout_1            -0.00688   0.0127\n 8 burnout_4            -0.00622   0.0127\n 9 study_hours_s2        0.00557   0.0127\n10 burnout_6            -0.00210   0.0127\n11 support_3            -0.000169  0.0127\n```\n\n\n:::\n:::\n\n\n\n\nOf 51 predictors, the lasso keeps 10. Because the predictors are normalised, the coefficients are comparable: the change in predicted final GPA for a one-standard-deviation difference in the predictor. Year-one GPA dominates. A student whose semester 2 GPA is one standard deviation above average is predicted to finish about 0.15 GPA points higher; the other predictors add small adjustments.\n\n@fig-lasso-path shows how the lasso arrives at this. As the penalty decreases from left to right, predictors enter the model one by one, and the two GPA measures enter first.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Lasso coefficient paths. Each line is one predictor's coefficient as the penalty decreases from left to right. The dashed line marks the chosen penalty.](13-predictive-regression_files/figure-html/fig-lasso-path-1.png){#fig-lasso-path fig-alt='Line chart of coefficients against penalty (logarithmic scale, decreasing to the right). At large penalties all coefficients are zero. Two lines, semester 2 GPA and semester 1 GPA, rise first and highest. Many other lines leave zero only at smaller penalties and stay close to zero.' width=624}\n:::\n:::\n\n\n::: {.callout-warning}\n## Selected is not the same as causal\n\nIt is tempting to read the lasso's choice as a list of what *matters* for grades. It is not. Sleep affects GPA in the wellbeing data (Chapter 8), yet the lasso drops the sleep variables, because their effect is already reflected in year-one GPA: once the model knows a student's past grades, knowing their sleep adds little to the *prediction*. Among correlated predictors, the lasso tends to keep one and drop the others, and which one it keeps can change from sample to sample. Use the lasso to predict, and use the methods of Chapters 8 and 10 to explain.\n:::\n\n## Boosting\n\nThe second family builds a model in a completely different way. **Boosting** starts with a very simple prediction, the average, and then adds small decision trees one at a time, each fitted to the *errors* of the model so far. The first tree learns the biggest pattern in the errors; the next tree learns what the first missed; and so on. Each tree's contribution is scaled down by a **learning rate** (for example 0.1), so the model improves in small steps and no single tree dominates. Hundreds of trees, each weak on its own, add up to a strong model.\n\n@fig-boosting shows the idea with a single predictor, semester 2 GPA, and trees with a single split. After one tree, the prediction is a single step; after ten, a staircase; after a hundred, a curve that follows the data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Boosting with one predictor. Predicted final GPA from semester 2 GPA after 1, 10, and 100 trees, each with a single split.](13-predictive-regression_files/figure-html/fig-boosting-1.png){#fig-boosting fig-alt='Three panels of final GPA against semester 2 GPA, with the training students as grey points. In the first panel, the prediction is a single step; in the second, a staircase with a few steps; in the third, a finely stepped line rising with semester 2 GPA and following the points closely.' width=768}\n:::\n:::\n\n\nBoosting is closely related to the random forests of Chapter 12, which also combine many trees. The difference is that a forest grows its trees *independently* and averages them, while boosting grows them *in sequence*, each correcting the last. **XGBoost** (\"extreme gradient boosting\") is a fast, popular implementation [@chen2016], and one of the most successful methods for tables of data. Its main hyperparameters are the number of trees, the learning rate, and the depth of each tree. A small learning rate needs more trees; deeper trees capture interactions between predictors. Here, 500 trees are used, and the learning rate and depth are tuned:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxgb_wf <- workflow(gpa_recipe,\n                   boost_tree(trees = 500, learn_rate = tune(), tree_depth = tune()) |>\n                     set_engine(\"xgboost\") |>\n                     set_mode(\"regression\"))\n\nset.seed(2026)\nxgb_tuning <- tune_grid(xgb_wf, resamples = gpa_folds,\n                        grid = expand_grid(learn_rate = c(0.01, 0.03, 0.1),\n                                           tree_depth = c(1, 2, 4)),\n                        metrics = metric_set(rmse))\nshow_best(xgb_tuning, metric = \"rmse\", n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 8\n  tree_depth learn_rate .metric .estimator  mean     n std_err .config        \n       <dbl>      <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>          \n1          1       0.03 rmse    standard   0.212    10 0.00968 pre0_mod2_post0\n2          2       0.01 rmse    standard   0.213    10 0.00928 pre0_mod4_post0\n3          1       0.01 rmse    standard   0.213    10 0.00834 pre0_mod1_post0\n```\n\n\n:::\n:::\n\n\n\n\nThe best settings use trees of depth 1, and the best RMSE is 0.212. Trees of depth 1 use one predictor each, so a boosted model built from them adds up separate effects of each predictor, with no interactions. That the shallowest trees work best is another sign that the wellbeing data has no strong interactions for the trees to find.\n\n## Comparing the models\n\nAll the models were evaluated with the same folds, so their cross-validated RMSEs can be compared directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  collect_metrics(null_cv) |> mutate(model = \"Baseline (mean)\"),\n  collect_metrics(lm_cv) |> mutate(model = \"Linear regression\"),\n  show_best(glmnet_tuning |> filter_parameters(mixture == 0), metric = \"rmse\", n = 1) |>\n    mutate(model = \"Ridge\"),\n  show_best(glmnet_tuning |> filter_parameters(mixture == 0.5), metric = \"rmse\", n = 1) |>\n    mutate(model = \"Elastic net\"),\n  show_best(glmnet_tuning |> filter_parameters(mixture == 1), metric = \"rmse\", n = 1) |>\n    mutate(model = \"Lasso\"),\n  show_best(xgb_tuning, metric = \"rmse\", n = 1) |> mutate(model = \"XGBoost\")\n) |>\n  filter(.metric == \"rmse\") |>\n  select(model, rmse = mean, std_err) |>\n  arrange(rmse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  model              rmse std_err\n  <chr>             <dbl>   <dbl>\n1 Lasso             0.204 0.00871\n2 Elastic net       0.205 0.00813\n3 XGBoost           0.212 0.00968\n4 Ridge             0.213 0.00938\n5 Linear regression 0.218 0.0105 \n6 Baseline (mean)   0.323 0.0104 \n```\n\n\n:::\n:::\n\n\nThe function `filter_parameters()` keeps only the tuning results with a given mixture, so the best ridge, elastic net, and lasso can be picked out separately.\n\nThe regularised models come out on top, followed closely by XGBoost, and all of them improve on ordinary regression. The differences between the best models are smaller than their standard errors. The lasso is chosen: it predicts as well as any, and it uses only 10 predictors, which makes it the easiest to explain and to use.\n\n## The final test\n\nAs always, the test set is used once, at the end. The function `last_fit()` fits the chosen model on the full training set and evaluates it on the test students:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_lasso <- glmnet_wf |>\n  finalize_workflow(best_penalty) |>\n  last_fit(gpa_split, metrics = regression_metrics)\ncollect_metrics(final_lasso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  .metric .estimator .estimate .config        \n  <chr>   <chr>          <dbl> <chr>          \n1 rmse    standard       0.192 pre0_mod0_post0\n2 mae     standard       0.161 pre0_mod0_post0\n3 rsq     standard       0.648 pre0_mod0_post0\n```\n\n\n:::\n:::\n\n\n\n\nOn new students, the lasso's predictions are off by 0.16 GPA points on average (MAE), with an RMSE of 0.19, and they capture 65% of the variation in final GPA. @fig-pred-actual compares the predictions with the actual final GPAs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncollect_predictions(final_lasso) |>\n  ggplot(aes(x = .pred, y = final_gpa)) +\n  geom_abline(linetype = \"dashed\", colour = \"grey50\") +\n  geom_point(alpha = 0.6, colour = \"#2f6793\") +\n  coord_obs_pred() +\n  labs(x = \"Predicted final GPA\", y = \"Actual final GPA\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Predicted and actual final GPA for the test students. Points on the dashed line are predicted perfectly.](13-predictive-regression_files/figure-html/fig-pred-actual-1.png){#fig-pred-actual fig-alt='Scatter plot of actual final GPA against predicted final GPA for the test students. The points form an upward band around the diagonal line. The predictions span a narrower range than the actual values: the lowest and highest actual GPAs are predicted closer to the average.' width=480}\n:::\n:::\n\n\nThe function `coord_obs_pred()` from tune gives both axes the same range, so the diagonal is at 45 degrees. The predictions are less spread out than the actual values: the model predicts the most extreme students closer to the average than they turn out to be. This is normal for any model that cannot predict perfectly, and it means that the model is most reliable for students in the middle of the range.\n\nA last comparison shows how much all the year-one measures add to past grades. A plain regression on the two year-one GPAs alone gives:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_only_wf <- workflow(recipe(final_gpa ~ gpa_s1 + gpa_s2, data = gpa_train), linear_reg())\ngpa_only_fit <- last_fit(gpa_only_wf, gpa_split, metrics = regression_metrics)\ncollect_metrics(gpa_only_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  .metric .estimator .estimate .config        \n  <chr>   <chr>          <dbl> <chr>          \n1 rmse    standard       0.193 pre0_mod0_post0\n2 mae     standard       0.163 pre0_mod0_post0\n3 rsq     standard       0.641 pre0_mod0_post0\n```\n\n\n:::\n:::\n\n\n\n\nIts test RMSE, 0.193, is practically the same as the lasso's 0.192. For the advisers, this is a useful, if humbling, result: past grades are by far the best predictor of future grades, and the questionnaire and semester records add little on top. That does not make sleep, stress, or support irrelevant to grades (Chapter 8 showed that they matter), but their influence is already visible in the year-one grades.\n\n::: {.callout-note icon=\"false\"}\n## In your field: engineering\n\nEngineers predict the strength of concrete from its recipe. The `concrete` data in the **modeldata** package records the compressive strength of 1030 concrete samples, with the amounts of cement, water, and six other ingredients, and the age of the sample in days [@yeh1998]. Strength rises with age, but less and less, and the ingredients interact: exactly the kind of structure where boosting shines.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(concrete, package = \"modeldata\")\nset.seed(1)\nconcrete_split <- initial_split(concrete)\n\nlm_concrete <- workflow(compressive_strength ~ ., linear_reg())\nxgb_concrete <- workflow(compressive_strength ~ .,\n                         boost_tree(trees = 500, learn_rate = 0.05, tree_depth = 4) |>\n                           set_engine(\"xgboost\") |>\n                           set_mode(\"regression\"))\n\nlm_concrete_fit  <- last_fit(lm_concrete, concrete_split)\nxgb_concrete_fit <- last_fit(xgb_concrete, concrete_split)\ncollect_metrics(lm_concrete_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  .metric .estimator .estimate .config        \n  <chr>   <chr>          <dbl> <chr>          \n1 rmse    standard      10.6   pre0_mod0_post0\n2 rsq     standard       0.603 pre0_mod0_post0\n```\n\n\n:::\n\n```{.r .cell-code}\ncollect_metrics(xgb_concrete_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  .metric .estimator .estimate .config        \n  <chr>   <chr>          <dbl> <chr>          \n1 rmse    standard       4.54  pre0_mod0_post0\n2 rsq     standard       0.926 pre0_mod0_post0\n```\n\n\n:::\n:::\n\n\n\n\nAs the code shows, `workflow()` also accepts a formula in place of a recipe. Boosting cuts the RMSE from 10.6 to 4.5 megapascals. The lesson of this chapter and the last is the same from both sides: flexible models win when the data has curves and interactions, and simple models are just as good when it does not. Only a fair comparison can tell which case you are in.\n:::\n\n## Common misconceptions\n\nPredictive regression invites a few characteristic misreadings.\n\n- **\"More predictors always help.\"** Each extra coefficient is another chance to fit noise; with few cases, adding predictors can make predictions worse.\n- **\"The predictors the lasso keeps are the ones that matter.\"** The lasso keeps the predictors that help *prediction*, and among correlated predictors it keeps one more or less arbitrarily.\n- **\"A low RMSE means every prediction is accurate.\"** The RMSE is a typical error; predictions for students at the extremes are pulled towards the average and can be far off.\n- **\"Boosting is always better than regression.\"** Boosting wins when the data has curves and interactions; on smooth data, regularised regression predicts as well and is easier to explain.\n\n## Chapter review\n\n### Summary\n\n- For numeric predictions, the MAE and RMSE measure the typical error in the units of the outcome (lower is better), and R² the share of variation captured. Always compare with a baseline that predicts the mean.\n- With many predictors relative to the number of cases, and correlated predictors, ordinary regression overfits: excellent on the training data, poor on new data.\n- Regularised regression penalises large coefficients. Ridge shrinks all coefficients; the lasso also sets some to zero, selecting predictors; the elastic net mixes the two. The penalty and mixture are tuned by cross-validation, and the predictors must be normalised.\n- The predictors a lasso selects are useful for prediction, not evidence of causes.\n- Boosting adds small trees one at a time, each fitted to the errors of the model so far. XGBoost's main hyperparameters are the number of trees, the learning rate, and the tree depth.\n- On the wellbeing data, regularised regression and boosting predict final GPA about equally well, and year-one GPA carries most of the information. On data with curves and interactions, boosting can be far better.\n\n### Key terms\n\nRegression (prediction), error, residual, MAE, RMSE, R², baseline model, overfitting, multicollinearity, regularisation, penalty (lambda), shrinkage, ridge regression, lasso, elastic net, mixture, coefficient path, variable selection, boosting, weak learner, learning rate, XGBoost, tree depth.\n\n## Exercises\n\nThe [playground](../playground/chapter13.html) has these and more, with hints and solutions.\n\n1. Calculate the MAE and RMSE of the tiny example by hand (or with basic R arithmetic), and check them against yardstick. Change one prediction so that it is off by 1.0 GPA point, and explain which measure changes more, and why.\n2. Repeat the 60-student experiment with 150 students, and report the gap between ordinary regression and the lasso.\n3. Fit a ridge regression (mixture 0) with the best ridge penalty, compare its coefficients with the lasso's, and count how many are exactly zero.\n4. Replace the 22 questionnaire items with the four scale scores (as in Chapter 11), and describe how the cross-validated RMSE of the lasso changes.\n5. Tune XGBoost with `trees = c(100, 500, 1000)` and a learning rate of 0.03, and describe what happens to the RMSE as trees are added.\n6. Write two sentences for the academic advisers explaining what an RMSE of 0.2 means for an individual student's predicted GPA.\n\n## Further reading\n\n- *Tidy Modeling with R* [@kuhn2022] covers regularised regression and boosted trees in tidymodels, including more efficient tuning methods.\n- *An Introduction to Statistical Learning* [@james2021islr] explains ridge regression, the lasso, and boosting clearly, with the ideas behind why shrinkage helps.\n- Tibshirani's paper introducing the lasso [@tibshirani1996] is a classic of modern statistics.\n",
    "supporting": [
      "13-predictive-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}