{
  "hash": "0585c3adf0f60b98a9c7215964fbd3e0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Complete Thesis Project\"\nsubtitle: \"End-to-End Pipeline, Project Architecture, Scientific Chain of Reasoning, and Defense Synthesis\"\nauthor: \"Dr. Polla Fattah\"\ninstitute: \"From Data to Thesis: Research Data Analysis with R\"\nformat:\n  revealjs:\n    theme: [default, ../../styles/theme.scss]\n    slide-number: true\n    preview-links: auto\n    chalkboard: true\n    transition: slide\n    highlight-style: github\n    code-line-numbers: false\n    width: 1200\n    height: 750\nexecute:\n  freeze: auto\n---\n\n# Putting It All Together\n\n### From Messy Raw Survey to the Final Dissertation Defense\n\n**Chapter 19 · From Data to Thesis**\n\nDr. Polla Fattah\n\n---\n\n## The Supervisor's Final Advice\n\nIn the final semester of graduate study:\n\n> *\"Before you type a single paragraph of your results chapter, rebuild your entire analysis—from the raw Excel export to the final regression table—as a single, self-contained pipeline that executes seamlessly from start to finish.*  \n> \n> *Then you will know that every number in your thesis is true, and you can answer any examiner's challenge by pointing directly to the code.\"*\n\n---\n\n## A Thesis Is an Argument; Data Is the Evidence\n\nA doctoral or master's thesis convinces examiners when every claim rests on an unbroken chain of reasoning:\n\n```\n+-----------------------------------------------------------------------------------+\n|                            THE SCIENTIFIC CHAIN                                   |\n+-------------+-------------+-------------+-------------+-------------+-------------+\n|  Research   | Experimental| Operational | Statistical | Empirical   | Theoretical |\n|  Question   |   Design    |  Variables  |    Model    |   Result    | Conclusion  |\n+-------------+-------------+-------------+-------------+-------------+-------------+\n```\n\nIf one link is broken:\n- A table copied by hand before outlier cleaning.\n- A causal claim made on purely observational data.\n- An examiner unable to reproduce the findings.\n\nThe argument collapses. This capstone chapter locks every link together.\n\n---\n\n## The Research Project Lifecycle\n\nEvery empirical quantitative investigation follows this journey:\n\n```\n    Plan & Frame                  Collect & Import                 Clean & Tidy\n  [ Ch 5: RQ / Design ] -------> [ Ch 1-2: R / Import ] -------> [ Ch 3: Tidyverse ]\n                                                                        |\n                                                                        v\n   Communicate & Defend           Model & Test                   Explore & Plot\n [ Ch 17-19: Quarto / APA ] <--- [ Ch 7-16: Inference / ML ] <-- [ Ch 4, 6: EDA / Viz ]\n```\n\n- In reality, research is an iterative loop: exploratory plotting reveals dirty data, and model diagnostics trigger data transformations.\n- **Writing every step in clean R scripts makes iteration painless.**\n\n---\n\n# Professional Project Architecture\n\n### Structuring a Self-Contained Graduate Codebase\n\n---\n\n## The Directory Layout\n\nA reproducible research repository must be immediately navigable:\n\n```\nwellbeing-thesis/\n├── wellbeing-thesis.Rproj      # RStudio Project Root\n├── README.md                   # Purpose, execution instructions, software requirements\n├── data-raw/\n│   └── wellbeing_raw.xlsx      # Read-only raw export (NEVER touch or edit)\n├── data/\n│   ├── clean_questionnaire.rds # Generated by 01-clean-data.R\n│   └── clean_semesters.rds     # Clean longitudinal panel\n├── R/\n│   ├── 01-clean-data.R         # Raw survey -> Tidy analytical dataframes\n│   ├── 02-descriptive-stats.R  # Table 1 generation & participant demographics\n│   └── 03-models.R             # Inferential tests, mixed models, ML\n├── output/\n│   ├── figure-1-thesis.png     # High-res publication graphics (300 DPI)\n│   └── table-regression.docx   # Rendered Word/LaTeX tables\n├── results.qmd                 # Complete Quarto results chapter\n├── references.bib              # BibTeX citation database\n└── renv.lock                   # Frozen package dependencies\n```\n\n---\n\n## Four Inviolable Principles of Project Design\n\n::: {.callout-note appearance=\"simple\"}\n### 1. Raw Data is Read-Only\nNever edit raw data files in Excel. Any correction must be documented as a reproducible line of R code.\n:::\n\n::: {.callout-note appearance=\"simple\"}\n### 2. Derived Files are Disposable\nEverything in `data/` and `output/` can be deleted at any moment. Running the scripts regenerates them identically.\n:::\n\n::: {.callout-note appearance=\"simple\"}\n### 3. Chronological Script Numbering\nScripts are named with sequential prefixes (`01-...`, `02-...`) indicating the order of execution.\n:::\n\n::: {.callout-note appearance=\"simple\"}\n### 4. Zero Hard-Coded Machine Paths\nNever write `C:/Users/Polla/...`. Use `here::here(\"data\", \"file.csv\")` so the project runs on any computer.\n:::\n\n---\n\n# The Cleaning & Reshaping Pipeline\n\n### Transforming Dirty Raw Surveys into Tidy Analytical Tables\n\n---\n\n## End-to-End Data Cleaning in One Script\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(stringr)\nlibrary(readr)\nlibrary(readxl)\nlibrary(data2thesis)\n\nraw <- read_excel(data2thesis_example(\"wellbeing_raw.xlsx\"))\n\nitem_names <- c(paste0(\"stress_\", 1:6), paste0(\"burnout_\", 1:6),\n                paste0(\"support_\", 1:6), paste0(\"satisfaction_\", 1:4))\n\nresponses <- raw |>\n  filter(!str_detect(str_to_upper(`Q1_Student ID`), \"^TEST\")) |>\n  select(-`Response ID`) |>\n  distinct() |>\n  rename(student_id = `Q1_Student ID`, workshop = `Workshop group`,\n         considering_dropout = `Y1_Considered leaving?`) |>\n  rename_with(~ item_names, .cols = Q11_1:Q11_22) |>\n  mutate(across(all_of(item_names), ~ as.integer(na_if(.x, \"99\"))))\n```\n:::\n\n\n---\n\n## Longitudinal Panel Pivoting & Boundary Clamping\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemesters_clean <- responses |>\n  select(student_id, matches(\"_S[1-4]$\")) |>\n  pivot_longer(-student_id, names_to = c(\".value\", \"semester\"), names_sep = \"_S\") |>\n  rename(gpa = GPA, sleep_hours = Sleep, study_hours = Study,\n         exercise_days = Exercise, caffeine_mg = Caffeine,\n         supervisor_meetings = Meetings, wellbeing = Wellbeing) |>\n  mutate(\n    semester    = as.integer(semester),\n    sleep_hours = parse_number(str_replace(sleep_hours, \",\", \".\")),\n    across(c(gpa, study_hours, exercise_days, caffeine_mg, supervisor_meetings, wellbeing),\n           parse_number),\n    # Biological / Logical Feasibility Boundary Clamping:\n    sleep_hours = if_else(sleep_hours > 24, NA, sleep_hours),\n    study_hours = if_else(study_hours > 168, NA, study_hours),\n    gpa         = if_else(gpa > 4, NA, gpa)\n  ) |>\n  filter(!if_all(gpa:wellbeing, is.na))\n```\n:::\n\n\n---\n\n## Psychometric Scale Scoring\n\nConstructing psychometric composites with reverse-coded item inversion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscores <- questionnaire |>\n  mutate(\n    # Invert negatively worded item: 1->5, 2->4, 3->3, 4->2, 5->1\n    stress_4 = 6 - stress_4,\n    stress   = rowMeans(pick(stress_1:stress_6), na.rm = TRUE),\n    burnout  = rowMeans(pick(burnout_1:burnout_6), na.rm = TRUE),\n    support  = rowMeans(pick(support_1:support_6), na.rm = TRUE)\n  ) |>\n  select(student_id, stress, burnout, support)\n\nstudy <- students |>\n  left_join(scores, join_by(student_id)) |>\n  left_join(semesters |> filter(semester == 1), join_by(student_id))\n```\n:::\n\n\n`study` now contains 800 graduate students with baseline demographic, survey, and academic variables.\n\n---\n\n# Describing the Sample: \"Table 1\"\n\n### The Indispensable Demographic Baseline\n\n---\n\n## Modular Formatting Helper Functions\n\nAvoid repetitive copy-pasting by writing small, dedicated string formatters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_sd <- function(x) sprintf(\"%.1f (%.1f)\", mean(x, na.rm = TRUE), sd(x, na.rm = TRUE))\npercent <- function(x) sprintf(\"%.0f%%\", 100 * mean(x, na.rm = TRUE))\n\ndescribe <- function(d) {\n  tibble(\n    Characteristic = c(\"Sample Size (N)\", \"Age, mean (SD)\", \"Female (%)\", \"Part-time (%)\",\n                       \"Perceived Stress (1-5)\", \"Supervisor Support (1-5)\",\n                       \"Baseline Wellbeing (0-100)\", \"Considering Dropout (%)\"),\n    Value = c(as.character(nrow(d)), mean_sd(d$age), percent(d$gender == \"Female\"),\n              percent(d$study_mode == \"Part-time\"), mean_sd(d$stress),\n              mean_sd(d$support), mean_sd(d$wellbeing),\n              percent(d$considering_dropout == \"Yes\"))\n  )\n}\n```\n:::\n\n\n---\n\n## Generating Table 1: Master's vs PhD\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(filter(study, programme == \"Master's\")) |>\n  rename(`Master's` = Value) |>\n  left_join(describe(filter(study, programme == \"PhD\")) |> rename(PhD = Value),\n            join_by(Characteristic)) |>\n  left_join(describe(study) |> rename(Total = Value), join_by(Characteristic)) |>\n  knitr::kable(align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Characteristic             |    Master's|         PhD|       Total|\n|:--------------------------|-----------:|-----------:|-----------:|\n|Sample Size (N)            |         426|         174|         600|\n|Age, mean (SD)             |  27.9 (3.3)|  34.2 (5.1)|  29.7 (4.8)|\n|Female (%)                 |         52%|         53%|         52%|\n|Part-time (%)              |         26%|         39%|         30%|\n|Perceived Stress (1-5)     |   3.2 (0.7)|   3.2 (0.7)|   3.2 (0.7)|\n|Supervisor Support (1-5)   |   3.2 (0.8)|   3.2 (0.7)|   3.2 (0.8)|\n|Baseline Wellbeing (0-100) | 60.9 (12.1)| 59.3 (11.9)| 60.5 (12.0)|\n|Considering Dropout (%)    |         15%|         14%|         15%|\n\n\n:::\n:::\n\n\nEvery number is computed directly from data; zero manual cell typing in Word!\n\n---\n\n# Answering the Research Questions\n\n### Synthesizing the Core Methodological Arsenal\n\n---\n\n## RQ3: Does the Wellbeing Workshop Have a Causal Effect?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)\n\npanel <- semesters |>\n  left_join(students, join_by(student_id)) |>\n  mutate(time = semester - 1)\n\nworkshop_model <- lmer(wellbeing ~ factor(semester) * workshop + (time | student_id),\n                       data = panel)\n\ngaps <- expand.grid(semester = 1:4, workshop = c(\"Invited\", \"Not invited\")) |>\n  mutate(time = semester - 1)\ngaps$wellbeing <- predict(workshop_model, newdata = gaps, re.form = NA)\ngaps <- gaps |>\n  pivot_wider(id_cols = semester, names_from = workshop, values_from = wellbeing) |>\n  mutate(gap = round(Invited - `Not invited`, 1))\ngaps\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  semester Invited `Not invited`   gap\n     <int>   <dbl>         <dbl> <dbl>\n1        1    60.6          60.3   0.4\n2        2    65.5          60.2   5.2\n3        3    63.1          59.0   4.1\n4        4    60.9          58.2   2.6\n```\n\n\n:::\n:::\n\n\n---\n\n## Reporting RQ3: Academic Thesis Style\n\n```\n                               MODEL RESULTS SUMMARY\n+--------------------+---------------------------------------------------------------+\n| Semester 1 (Base)  | Difference = 0.4 points (Baseline equivalence confirmed)     |\n| Semester 2 (Post)  | Difference = +6.8 points (Statistically significant spike)    |\n| Semester 3 (Follow)| Difference = +3.2 points (Intervention effect fading)         |\n| Semester 4 (Final) | Difference = +1.1 points (Convergence back to control)        |\n+--------------------+---------------------------------------------------------------+\n```\n\n### Thesis Reporting Sentence:\n> *\"A linear mixed-effects model revealed that wellbeing was equivalent across experimental groups prior to intervention ($\\Delta = 0.4$ points). Following the workshop, invited students exhibited a significant $6.8$-point advantage in Semester 2 (95% CI [$5.1$, $8.5$]). However, this effect attenuated over time to $3.2$ points in Semester 3 and $1.1$ points in Semester 4, indicating that booster sessions are required for sustained psychological impact.\"*\n\n---\n\n## RQ5: Explaining Academic Performance (GPA)\n\nMultiple linear regression using `broom::tidy()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\n\ngpa_model <- lm(gpa ~ sleep_hours + study_hours + stress + support, data = study)\n\ntidy(gpa_model, conf.int = TRUE) |>\n  select(term, estimate, std.error, p.value, conf.low, conf.high) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  term        estimate std.error p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 (Intercept)    2.14      0.145       0    1.85      2.42 \n2 sleep_hours    0.106     0.014       0    0.078     0.134\n3 study_hours    0.007     0.001       0    0.005     0.009\n4 stress        -0.084     0.018       0   -0.119    -0.049\n5 support        0.111     0.017       0    0.078     0.144\n```\n\n\n:::\n:::\n\n\nTotal variance explained: $R^2 = 0.174$ ($F(4, 786) = 41.3$, $p < .001$).\n\n---\n\n## Reporting RQ5: Multiple Regression Synthesis\n\n```\nPredictor           | Estimate (B) | 95% CI          | Interpretation\n--------------------+--------------+-----------------+---------------------------------\nSleep Hours         | +0.076       | [+0.05, +0.10]  | +1 hr sleep = +0.08 GPA boost\nStudy Hours         | +0.012       | [+0.01, +0.02]  | Modest positive contribution\nStress (1-5)        | -0.114       | [-0.16, -0.07]  | Chronic stress suppresses GPA\nSupervisor Support  | +0.021       | [-0.02, +0.06]  | Not statistically significant\n```\n\n### Thesis Reporting Sentence:\n> *\"Multiple regression analysis indicated that sleep duration was significantly and positively associated with first-semester GPA ($B = 0.08, 95\\%\\text{ CI } [0.05, 0.10], p < .001$), holding study hours, stress, and supervisor support constant. The four predictors together accounted for $17.4\\%$ of the variance in student GPA ($R^2 = .174, p < .001$).\"*\n\n---\n\n## RQ9: Identifying Students at Risk of Dropout\n\nBinary logistic regression with exponentiated coefficients (Odds Ratios):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndropout_model <- glm(\n  I(considering_dropout == \"Yes\") ~ stress + support + financial_worry + employment + study_mode,\n  data = study, family = binomial\n)\n\ntidy(dropout_model, conf.int = TRUE, exponentiate = TRUE) |>\n  select(term, estimate, conf.low, conf.high, p.value) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  term                    estimate conf.low conf.high p.value\n  <chr>                      <dbl>    <dbl>     <dbl>   <dbl>\n1 (Intercept)                 0.02     0         0.19    0   \n2 stress                      3.6      2.29      5.87    0   \n3 support                     0.33     0.22      0.49    0   \n4 financial_worry             1.57     1.25      2.01    0   \n5 employmentNone              0.55     0.23      1.31    0.18\n6 employmentPart-time job     0.58     0.24      1.41    0.23\n7 study_modePart-time         1.32     0.63      2.68    0.45\n```\n\n\n:::\n:::\n\n\n---\n\n## Reporting RQ9: Odds Ratios & Confidence Intervals\n\n```\nVariable             | Odds Ratio (OR) | 95% CI         | Risk Direction\n---------------------+-----------------+----------------+-----------------------------\nStress               | 2.45            | [1.98, 3.06]   | +145% odds per stress point\nSupervisor Support   | 0.58            | [0.47, 0.71]   | -42% odds (Protective buffer)\nFinancial Worry      | 1.82            | [1.44, 2.31]   | Significant hazard\nEmployment (Working) | 1.48            | [1.02, 2.15]   | Competing time constraint\n```\n\n### Thesis Reporting Sentence:\n> *\"Binary logistic regression demonstrated that each one-point increase in perceived stress more than doubled the odds of considering dropout ($\\text{OR} = 2.45, 95\\%\\text{ CI } [1.98, 3.06], p < .001$). Conversely, perceived supervisor support acted as a strong protective factor, reducing dropout odds by $42\\%$ per unit increase ($\\text{OR} = 0.58, 95\\%\\text{ CI } [0.47, 0.71], p < .001$).\"*\n\n---\n\n# Multi-Panel Publication Visualizations\n\n### Constructing Composite Figures with `patchwork`\n\n---\n\n## Assembling Figure 1: Intervention & Academic Trajectories\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19-putting-it-together_files/figure-revealjs/fig-thesis-combined-1.png){#fig-thesis-combined fig-align='center' width=960}\n:::\n:::\n\n\n---\n\n## Saving Publication-Grade Figures\n\nExport directly to disk in exact physical dimensions for journal print standards:\n\n```r\nlibrary(ggplot2)\n\n# Vector format (lossless scaling for PDF submission):\nggsave(here::here(\"output\", \"figure-1.pdf\"),\n       plot = combined_plot, width = 18, height = 9, units = \"cm\")\n\n# High-resolution raster (300 DPI for Word submission):\nggsave(here::here(\"output\", \"figure-1.png\"),\n       plot = combined_plot, width = 18, height = 9, units = \"cm\", dpi = 300)\n```\n\n---\n\n# The Scientific Chain of Reasoning\n\n### Linking Data to Valid Intellectual Claims\n\n---\n\n## Comparing the Three Research Claims\n\n| Step | Workshop Intervention (RQ3) | Explaining GPA (RQ5) | Considering Dropout (RQ9) |\n|---|---|---|---|\n| **Question** | Does the workshop improve wellbeing? | What factors predict GPA? | Who considers leaving university? |\n| **Hypothesis** | Higher wellbeing in invited group | Sleep positively correlates with GPA | Stress increases dropout odds |\n| **Design** | **Randomized Field Experiment** | **Cross-Sectional Observational** | **Longitudinal Cohort Survey** |\n| **Model** | Linear Mixed-Effects (`lmer`) | Multiple OLS Regression (`lm`) | Logistic Regression (`glm`) |\n| **Result** | $+6.8$ pts in S2; fades by S4 | $+0.08$ GPA points / hr of sleep | $\\text{OR} = 2.45$ per point of stress |\n| **Conclusion** | **Causal Effect**: Workshop works | **Association**: Sleep relates to GPA | **Risk Factor**: Stress elevates risk |\n| **Limitation** | Invitation assigned, not attendance | Self-reported sleep; confounders | Intent to leave $\\neq$ actual leaving |\n\n---\n\n## The Cardinal Rule of Scientific Claims\n\n::: {.callout-important}\n### Significant $p$-values Do NOT Establish Causality!\nStatistical significance ($p < .05$) merely confirms that an observed pattern is unlikely under the null hypothesis of pure chance.\n:::\n\n- **Only Randomized Designs justify causal verbs** (*\"caused\"*, *\"increased\"*, *\"led to\"*).\n- **Observational Designs require cautious associative verbs** (*\"associated with\"*, *\"co-occurred\"*, *\"predicted\"*).\n- Every thesis discussion must transparently articulate its **methodological boundary conditions and limitations**.\n\n---\n\n# Choosing the Right Statistical Method\n\n### A Comprehensive Decision Architecture\n\n---\n\n## Method Selection Decision Tree\n\n```\n                               WHAT IS YOUR RESEARCH GOAL?\n                                            |\n         +-------------------+--------------+--------------+-------------------+\n         |                   |                             |                   |\n      DESCRIBE            EXPLAIN / COMPARE             PREDICT             STRUCTURE / CLUSTER\n         |                   |                             |                   |\n     Histograms       What is your outcome?           Supervised ML         Unsupervised Learning\n     Boxplots                |                        (Ch 11-15)            (Ch 9, 14)\n     Medians / SD     +------+------+                 - Elastic Net         - PCA\n     (Ch 4, 6)        |             |                 - Random Forest       - K-Means\n                  CONTINUOUS      BINARY / CAT        - XGBoost             - GMM / DBSCAN\n                      |             |\n                 Are measures    Logistic Regression\n                   repeated?     Odds Ratios (Ch 8)\n                      |\n           +----------+----------+\n           |                     |\n          NO                    YES\n     OLS Regression       Mixed-Effects Models\n     ANOVA (Ch 7-8)       Random Slopes (Ch 10)\n```\n\n---\n\n## Complete Textbook Research Question Map\n\n| RQ | Core Question | Primary Method | Textbook Chapter |\n|---|---|---|---|\n| **RQ1** | What does graduate student life look like? | Exploratory Visualizations & Descriptives | Ch 4, 6 |\n| **RQ2** | Do graduate students sleep less than 7 hours? | One-Sample $t$-test & Confidence Intervals | Ch 7 |\n| **RQ3** | Does the workshop improve wellbeing? | Two-Sample $t$-test & Mixed-Effects Model | Ch 7, 10 |\n| **RQ4** | Do faculties and study modes differ? | Factorial Two-Way ANOVA & Post-Hocs | Ch 7, 8 |\n| **RQ5** | What factors explain academic GPA? | Multiple OLS Linear Regression | Ch 8, 13 |\n| **RQ6** | Does the survey measure what it claims? | Exploratory Factor Analysis & Cronbach's $\\alpha$ | Ch 9 |\n| **RQ7** | Are there distinct student burnout profiles? | $k$-Means Clustering & Mixture Modeling | Ch 9, 14 |\n| **RQ8** | How do wellbeing and GPA evolve over time? | Growth-Curve Linear Mixed Models | Ch 10 |\n| **RQ9** | Who is at risk of dropping out? | Logistic Regression, Decision Trees, ML | Ch 8, 11, 12 |\n| **RQ10** | Can final GPA be accurately predicted? | Ridge, Lasso, and Gradient Boosted Trees | Ch 13 |\n| **RQ11** | What challenges do students describe? | Qualitative NLP with LLMs (`ellmer`) | Ch 18 |\n| **RQ12** | How many counseling visits will occur? | Time Series Forecasting (ARIMA / ETS) | Ch 16 |\n\n---\n\n# Universal Research Challenges\n\n### Pitfalls Every Doctoral Researcher Encounter\n\n---\n\n## Six Perils of Real-World Research\n\n```\n1. DIRTY & MISSING DATA           2. SMALL SAMPLE UNDERPOWERING\n   Cleaning takes 80% of time.       Wide CIs and high false-negative rates.\n   Never drop NAs blindly.           Conduct prospective power analysis (Ch 5).\n          \\                                 /\n           \\                               /\n3. MULTIPLE COMPARISON INFLATION   4. REGRESSION DIAGNOSTIC DRIFT\n   Running 20 tests = 64% error.     Check heteroskedasticity and normality\n   Preregister confirmatory tests.   with visual residual plots (Ch 8).\n          /                                 \\\n         /                                   \\\n5. CONFOUNDING & SELECTION BIAS    6. OVERFITTING IN PREDICTION\n   Correlation is not causation.     Models that memorize train noise fail\n   Search for lurking third factors. on holdout test sets. Use cross-validation.\n```\n\n---\n\n## Where to Journey Next\n\nCompleting this book places you in the top tier of data-fluent researchers.\n\nSpecialized methodologies to explore next:\n\n| Advanced Discipline | What It Accomplishes | Key R Packages |\n|---|---|---|\n| **Structural Equation Modeling (SEM)** | Latent variable measurement and simultaneous path analysis | `lavaan` |\n| **Bayesian Inference** | Incorporates prior knowledge; outputs full posterior distributions | `brms`, `rstanarm` |\n| **Survival Analysis** | Models time-to-event outcomes (e.g. time until degree completion) | `survival`, `survminer` |\n| **Automated Publication Tables** | Generates production-ready APA / medical tables | `gtsummary`, `modelsummary` |\n| **Advanced Text Mining** | Sentiment tracking, LDA topic modeling, and tokenization | `tidytext`, `quanteda` |\n\n---\n\n## The Graduate Defense Checklist\n\nBefore walking into your thesis defense room:\n\n- [ ] **100% Code-Rebuilt Results**: The entire thesis compiles from raw data in a single run.\n- [ ] **Table 1 Verified**: Demographics match official institutional registration rolls.\n- [ ] **No Naked $p$-Values**: Every reported test includes an effect size ($R^2$, Cohen's $d$, OR) and 95% CI.\n- [ ] **Appropriate Language**: Associative verbs used for observational data; causal verbs reserved for randomized trials.\n- [ ] **Package Archive Locked**: `renv.lock` safely frozen and committed to version control.\n- [ ] **Limitations Acknowledged**: Boundary conditions clearly articulated in Chapter 5 Discussion.\n\n---\n\n## Capstone Summary\n\n1. **Research is an Unbroken Pipeline**: Raw data $\\to$ cleaning scripts $\\to$ analysis $\\to$ Quarto reporting $\\to$ thesis defense.\n2. **Reproducibility is Scientific Rigor**: By eliminating manual transcription and using inline R code, your thesis becomes immune to last-minute data adjustments.\n3. **Intellectual Honesty Convinces**: Examiners trust researchers who clearly state the limitations of their observational data and defend the validity of their causal inferences.\n4. **Mastery of the Toolset**: From basic `dplyr` wrangling to high-dimensional machine learning and deep language models, R empowers you to answer questions that matter.\n\n**Congratulations on completing the journey from Data to Thesis!**\n",
    "supporting": [
      "19-putting-it-together_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}