{
  "hash": "7be62187ea363423cf93180be3472473",
  "result": {
    "engine": "knitr",
    "markdown": "---\nnumber-offset: 2\n---\n\n# Data Manipulation {#sec-ch03}\n\n\n\nRaw data is never ready for analysis. Survey tools record test responses alongside real ones, participants submit the same form twice, one person types \"female\" and another \"F\", missing answers are stored as `99`, and a slip of the finger turns an age of 25 into 250. None of this is unusual, and none of it is harmless: a single `99` among answers from 1 to 5 can shift an average noticeably, and a duplicated row counts one participant twice. Preparing data for analysis, usually called **data cleaning**, often takes longer than the analysis itself, and its decisions shape every result that follows.\n\nCleaning is therefore part of the analysis, not a chore before it, and it deserves the same care. This chapter first sets out what clean data means and the principles that guide cleaning decisions. It then introduces the tools for working with tables in R: choosing cases and variables, creating new variables, summarising by group, reshaping, and combining tables. Finally, it applies them, step by step, to the raw export of the wellbeing survey that Chapter 2 opened: the file with test responses, duplicated rows, the same answer spelled four ways, ages stored as text, and missing values coded as `99`.\n\n::: {.callout-tip appearance=\"simple\"}\n## By the end of this chapter you will be able to\n\n- Explain what clean data means, and why every cleaning decision must be recorded.\n- Explain what tidy data is, and recognise data that is not tidy.\n- Chain steps together with the pipe `|>`.\n- Choose cases and variables, sort, create new variables, and summarise, overall and by group.\n- Reshape data between wide and long formats, and join tables that share an identifier.\n- Clean a real survey export: remove test and duplicate rows, rename variables, fix inconsistent categories, convert text to numbers, and handle missing codes and impossible values.\n- Compute questionnaire scale scores, including reversed items, and report the cleaning in a thesis.\n:::\n::: {.callout-note appearance=\"simple\" icon=\"false\"}\n**Teaching & Practice:** [Interactive Lecture Slides](../slides/03-data-manipulation.html) · [Browser Playground Exercises](../playground/chapter03.html)\n:::\n\n\n## What clean data means\n\nData is clean when it can be trusted to represent what was measured. That broad idea can be broken into five qualities, each of which the survey export fails in some way. Clean data is **valid**: every value is possible for its variable, so there are no ages of 250 or 26 hours of sleep a night. It is **accurate**: values record what the participant actually meant, so a missing-answer code is not mistaken for a real answer. It is **complete** as far as possible, and where values are missing, they are marked as missing rather than hidden behind codes. It is **consistent**: the same answer is always recorded in the same way, so \"F\", \"female\", and \"Female\" become one category. And it is **unique**: each case appears exactly once, with no test entries and no duplicates.\n\nEach failure distorts results in a different way. A missing-answer code that stays in the data is the easiest to see. Suppose five students answered a question on a 1-to-5 scale, and one of them skipped it, which the survey tool recorded as `99`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nanswers <- c(4, 3, 5, 99, 2)\nmean(answers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.6\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(na_if(answers, 99), na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.5\n```\n\n\n:::\n:::\n\n\nWith the code left in, the average is 22.6, a value that is impossible on a 1-to-5 scale. Marked as missing with `na_if()`, the code drops out, and the average of the four real answers is 3.5. In a real dataset the distortion is usually smaller and therefore harder to notice, which is exactly what makes it dangerous. Duplicates work in a similar way, but on the sample size and the balance of the sample: a participant who appears twice counts twice.\n\nThree principles follow for every cleaning decision. The **raw file is never edited**; it stays exactly as it was received, and all changes are made by code that starts from it. **Every decision is recorded**, in the script and, where it affects the results, in the thesis: how many cases were removed and why, which values were set to missing, how scale scores were built. And **the result is checked after every step**, because many cleaning mistakes produce no error message at all. The final section of this chapter shows how to report the cleaning in a thesis.\n\n## Tidy data\n\nClean data should also be arranged in a way that makes analysis straightforward. The arrangement used throughout this book is called **tidy data** [@wickham2014tidy]. In tidy data, each variable forms a column, each observation forms a row, and each value sits in its own cell. The idea is easiest to see in a small example. @tbl-untidy stores two semesters of wellbeing for three students side by side, as a spreadsheet often would.\n\n| student | wellbeing_s1 | wellbeing_s2 |\n|---|---|---|\n| S1 | 58 | 63 |\n| S2 | 71 | 70 |\n| S3 | 64 | 69 |\n\n: Wellbeing in wide format: one variable, wellbeing, is spread over two columns {#tbl-untidy}\n\nThe table looks neat, but one variable, wellbeing, is spread over two columns, and a second variable, the semester, is hidden inside the column names. @tbl-tidy holds the same six measurements in tidy form.\n\n| student | semester | wellbeing |\n|---|---|---|\n| S1 | 1 | 58 |\n| S1 | 2 | 63 |\n| S2 | 1 | 71 |\n| S2 | 2 | 70 |\n| S3 | 1 | 64 |\n| S3 | 2 | 69 |\n\n: The same data in tidy (long) format: one column per variable, one row per observation {#tbl-tidy}\n\nNow each of the three variables has its own column, and each row is one observation: one student in one semester. Questions such as \"average wellbeing in each semester\" become a simple grouped summary. The `students` table in the package is tidy, with one row per student and one column per variable. The survey export is not: it squeezes four semesters of measurements side by side into one row per student. Much of cleaning consists of making data tidy, because once it is tidy, every tool in this chapter works on it.\n\n## The tidyverse\n\nThe tools in this chapter come from the **tidyverse**, a collection of packages that share one way of working and are designed for tidy data. This chapter uses four of them: **dplyr** for working with rows and columns, **tidyr** for reshaping data, **stringr** for working with text, and **readr** for turning text into numbers (and for reading and writing files). The whole collection can be installed at once with `install.packages(\"tidyverse\")` and loaded with `library(tidyverse)`, but this book loads only the packages each chapter needs:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(stringr)\nlibrary(readr)\n```\n:::\n\n\n### Chaining steps with the pipe\n\nAnalysis is a series of steps: take the data, keep some rows, calculate something, round the result. In Chapter 1, such steps were written by putting functions inside each other:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep <- c(6.5, 7, 5.5, 8, 6)\nround(mean(sleep), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.6\n```\n\n\n:::\n:::\n\n\nThis reads from the inside out, which gets hard to follow as the steps multiply. The **pipe**, written `|>`, writes the steps in the order they happen. It takes the result on its left and passes it as the first argument to the function on its right:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep |> mean() |> round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.6\n```\n\n\n:::\n:::\n\n\nThe pipe reads as \"and then\": take `sleep`, *and then* take the mean, *and then* round it to one decimal place. In RStudio, **Ctrl+Shift+M** (**Cmd+Shift+M** on a Mac) types the pipe for you.\n\n::: {.callout-note}\n## The older pipe\n\nBefore R had its own pipe, the tidyverse used `%>%`, from the magrittr package. You will see it in many tutorials and older scripts. For everything in this book, it does the same job as `|>`.\n:::\n\n## Working with cases and variables\n\nThe dplyr package provides a small set of **verbs**, each doing one job. Every verb takes a data frame first and returns a data frame, so verbs can be chained with the pipe. The verbs are easiest to understand on a tiny table. The function `tibble()` builds one; a **tibble** is the tidyverse's version of a data frame, which prints more neatly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot <- tibble(\n  student = c(\"S1\", \"S2\", \"S3\", \"S4\", \"S5\"),\n  faculty = c(\"Education\", \"Humanities\", \"Education\", \"Health Sciences\", \"Humanities\"),\n  sleep   = c(6.5, 7.5, 5.5, 8, 6),\n  stress  = c(3.2, 2.1, 4.5, 1.8, 3.9)\n)\npilot\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  student faculty         sleep stress\n  <chr>   <chr>           <dbl>  <dbl>\n1 S1      Education         6.5    3.2\n2 S2      Humanities        7.5    2.1\n3 S3      Education         5.5    4.5\n4 S4      Health Sciences   8      1.8\n5 S5      Humanities        6      3.9\n```\n\n\n:::\n:::\n\n\n### Choosing the cases you need\n\nMost analyses use only some of the cases: the students of one faculty, the first semester, the participants who completed the study. The verb `filter()` keeps the rows that meet a condition:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> filter(sleep < 7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  student faculty    sleep stress\n  <chr>   <chr>      <dbl>  <dbl>\n1 S1      Education    6.5    3.2\n2 S3      Education    5.5    4.5\n3 S5      Humanities   6      3.9\n```\n\n\n:::\n:::\n\n\nSeveral conditions separated by commas must all be true:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> filter(sleep < 7, faculty == \"Education\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  student faculty   sleep stress\n  <chr>   <chr>     <dbl>  <dbl>\n1 S1      Education   6.5    3.2\n2 S3      Education   5.5    4.5\n```\n\n\n:::\n:::\n\n\nTo keep rows matching any of several values, use `%in%`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> filter(faculty %in% c(\"Education\", \"Humanities\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  student faculty    sleep stress\n  <chr>   <chr>      <dbl>  <dbl>\n1 S1      Education    6.5    3.2\n2 S2      Humanities   7.5    2.1\n3 S3      Education    5.5    4.5\n4 S5      Humanities   6      3.9\n```\n\n\n:::\n:::\n\n\nEvery filter is a decision about the sample, and should be reported: an analysis of \"students who completed all four semesters\" answers a different question from an analysis of all students.\n\n### Choosing variables\n\nLarge datasets have far more variables than any one analysis needs. The verb `select()` keeps the columns you name, in the order you name them, and a minus sign drops a column instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> select(student, sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  student sleep\n  <chr>   <dbl>\n1 S1        6.5\n2 S2        7.5\n3 S3        5.5\n4 S4        8  \n5 S5        6  \n```\n\n\n:::\n\n```{.r .cell-code}\npilot |> select(-faculty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  student sleep stress\n  <chr>   <dbl>  <dbl>\n1 S1        6.5    3.2\n2 S2        7.5    2.1\n3 S3        5.5    4.5\n4 S4        8      1.8\n5 S5        6      3.9\n```\n\n\n:::\n:::\n\n\n### Sorting cases\n\nSorting helps when looking at data, for example to see the most extreme values first. The verb `arrange()` sorts rows by one or more columns, and `desc()` sorts from largest to smallest:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> arrange(desc(stress))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  student faculty         sleep stress\n  <chr>   <chr>           <dbl>  <dbl>\n1 S3      Education         5.5    4.5\n2 S5      Humanities        6      3.9\n3 S1      Education         6.5    3.2\n4 S2      Humanities        7.5    2.1\n5 S4      Health Sciences   8      1.8\n```\n\n\n:::\n:::\n\n\n### Creating new variables\n\nMany variables used in analysis are calculated from others: a total score, a conversion to other units, a category derived from a number. The verb `mutate()` adds new columns calculated from existing ones, or changes existing ones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> mutate(\n  sleep_minutes = sleep * 60,\n  short_sleep   = sleep < 7\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  student faculty         sleep stress sleep_minutes short_sleep\n  <chr>   <chr>           <dbl>  <dbl>         <dbl> <lgl>      \n1 S1      Education         6.5    3.2           390 TRUE       \n2 S2      Humanities        7.5    2.1           450 FALSE      \n3 S3      Education         5.5    4.5           330 TRUE       \n4 S4      Health Sciences   8      1.8           480 FALSE      \n5 S5      Humanities        6      3.9           360 TRUE       \n```\n\n\n:::\n:::\n\n\nTo sort values into categories, `case_when()` checks conditions in order and uses the first one that is true, and `.default` catches everything else:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> mutate(\n  stress_level = case_when(\n    stress >= 4 ~ \"High\",\n    stress >= 2.5 ~ \"Medium\",\n    .default = \"Low\"\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  student faculty         sleep stress stress_level\n  <chr>   <chr>           <dbl>  <dbl> <chr>       \n1 S1      Education         6.5    3.2 Medium      \n2 S2      Humanities        7.5    2.1 Low         \n3 S3      Education         5.5    4.5 High        \n4 S4      Health Sciences   8      1.8 Low         \n5 S5      Humanities        6      3.9 Medium      \n```\n\n\n:::\n:::\n\n\nTurning a number into categories in this way loses information, since a stress score of 3.9 and one of 2.6 become the same \"Medium\". It is useful for description, but analyses should normally keep the original number.\n\n### Summarising, overall and by group\n\nSummaries reduce many values to a few numbers. The verb `summarise()` reduces a table to one row of summaries, and `n()` counts the rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> summarise(\n  mean_sleep = mean(sleep),\n  students   = n()\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  mean_sleep students\n       <dbl>    <int>\n1        6.7        5\n```\n\n\n:::\n:::\n\n\nThe real power comes with groups. The `.by` argument calculates the summary separately for each group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> summarise(\n  mean_sleep = mean(sleep),\n  students   = n(),\n  .by = faculty\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  faculty         mean_sleep students\n  <chr>                <dbl>    <int>\n1 Education             6           2\n2 Humanities            6.75        2\n3 Health Sciences       8           1\n```\n\n\n:::\n:::\n\n\nFor simple counts, `count()` is a shortcut:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npilot |> count(faculty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  faculty             n\n  <chr>           <int>\n1 Education           2\n2 Health Sciences     1\n3 Humanities          2\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Grouping in older code\n\nIn many tutorials you will see `group_by(faculty) |> summarise(...)` instead of the `.by` argument. Both give the same result. The `.by` argument is newer and keeps each step self-contained, so this book uses it.\n:::\n\n### Combining the steps\n\nEach verb is simple, but chained together they answer real questions. One such question concerns how average wellbeing changed over the four semesters, separately for students who were and were not invited to the workshop. The semester records are in `semesters`, and the workshop group is in `students`, so the workshop group is first added to the semester records. (The `left_join()` in the first line is explained in @sec-joins.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemesters |>\n  left_join(students |> select(student_id, workshop), join_by(student_id)) |>\n  summarise(\n    mean_wellbeing = mean(wellbeing),\n    students       = n(),\n    .by = c(semester, workshop)\n  ) |>\n  arrange(semester, workshop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  semester    workshop mean_wellbeing students\n1        1     Invited       60.64667      300\n2        1 Not invited       60.26667      300\n3        2     Invited       65.47000      300\n4        2 Not invited       60.22000      300\n5        3     Invited       63.22261      283\n6        3 Not invited       59.22857      280\n7        4     Invited       60.93286      283\n8        4 Not invited       58.42500      280\n```\n\n\n:::\n:::\n\n\nRead aloud, the code says: take the semester records, *and then* add each student's workshop group, *and then* calculate the average wellbeing and the number of students for each semester and workshop group, *and then* sort the result. In semester 1, before the workshop, the two groups are almost level. From semester 2, the invited students are ahead. Chapter 7 tests whether that difference is larger than chance.\n\nThe number of students also drops in semesters 3 and 4. Some students left the study, which is worth remembering: it returns later in this chapter and in Chapter 6.\n\n## Reshaping between wide and long\n\nThe same data can be laid out in two ways, as the section on tidy data showed. In **wide** format, repeated measurements sit side by side, one column per occasion. In **long** format, each measurement has its own row. Here is the wide table from @tbl-untidy in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwide <- tibble(\n  student     = c(\"S1\", \"S2\", \"S3\"),\n  wellbeing_1 = c(58, 71, 64),\n  wellbeing_2 = c(63, 70, 69)\n)\nwide\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  student wellbeing_1 wellbeing_2\n  <chr>         <dbl>       <dbl>\n1 S1               58          63\n2 S2               71          70\n3 S3               64          69\n```\n\n\n:::\n:::\n\n\nSpreadsheets and SPSS often use wide format. For analysis in R, long format is usually easier, because each variable (student, semester, wellbeing) is then one column. The function `pivot_longer()` turns wide into long:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong <- wide |>\n  pivot_longer(\n    cols         = c(wellbeing_1, wellbeing_2),\n    names_to     = \"semester\",\n    names_prefix = \"wellbeing_\",\n    values_to    = \"wellbeing\"\n  )\nlong\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  student semester wellbeing\n  <chr>   <chr>        <dbl>\n1 S1      1               58\n2 S1      2               63\n3 S2      1               71\n4 S2      2               70\n5 S3      1               64\n6 S3      2               69\n```\n\n\n:::\n:::\n\n\nThe arguments say which columns to stack (`cols`), where the old column names should go (`names_to`), which part of the names to drop (`names_prefix`), and where the values should go (`values_to`). The result is @tbl-tidy.\n\nThe opposite function, `pivot_wider()`, is especially useful for presenting results, because a wide table is easier to read:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |> pivot_wider(names_from = semester, values_from = wellbeing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  student   `1`   `2`\n  <chr>   <dbl> <dbl>\n1 S1         58    63\n2 S2         71    70\n3 S3         64    69\n```\n\n\n:::\n:::\n\n\nThe average wellbeing table from the previous section, for example, reads more easily with one column per workshop group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemesters |>\n  left_join(students |> select(student_id, workshop), join_by(student_id)) |>\n  summarise(mean_wellbeing = round(mean(wellbeing), 1), .by = c(semester, workshop)) |>\n  pivot_wider(names_from = workshop, values_from = mean_wellbeing)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  semester `Not invited` Invited\n     <int>         <dbl>   <dbl>\n1        1          60.3    60.6\n2        2          60.2    65.5\n3        3          59.2    63.2\n4        4          58.4    60.9\n```\n\n\n:::\n:::\n\n\n## Joining tables {#sec-joins}\n\nResearch data is often spread over several tables that share an identifier. The wellbeing study keeps students in one table, their semester records in another, and their supervisors in a third. **Joins** combine tables by matching the identifier. Two small tables show how:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeople <- tibble(\n  student = c(\"S1\", \"S2\", \"S3\"),\n  faculty = c(\"Education\", \"Humanities\", \"Education\")\n)\nscores <- tibble(\n  student = c(\"S1\", \"S1\", \"S2\", \"S4\"),\n  wellbeing = c(58, 63, 71, 66)\n)\n```\n:::\n\n\nThe function `left_join()` keeps every row of the first table and adds the matching information from the second:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscores |> left_join(people, join_by(student))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  student wellbeing faculty   \n  <chr>       <dbl> <chr>     \n1 S1             58 Education \n2 S1             63 Education \n3 S2             71 Humanities\n4 S4             66 <NA>      \n```\n\n\n:::\n:::\n\n\nThe argument `join_by(student)` names the column that links the two tables. Student `S4` has a score but no entry in `people`, so their faculty is `NA`.\n\nThe function `anti_join()` does the opposite: it keeps the rows of the first table that have *no* match in the second. It is the quickest way to find what is missing, here the students without any scores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeople |> anti_join(scores, join_by(student))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  student faculty  \n  <chr>   <chr>    \n1 S3      Education\n```\n\n\n:::\n:::\n\n\nOn the wellbeing data, joins answer questions that no single table can. Each student's supervisor has an academic rank, stored in `supervisors`, and a join brings it next to each student's answer about dropping out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby_rank <- students |>\n  left_join(supervisors |> select(supervisor_id, rank), join_by(supervisor_id)) |>\n  summarise(\n    considering_dropout = mean(considering_dropout == \"Yes\"),\n    students            = n(),\n    .by = rank\n  )\nby_rank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 rank considering_dropout students\n1            Lecturer           0.1367521      234\n2           Professor           0.1217391      115\n3 Assistant Professor           0.1752988      251\n```\n\n\n:::\n:::\n\n\nThe shares differ a little, from about 12% to about 18%. Differences this small could easily be chance; Chapter 7 shows how to test that. A second join finds the students who have no records for semester 3:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleft <- students |>\n  anti_join(semesters |> filter(semester == 3), join_by(student_id))\nnrow(left)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 37\n```\n\n\n:::\n\n```{.r .cell-code}\nleft |> count(considering_dropout)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  considering_dropout  n\n1                  No 15\n2                 Yes 22\n```\n\n\n:::\n:::\n\n\n\n\nIn all, 37 students have no semester 3 record: they left the study after the first year, and 22 of them had said they were considering dropping out. The students who left are not a random selection, which matters for any analysis of the later semesters. Chapter 6 returns to this.\n\n## Cleaning the survey export\n\nThe survey export can now be cleaned. The steps below are the ones needed for almost any survey data, and each is preceded by the problem it solves. Each step is short. What matters is doing them in a sensible order, and checking the result after each one.\n\n### Inspecting the export\n\nCleaning starts with looking, because problems that have not been seen cannot be fixed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nraw <- read_excel(data2thesis_example(\"wellbeing_raw.xlsx\"))\ndim(raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 615  64\n```\n\n\n:::\n:::\n\n\nThe file has 615 rows, although there are only 600 students. A few lines of code show what needs fixing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw |> count(Q3_Gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  Q3_Gender     n\n  <chr>     <int>\n1 F            28\n2 Female      233\n3 M            46\n4 Male        173\n5 female       56\n6 male         78\n7 <NA>          1\n```\n\n\n:::\n\n```{.r .cell-code}\nraw |> filter(str_detect(str_to_upper(`Q1_Student ID`), \"TEST\")) |> select(1:4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  `Response ID` `Q1_Student ID` Q2_Age Q3_Gender\n  <chr>         <chr>           <chr>  <chr>    \n1 R0001         TEST            99     Female   \n2 R0002         test            <NA>   <NA>     \n3 R0003         TEST2           30     Male     \n```\n\n\n:::\n:::\n\n\nGender is spelled six ways (`F`, `female`, `Female`, and so on), plus a blank from a test response, and there are test responses from when the survey was set up. (The raw file also contains `\"Female \"` with a trailing space; `read_excel()` removes such spaces automatically, but other import functions do not, which is why the cleaning below still uses `str_trim()`.) Column names such as `Q1_Student ID` contain spaces, so they must be written inside backticks (`` ` ``) in code. And as Chapter 2 showed, many numeric columns arrived as text.\n\n### Test responses and duplicates\n\nTest responses are not data about students, and duplicated submissions would count some students twice, so both must go before anything else. Test responses have a student ID starting with \"TEST\", in upper or lower case. The function `str_to_upper()` makes the case irrelevant, and `str_detect()` checks for the pattern. The function `distinct()` then removes rows that are exact copies of another row. The response ID is different for each submission, even for duplicates, so it is dropped first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses <- raw |>\n  filter(!str_detect(str_to_upper(`Q1_Student ID`), \"^TEST\")) |>\n  select(-`Response ID`) |>\n  distinct()\nnrow(responses)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 600\n```\n\n\n:::\n:::\n\n\n\n\nIn the pattern, `!` means \"not\" and `^` means \"at the start\". Exactly 600 rows are left: one per student.\n\n### Usable variable names\n\nNames such as `Q10_How worried are you about money? (1-5)` are awkward to type and easy to get wrong. Short, consistent names make the code readable and reduce errors. The function `rename()` changes names, new name first, and the 22 questionnaire items, `Q11_1` to `Q11_22`, are renamed in one go with `rename_with()`, using the scale each item belongs to:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nitem_names <- c(paste0(\"stress_\", 1:6), paste0(\"burnout_\", 1:6),\n                paste0(\"support_\", 1:6), paste0(\"satisfaction_\", 1:4))\n\nresponses <- responses |>\n  rename(\n    student_id          = `Q1_Student ID`,\n    age                 = Q2_Age,\n    gender              = Q3_Gender,\n    faculty             = Q4_Faculty,\n    programme           = Q5_Programme,\n    study_mode          = `Q6_Study mode`,\n    employment          = `Q7_Paid work`,\n    has_children        = Q8_Children,\n    lives_away          = `Q9_Moved away from family`,\n    financial_worry     = `Q10_How worried are you about money? (1-5)`,\n    workshop            = `Workshop group`,\n    workshop_sessions   = `Workshop sessions attended`,\n    considering_dropout = `Y1_Considered leaving?`\n  ) |>\n  rename_with(~ item_names, .cols = Q11_1:Q11_22)\n```\n:::\n\n\nThe call `paste0(\"stress_\", 1:6)` builds the names `stress_1` to `stress_6`, which saves typing them all. The questionnaire's wording is not lost: it belongs in the codebook (Chapter 2).\n\n### Consistent categories\n\nIf \"F\", \"female\", and \"Female\" stay separate, every table and every test treats them as three different groups. Categories are fixed by looking for a pattern rather than listing every spelling, after `str_to_lower()` and `str_trim()` have removed differences in case and stray spaces:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses <- responses |>\n  mutate(\n    gender = if_else(str_starts(str_to_lower(str_trim(gender)), \"f\"), \"Female\", \"Male\"),\n    faculty = case_when(\n      str_detect(str_to_lower(faculty), \"educ\")    ~ \"Education\",\n      str_detect(str_to_lower(faculty), \"health\")  ~ \"Health Sciences\",\n      str_detect(str_to_lower(faculty), \"humanit\") ~ \"Humanities\",\n      str_detect(str_to_lower(faculty), \"social\")  ~ \"Social Sciences\",\n      str_detect(str_to_lower(faculty), \"natural|^sciences$\") ~ \"Natural Sciences\"\n    ),\n    programme  = if_else(str_detect(str_to_lower(programme), \"ph\"), \"PhD\", \"Master's\"),\n    study_mode = if_else(str_detect(str_to_lower(study_mode), \"part\"), \"Part-time\", \"Full-time\"),\n    employment = if_else(str_to_lower(employment) %in% c(\"none\", \"no job\"), \"None\", employment),\n    across(c(has_children, lives_away, considering_dropout),\n           ~ if_else(str_starts(str_to_lower(.x), \"y\"), \"Yes\", \"No\"))\n  )\nresponses |> count(gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  gender     n\n  <chr>  <int>\n1 Female   312\n2 Male     288\n```\n\n\n:::\n\n```{.r .cell-code}\nresponses |> count(faculty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  faculty              n\n  <chr>            <int>\n1 Education          148\n2 Health Sciences    154\n3 Humanities          95\n4 Natural Sciences    87\n5 Social Sciences    116\n```\n\n\n:::\n:::\n\n\nTwo details deserve attention. The order of conditions in `case_when()` matters: \"social sciences\" also contains \"sciences\", so Social Sciences is checked before Natural Sciences. And `across()` applies the same change to several columns at once, here turning `Yes`, `yes`, and `Y` into `Yes`.\n\nAfter each fix, the categories should be counted again, as above. If a spelling was missed, it shows up immediately.\n\n### Missing codes and numbers stored as text\n\nSurvey tools often mark missing answers with codes such as `99` or `-9`. As the opening example showed, these codes must become `NA` before any calculation, or R will treat them as real values. The function `na_if()` turns a code into `NA`, and `as.integer()` then turns the text into whole numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses <- responses |>\n  mutate(\n    financial_worry = financial_worry |> na_if(\"99\") |> na_if(\"-9\") |> as.integer(),\n    across(all_of(item_names), ~ as.integer(na_if(.x, \"99\"))),\n    workshop_sessions = as.integer(workshop_sessions),\n    age = parse_number(age)\n  )\n```\n:::\n\n\n::: {.callout-warning}\n## Do not replace `99` everywhere\n\nIt is tempting to turn every `99` in the file into `NA` in one go. But a `99` is not always a code. In a wellbeing score from 0 to 100, it is a perfectly real value. Replace missing codes only in the columns where you know they are codes.\n:::\n\nThe function `parse_number()` from readr reads the number out of a text value, ignoring extra text around it. It is useful for the sleep columns, where some students typed `\"7 hrs\"`. A decimal comma, however, defeats it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparse_number(c(\"7 hrs\", \"6.5\", \"6,5\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  7.0  6.5 65.0\n```\n\n\n:::\n:::\n\n\nThe value `\"6,5\"` becomes 65, not 6.5, because in English a comma separates thousands. The comma has to be changed to a point first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparse_number(str_replace(c(\"7 hrs\", \"6.5\", \"6,5\"), \",\", \".\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.0 6.5 6.5\n```\n\n\n:::\n:::\n\n\nMistakes like this produce no error message. The only protection is to check the data after each step.\n\n### Impossible values\n\nSome values cannot be true, such as an age of 250 or 26 hours of sleep a night. Left in the data, a single one can dominate an average or a regression. They are typing mistakes, and since the true value cannot be known, the honest fix is to set them to `NA` rather than to guess (an age of 250 might have been 25, or 50):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponses |> filter(age > 100) |> select(student_id, age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  student_id   age\n  <chr>      <dbl>\n1 S0007        250\n```\n\n\n:::\n\n```{.r .cell-code}\nresponses <- responses |> mutate(age = if_else(age > 100, NA, age))\n```\n:::\n\n\nThis is where the missing age in Chapter 1 came from. Unusual but possible values, such as a student who sleeps 4 hours a night, are a different matter: they are real data and are kept. Chapter 6 discusses how to handle them.\n\n### Scale scores\n\nA questionnaire scale is scored as the average of its items, and the items must all point in the same direction before they are averaged. One stress item, `stress_4` (\"I feel confident handling problems in my studies\"), is worded in the opposite direction to the others: agreeing with it means *less* stress. Averaged as it stands, it would cancel part of what the other five items measure. It must first be **reversed**, so that 1 becomes 5, 2 becomes 4, and so on. On a 1-to-5 scale, subtracting from 6 does exactly that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquestionnaire_clean <- responses |>\n  select(student_id, all_of(item_names))\n\nscores <- questionnaire_clean |>\n  mutate(\n    stress_4           = 6 - stress_4,\n    stress_score       = rowMeans(pick(stress_1:stress_6), na.rm = TRUE),\n    burnout_score      = rowMeans(pick(burnout_1:burnout_6), na.rm = TRUE),\n    support_score      = rowMeans(pick(support_1:support_6), na.rm = TRUE),\n    satisfaction_score = rowMeans(pick(satisfaction_1:satisfaction_4), na.rm = TRUE)\n  ) |>\n  select(student_id, ends_with(\"_score\"))\nhead(scores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  student_id stress_score burnout_score support_score satisfaction_score\n  <chr>             <dbl>         <dbl>         <dbl>              <dbl>\n1 S0191              2.83          1.5           3.83               3.33\n2 S0015              4.5           3.83          1.67               3   \n3 S0474              3.5           4.5           1.4                2.75\n4 S0418              3.17          3             1.67               3.75\n5 S0049              3             3.5           3.17               3.33\n6 S0537              2.83          2.5           3.2                4.75\n```\n\n\n:::\n:::\n\n\nThe function `pick()` selects the columns of one scale, and `rowMeans()` averages each student's answers across them. With `na.rm = TRUE`, a student who skipped one item still gets a score from the items they answered. Whether that is acceptable, and how many skipped items is too many, is a decision to report in the thesis. Chapter 9 checks that the items really do measure four separate scales.\n\nThe original items should stay in the data, with the scores stored separately as here, because the items are needed again for checking the scales.\n\n### From wide to long\n\nThe semester measurements sit side by side: `GPA_S1`, `Sleep_S1`, ..., `Wellbeing_S4`, 28 columns in all. The data is not tidy, since each row holds four observations, and analyses of change over time need one row per student per semester. This is a `pivot_longer()` with one extra idea: each column name holds two pieces of information, the variable (`GPA`) and the semester (`1`), separated by `_S`. The special name `.value` tells R to use the first piece as a column name:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemesters_clean <- responses |>\n  select(student_id, matches(\"_S[1-4]$\")) |>\n  pivot_longer(\n    cols      = -student_id,\n    names_to  = c(\".value\", \"semester\"),\n    names_sep = \"_S\"\n  )\nhead(semesters_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  student_id semester GPA   Sleep Study Exercise Caffeine Meetings Wellbeing\n  <chr>      <chr>    <chr> <chr> <chr> <chr>    <chr>    <chr>    <chr>    \n1 S0191      1        3.07  5.6   31    3        140      2        64       \n2 S0191      2        3.29  5,7   30    4        140      7        65       \n3 S0191      3        3.35  5.5   32    3        130      5        60       \n4 S0191      4        3.58  6.6   29    2        155      7        69       \n5 S0015      1        2.8   6.5   15    2        210      2        34       \n6 S0015      2        3.2   6.5   18    0        275      5        38       \n```\n\n\n:::\n:::\n\n\n\n\nThe selection `matches(\"_S[1-4]$\")` picks the columns whose names end in `_S1` to `_S4`. The rest is cleaning already familiar from the steps above: tidy names, text to numbers (with the decimal-comma fix for sleep), impossible values to `NA`, and finally removing the empty rows of students who had left the study:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemesters_clean <- semesters_clean |>\n  rename(gpa = GPA, sleep_hours = Sleep, study_hours = Study,\n         exercise_days = Exercise, caffeine_mg = Caffeine,\n         supervisor_meetings = Meetings, wellbeing = Wellbeing) |>\n  mutate(\n    semester    = as.integer(semester),\n    sleep_hours = parse_number(str_replace(sleep_hours, \",\", \".\")),\n    across(c(gpa, study_hours, exercise_days, caffeine_mg, supervisor_meetings, wellbeing),\n           parse_number),\n    sleep_hours = if_else(sleep_hours > 24, NA, sleep_hours),\n    study_hours = if_else(study_hours > 168, NA, study_hours),\n    gpa         = if_else(gpa > 4, NA, gpa)\n  ) |>\n  filter(!if_all(gpa:wellbeing, is.na))\nnrow(semesters_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2326\n```\n\n\n:::\n:::\n\n\nThe condition `if_all(gpa:wellbeing, is.na)` is `TRUE` for rows where every measurement is missing, and `!` keeps the others.\n\n### Checking the result\n\nThe last step checks what the cleaning has produced. The amount of missing data comes first, and `across()` inside `summarise()` counts the `NA`s in every column at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemesters_clean |> summarise(across(everything(), ~ sum(is.na(.x))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 9\n  student_id semester   gpa sleep_hours study_hours exercise_days caffeine_mg\n       <int>    <int> <int>       <int>       <int>         <int>       <int>\n1          0        0     1          21          23            20          25\n# ℹ 2 more variables: supervisor_meetings <int>, wellbeing <int>\n```\n\n\n:::\n:::\n\n\nUp to 25 values per measurement are still missing, about 1% of the records: answers students really did not give, and the impossible values set to `NA`. These are genuine gaps, and Chapter 6 discusses how to handle them.\n\nThe most satisfying check of all is a comparison with a trusted result. The clean tables in the `data2thesis` package were produced from this same export, so the cleaned data should match them exactly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsame <- function(mine, theirs) {\n  mine   <- as.data.frame(mine)[, names(mine)]\n  theirs <- as.data.frame(theirs)[, names(mine)]\n  isTRUE(all.equal(mine, theirs, check.attributes = FALSE))\n}\nsame(questionnaire_clean |> arrange(student_id),\n     questionnaire |> arrange(student_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nsame(semesters_clean |> arrange(student_id, semester),\n     semesters |> arrange(student_id, semester))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nBoth are `TRUE`. The cleaning is complete, and from here on the book uses the clean tables from the package.\n\n::: {.callout-tip}\n## Writing it up\n\nA thesis reports the cleaning briefly, usually in the methods chapter, so that a reader can judge what was done to the data. For the survey export, with the numbers filled in by the code:\n\nThe survey export contained 615 responses. Test responses (3) and duplicate submissions (12) were removed, leaving 600 students. Inconsistent spellings of categories were standardised, and missing-answer codes (99 and −9) were recoded as missing. Impossible values (4 in all), such as an age of 250 years or 26 hours of sleep a night, were set to missing, because the true values could not be known. The reverse-worded item `stress_4` was recoded before scale scores were computed as the mean of each scale's items, using all items a student had answered.\n:::\n\n::: {.callout-tip}\n## Save your cleaning as a script\n\nPut all of these steps in one script, for example `01-clean-data.R`, that starts from the raw file and ends by saving the clean tables:\n\n```r\nwrite_csv(semesters_clean, here::here(\"data\", \"semesters_clean.csv\"))\n```\n\nNever edit the raw file by hand. If you find a new problem next month, you fix it in the script and run it again, and every step stays on record.\n:::\n\n::: {.callout-note icon=\"false\"}\n## In your field: environmental and public health\n\n`airquality` is a real dataset that comes with R: daily air measurements in New York from May to September 1973. Like most real data, it has gaps. The same verbs summarise it by month:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nairquality |>\n  summarise(\n    mean_ozone   = mean(Ozone, na.rm = TRUE),\n    missing_days = sum(is.na(Ozone)),\n    .by = Month\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Month mean_ozone missing_days\n1     5   23.61538            5\n2     6   29.44444           21\n3     7   59.11538            5\n4     8   59.96154            5\n5     9   31.44828            1\n```\n\n\n:::\n:::\n\n\nOzone levels peak in July and August, and June has the most missing days, a pattern worth knowing before any analysis: if the missing days were mostly hot ones, the June average would be too low.\n:::\n\n## Chapter review\n\n### Summary\n\n- Clean data is valid, accurate, complete as far as possible, consistent, and unique. Cleaning decisions shape the results, so they are made in code from an untouched raw file, recorded, reported, and checked after every step.\n- Tidy data has one variable per column, one observation per row, and one value per cell.\n- The pipe `|>` passes a result to the next function: read it as \"and then\".\n- dplyr verbs: `filter()` chooses cases, `select()` chooses variables, `arrange()` sorts, `mutate()` creates variables, `summarise()` with `.by` summarises by group, and `count()` counts. `case_when()` sorts values into categories.\n- `pivot_longer()` and `pivot_wider()` reshape data between wide and long formats.\n- `left_join()` combines tables by an identifier; `anti_join()` finds rows without a match.\n- Cleaning survey data: remove test and duplicate rows, rename variables, fix categories by pattern, turn missing codes into `NA` column by column, convert text to numbers (watch decimal commas), set impossible values to `NA`, reverse reversed items before computing scale scores, and check the result.\n\n### Key terms\n\nData cleaning, tidyverse, tidy data, tibble, pipe, verb, grouped summary, wide format, long format, join, identifier, missing code, reversed item, scale score.\n\n## Exercises\n\nThe [playground](../playground/chapter03.html) has these and more, with hints and solutions.\n\n1. Using `students`, find the average age of students in each faculty, sorted from oldest to youngest. (Remember `na.rm = TRUE`.)\n2. Add a column to `semesters` that is `\"Short\"` when `sleep_hours` is under 6, `\"Recommended\"` when it is 7 or more, and `\"Moderate\"` otherwise. Count the semester records in each category.\n3. Using `semesters`, make a table of average GPA with one row per student and one column per semester, using `pivot_wider()`. Show the first rows.\n4. Join `semesters` to `students` and compare the average semester GPA of full-time and part-time students.\n5. Explain why the `stress_4` item must be reversed before the stress score is calculated, and describe what would happen to the scores if it were not.\n6. For each of the five qualities of clean data, give one example of a problem from your own field, and the cleaning decision it would require.\n\n## Further reading\n\n- *R for Data Science* [@wickham2023]: chapters \"Data transformation\", \"Data tidying\", \"Joins\", \"Strings\", and \"Missing values\".\n- \"Tidy data\" [@wickham2014tidy], the paper that introduced the idea, with many examples of untidy data and how to fix it.\n- The [dplyr](https://dplyr.tidyverse.org) and [tidyr](https://tidyr.tidyverse.org) websites, with a reference page for every function.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}