{
  "hash": "9e6d68c731a7e9a49bdf1904bff6ad25",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Artificial Intelligence in Academic Research\"\nsubtitle: \"Coding Assistants, Qualitative NLP with ellmer, Cohen's Kappa, and Research Ethics\"\nauthor: \"Dr. Polla Fattah\"\ninstitute: \"From Data to Thesis: Research Data Analysis with R\"\nformat:\n  revealjs:\n    theme: [default, ../../styles/theme.scss]\n    slide-number: true\n    preview-links: auto\n    chalkboard: true\n    transition: slide\n    highlight-style: github\n    code-line-numbers: false\n    width: 1200\n    height: 750\nexecute:\n  freeze: auto\n---\n\n# Artificial Intelligence with R\n\n### Augmenting Quantitative and Qualitative Science\n\n**Chapter 18 · From Data to Thesis**\n\nDr. Polla Fattah\n\n---\n\n## When Research Data is Unstructured Text\n\nMuch of what researchers study cannot be captured on a 5-point Likert scale:\n\n- Open-ended survey responses\n- In-depth qualitative interview transcripts\n- Clinical admission notes and doctor discharge summaries\n- Policy documents, historical archives, and committee minutes\n\n> **The Methodological Bottleneck**:  \n> Reading and categorizing 1,000 open-ended responses by hand can take weeks of full-time labor.\n\nCan modern **Large Language Models (LLMs)** assist with qualitative coding without compromising scientific rigor?\n\n---\n\n## The Two Faces of AI in Research\n\nIn modern data science, Artificial Intelligence serves two distinct roles:\n\n```\n+-----------------------------------------------------------------------------------+\n|                            ARTIFICIAL INTELLIGENCE                                |\n+----------------------------------------+------------------------------------------+\n|          1. CODING ASSISTANT           |          2. QUALITATIVE ANALYST          |\n|  - Generates R code drafts             |  - Reads open-ended text                 |\n|  - Explains complex error traces       |  - Classifies responses into themes      |\n|  - Refactors tidyverse pipelines       |  - Extracts clinical entities from notes |\n|  - Interactive debugging partner       |  - Validated against human benchmarks    |\n+----------------------------------------+------------------------------------------+\n```\n\nIn both roles, **the human researcher remains legally and intellectually responsible** for every line of code and every published finding.\n\n---\n\n# Inter-Rater Reliability\n\n### Measuring Agreement Beyond Mere Chance\n\n---\n\n## The Problem with Raw Agreement\n\nSuppose two research assistants code 20 student responses for their primary challenge: **Workload** vs. **Family**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoder_a <- c(rep(\"Workload\", 16), rep(\"Family\", 4))\ncoder_b <- c(rep(\"Workload\", 14), rep(\"Family\", 2),\n             rep(\"Workload\", 2),  rep(\"Family\", 2))\n\n# Raw percentage agreement:\nmean(coder_a == coder_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8\n```\n\n\n:::\n:::\n\n\n**80% agreement sounds impressive!** But does this reflect genuine coding consistency?\n\n---\n\n## The Base-Rate Illusion\n\nLook closer at the marginal distributions:\n- Coder A categorized **80%** of all responses as *Workload*.\n- Coder B categorized **80%** of all responses as *Workload*.\n\n```\nChance agreement on Workload:  0.80 × 0.80 = 0.64\nChance agreement on Family:    0.20 × 0.20 = 0.04\nTotal Expected Chance Agreement = 0.64 + 0.04 = 0.68 (68%)\n```\n\nTwo coders throwing darts at a board with these base rates would agree **68% of the time purely by luck**!\n\nThe observed $80\\%$ agreement gained very little ground over sheer coincidence.\n\n---\n\n## Cohen's Kappa ($\\kappa$)\n\nJacob Cohen (1960) formulated **Kappa** to measure agreement corrected for chance:\n\n$$\\kappa = \\frac{P_o - P_e}{1 - P_e}$$\n\nWhere:\n- $P_o$ = **Observed proportion of agreement**\n- $P_e$ = **Expected agreement under independence (chance)**\n- $1 - P_e$ = Maximum possible agreement achievable beyond chance\n\n$$\\kappa = \\frac{0.80 - 0.68}{1 - 0.68} = \\frac{0.12}{0.32} = \\mathbf{0.375}$$\n\nWhat looked like an impressive $80\\%$ is actually **poor-to-fair reliability** ($\\kappa = 0.38$).\n\n---\n\n## Interpreting Cohen's Kappa\n\nThe standard benchmarks established by Landis & Koch (1977):\n\n| Cohen's $\\kappa$ Range | Strength of Agreement | Acceptable for Science? |\n|---|---|---|\n| $< 0.20$ | Slight agreement | Unacceptable |\n| $0.21 - 0.40$ | Fair agreement | Problematic / Revise codebook |\n| $0.41 - 0.60$ | Moderate agreement | Minimum threshold for exploratory work |\n| $0.61 - 0.80$ | Substantial agreement | Good scientific reliability |\n| $0.81 - 1.00$ | Almost perfect | Gold standard benchmark |\n\nIn `tidymodels` / `yardstick`, calculate it directly:\n```r\nyardstick::kap(df, truth = human_code, estimate = ai_code)\n```\n\n---\n\n# How Large Language Models Work\n\n### Next-Token Probability Engines, Not Truth Oracles\n\n---\n\n## The Autoregressive Mechanism\n\nLLMs (ChatGPT, Claude, Gemini, Gemma, Llama) are massive artificial neural networks trained on hundreds of billions of words.\n\nAt their core, they perform one mathematical task:\n\n$$P(w_{t} \\mid w_1, w_2, \\dots, w_{t-1})$$\n\n> **Predicting the next token** (word or sub-word piece) given the entire sequence that came before it.\n\n```\nInput: \"The student was stressed because of the upcoming ...\"\nProbabilities:\n  - \"deadline\"  (58%)\n  - \"exam\"      (31%)\n  - \"meeting\"    (8%)\n  - \"banana\"    (0.00001%)\n```\n\nThe model outputs text by sampling from this conditioned probability distribution.\n\n---\n\n## What LLMs Excel At vs Where They Fail\n\n```\n+-------------------------------------+-------------------------------------+\n|         WHAT LLMs DO WELL           |         WHERE LLMs FAIL             |\n+-------------------------------------+-------------------------------------+\n| - Writing standard R / tidyverse    | - Plausible Hallucinations          |\n| - Explaining error messages         |   (Inventing fake functions & args) |\n| - Translating between languages     | - Fabricating academic citations    |\n| - Synthesizing qualitative text     | - Silent logic bugs in calculations |\n| - Adhering to structured schemas    | - Knowledge cutoffs (outdated APIs) |\n+-------------------------------------+-------------------------------------+\n```\n\n::: {.callout-important}\n### Plausibility $\\neq$ Veracity\nAn LLM does not generate text because it knows it is true. It generates text because it sounds **statistically probable**.\n:::\n\n---\n\n# AI as an R Coding Assistant\n\n### Best Practices for Pair Programming\n\n---\n\n## Crafting High-Precision Prompts\n\nAn assistant can only be as accurate as your context:\n\n```\nPOOR PROMPT:\n\"Write R code to get the dropout rates.\"\n(Result: Generic code, assumed column names, likely base-R or outdated syntax)\n\nHIGH-PRECISION PROMPT:\n\"I have a tibble called students. Here is glimpse(students):\n- student_id: chr\n- faculty: fct\n- considering_dropout: chr ('Yes', 'No')\n\nCalculate the percentage of students considering dropout WITHIN each faculty.\nUse modern dplyr syntax with the native pipe |>.\"\n```\n\n---\n\n## The Subtle Trap of Plausible Logic Bugs\n\nSuppose you ask an assistant for the dropout percentage by faculty:\n\n```r\n# Assistant's Suggestion:\nstudents |>\n  summarise(\n    percent = 100 * sum(considering_dropout == \"Yes\") / nrow(students),\n    .by = faculty\n  )\n```\n\n### The Danger:\n- It executes without any error!\n- The numbers look reasonable ($3.2\\%, 4.1\\%, 2.8\\%$).\n- **The flaw**: `nrow(students)` divides by the **entire university population**, not the faculty total! The percentages sum to the overall rate rather than each faculty's internal rate!\n\n---\n\n## The Corrected Calculation\n\nTo compute the proportion *within* each faculty group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(data2thesis)\n\nstudents |>\n  summarise(\n    n_students = n(),\n    n_dropout  = sum(considering_dropout == \"Yes\"),\n    percent    = round(100 * mean(considering_dropout == \"Yes\"), 1),\n    .by        = faculty\n  ) |>\n  arrange(desc(percent))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           faculty n_students n_dropout percent\n1  Health Sciences        154        29    18.8\n2  Social Sciences        116        21    18.1\n3       Humanities         95        13    13.7\n4 Natural Sciences         87        11    12.6\n5        Education        148        16    10.8\n```\n\n\n:::\n:::\n\n\nThe mean of a logical vector (`considering_dropout == \"Yes\"`) is mathematically identical to the internal proportion!\n\n---\n\n## Four Verification Heuristics\n\nWhenever using AI-generated code in your research:\n\n1. **Test on Toy Data**: Run the code on a 4-row handmade tibble where you know the true answer by mental arithmetic.\n2. **Triangulate by Another Route**: Verify summary numbers against simple counts:\n   ```r\n   students |> count(faculty, considering_dropout)\n   ```\n3. **Verify Function Help**: Check `?function_name` in the R console to ensure suggested arguments actually exist in your installed package version.\n4. **Demand Explanations**: Ask: *\"Explain line 3. Why did you use .data[[...]] instead of standard evaluation?\"*\n\n---\n\n# Qualitative Coding with R & LLMs\n\n### The RQ11 Case Study: Graduate Student Challenges\n\n---\n\n## Research Question 11\n\nIn the university wellbeing dataset, students completed an open-ended prompt:\n\n> *\"What has been your biggest challenge during your studies?\"*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stringr)\n\nopen_responses |>\n  slice(c(5, 9, 15, 55)) |>\n  pull(biggest_challenge)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"most of my income goes on tuition fees. Besides that, I work alone all the time. Things are slowly improving.\"                                                  \n[2] \"I moved to a city where I know no one for my studies and I feel lonely. And I never have enough time.\"                                                          \n[3] \"Supervisor.\"                                                                                                                                                    \n[4] \"The direction of my thesis changed twice after comments from my supervsor. Sometimes I rewrite the same section again and again without knowing if it is right.\"\n```\n\n\n:::\n:::\n\n\n**The Goal**: Categorize hundreds of free-text responses into a standardized codebook.\n\n---\n\n## The Seven-Theme Codebook\n\nElaf developed a qualitative codebook with seven distinct themes:\n\n```\n1. Supervision : Supervisor friction, lack of feedback, missed meetings.\n2. Workload    : Excessive volume, tight deadlines, time management.\n3. Finances    : Tuition fees, living expenses, need for outside employment.\n4. Family      : Childcare, eldercare, partner commitments, home distractions.\n5. Health      : Physical illness, mental health, anxiety, chronic sleep loss.\n6. Isolation   : Loneliness, imposter syndrome, lack of peer community.\n7. Other       : Bureaucracy, ethics clearance, English proficiency, tech issues.\n```\n\nElaf hand-coded a representative benchmark sample ($N = 100$) over two weeks.\n\n---\n\n## Baseline Method: Keyword Dictionary\n\nBefore jumping to deep neural networks, establish a transparent baseline using regular expressions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkeywords <- c(\n  Supervision = \"\\\\b(supervis|feedback|guidance|meeting)\",\n  Workload    = \"\\\\b(time|deadline|workload|too much|assignment|reading|busy)\",\n  Finances    = \"\\\\b(money|fee|scholarship|rent|afford|salary|income|funding|stipend)\",\n  Family      = \"\\\\b(famil|child|kid|son\\\\b|daughter|baby|parent|mother|father)\",\n  Health      = \"\\\\b(sleep|tired|stress|anxi|health|ill\\\\b|burnout|exhaust)\",\n  Isolation   = \"\\\\b(lonel|alone|friends|outsider|miss (home|my)|far from)\",\n  Other       = \"\\\\b(ethic|participant|statistic|library|procedure|english)\"\n)\n```\n:::\n\n\n---\n\n## Keyword Classification Logic\n\nAssign each response to the theme with the highest keyword count:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncode_by_keywords <- function(answer) {\n  hits <- sapply(keywords, \\(pattern) str_count(str_to_lower(answer), pattern))\n  if (all(hits == 0)) \"Other\" else names(keywords)[which.max(hits)]\n}\n\ncode_by_keywords(\"I miss my family and I cannot afford the tuition fees.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Finances\"\n```\n\n\n:::\n:::\n\n\n- Matches 1 Family keyword (\"family\")\n- Matches 2 Finance keywords (\"afford\", \"fees\")\n- Classifies as: **Finances**\n\n---\n\n## Evaluating Keyword Performance\n\nHow well does the dictionary match Elaf's manual coding?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(yardstick)\n\nthemes <- names(keywords)\n\nkeyword_check <- open_responses_coded |>\n  mutate(\n    keyword_theme = sapply(biggest_challenge, code_by_keywords),\n    theme         = factor(theme, levels = themes),\n    keyword_theme = factor(keyword_theme, levels = themes)\n  )\n\nkeyword_check |> accuracy(truth = theme, estimate = keyword_theme)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 accuracy multiclass     0.605\n```\n\n\n:::\n\n```{.r .cell-code}\nkeyword_check |> kap(truth = theme, estimate = keyword_theme)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 kap     multiclass     0.506\n```\n\n\n:::\n:::\n\n\n**Results**: Accuracy $\\approx 61\\%$, $\\kappa \\approx 0.54$ (Moderate agreement).  \n**Why it fails**: Keywords cannot parse semantic context, negation, or competing clauses.\n\n---\n\n# Calling LLMs with `ellmer`\n\n### Seamless R Integration with Cloud and Local Models\n\n---\n\n## Introducing the `ellmer` Package\n\n**`ellmer`** (developed by Hadley Wickham & Posit) connects R directly to state-of-the-art language models:\n\n```\n                       ellmer in R\n                            |\n           +----------------+----------------+\n           |                                 |\n   Cloud API Models                  Local Models\n   (Claude, OpenAI, Gemini)          (Ollama / Gemma / Llama)\n   - Highest accuracy                - 100% On-device privacy\n   - Requires API key                - Free / Zero API costs\n   - Data sent over internet         - Complies with strict ethics\n```\n\n---\n\n## Protecting API Keys in R\n\n::: {.callout-caution}\n### Never Hard-Code API Keys in Your Scripts!\nIf you push your script to GitHub, automated scrapers will steal your key within seconds.\n:::\n\nStore keys in your user-level `.Renviron` file:\n\n```r\n# Open .Renviron safely in RStudio\nusethis::edit_r_environ()\n```\n\nAdd your credentials:\n```bash\nANTHROPIC_API_KEY=sk-ant-api03-...\nOPENAI_API_KEY=sk-proj-...\nGEMINI_API_KEY=AIzaSy...\n```\n\nR loads these environment variables silently on startup.\n\n---\n\n## Running Models Locally with Ollama\n\nFor sensitive human participant data, use **Ollama** ([ollama.com](https://ollama.com)):\n\n1. Install Ollama on your computer.\n2. In your terminal, pull a compact, high-performance open model:\n   ```bash\n   ollama pull gemma4:e4b\n   ```\n3. Connect from R with zero configuration:\n   ```r\n   library(ellmer)\n   chat <- chat_ollama(model = \"gemma4:e4b\")\n   chat$chat(\"What is Cohen's kappa?\")\n   ```\n- **Data never leaves your machine.**\n- Completely compliant with institutional IRB / Ethics boards!\n\n---\n\n## Structured Output Schemas\n\nWhen processing 1,000 texts, we cannot accept rambling conversational replies. We need **machine-readable structured output**.\n\n```r\ncodebook_prompt <- \"\nYou are an expert qualitative researcher coding student survey responses.\nAssign each text to exactly ONE theme from the codebook:\nSupervision, Workload, Finances, Family, Health, Isolation, Other.\n\"\n\n# Define the strict schema:\ntheme_type <- type_object(\n  theme = type_enum(themes, description = \"The primary challenge theme\")\n)\n\nchat <- chat_anthropic(\n  system_prompt = codebook_prompt,\n  model         = \"claude-sonnet-5\",\n  params        = params(temperature = 0) # Deterministic\n)\n```\n\nSetting `temperature = 0` forces the model to select greedy, reproducible tokens.\n\n---\n\n## Batch Qualitative Coding\n\nProcess an entire survey column in parallel:\n\n```r\nai_results <- parallel_chat_structured(\n  chat,\n  prompts = as.list(open_responses$biggest_challenge),\n  type    = theme_type\n)\n```\n\n```\n+------------+-------------------------------------------+-------------+\n| student_id | biggest_challenge                         | theme       |\n+------------+-------------------------------------------+-------------+\n| STU_001    | Balancing lab experiments with child care | Family      |\n| STU_002    | Tuition fees are far too high this term   | Finances    |\n| STU_003    | Disagreements with my primary supervisor  | Supervision |\n+------------+-------------------------------------------+-------------+\n```\n\n---\n\n## Evaluating the AI Coder vs Humans\n\nJoining the AI model's classifications to Elaf's manual benchmark:\n\n```\n+--------------------+----------------+-------------------+\n| Metric             | Keyword Method | Local LLM (Gemma) |\n+--------------------+----------------+-------------------+\n| Raw Accuracy       | 61.0%          | 82.0%             |\n| Chance Agreement   | 15.3%          | 16.1%             |\n| Cohen's Kappa      | 0.54 (Fair)    | 0.78 (Substantial)|\n+--------------------+----------------+-------------------+\n```\n\nThe language model approaches human-level agreement ($\\kappa = 0.78$), far outperforming the dictionary approach!\n\n---\n\n## Inspecting Disagreements: Confusion Matrix\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](18-ai_files/figure-revealjs/fig-confusion-matrix-1.png){#fig-confusion-matrix fig-align='center' width=768}\n:::\n:::\n\n\n---\n\n## Qualitative Error Analysis\n\nWhen human and model disagree, read the specific text:\n\n> *\"I am working 30 hours a week at a supermarket to pay rent, which leaves almost no time for reading.\"*\n\n- **Human Coder**: *Workload* (Focuses on lack of reading time).\n- **Model Coder**: *Finances* (Focuses on working to pay rent).\n\n::: {.callout-tip}\n### Codebook Refinement\nDisagreements often highlight **ambiguities in your qualitative codebook**, not model failure.  \nRule addition: *\"When paid work causes time pressure, code under Finances.\"*\n:::\n\n---\n\n## Convergent Validity: Linking Text to Numbers\n\nDo the AI-classified themes correspond to validated psychometric scales?\n\n```\nTheme Classified by AI    | Mean Supervisor Support Scale (1 - 5)\n--------------------------+--------------------------------------\nSupervision               | 2.12  <-- Lowest perceived support!\nWorkload                  | 3.45\nIsolation                 | 3.20\nFinances                  | 3.82\nFamily                    | 3.91\n```\n\n- Students classified under **Supervision** reported drastically lower perceived supervisor support ($M = 2.12$ vs $3.8+$).\n- **Validity Confirmed**: The text answers and quantitative survey scales tell the exact same story!\n\n---\n\n# Responsible AI in Academic Research\n\n### Ethics, Privacy, and Disclosure\n\n---\n\n## The Core Tenets of Research AI Ethics\n\n```\n      1. HUMAN RESPONSIBILITY               2. PARTICIPANT PRIVACY\n   You own every claim, error,           Never send confidential or\n   and hallucination in your thesis.     quasi-identifiable text to APIs.\n                  \\                             /\n                   \\                           /\n      3. METHODOLOGICAL DISCLOSURE          4. REPRODUCIBILITY FREEZE\n   Disclose model, version, prompts,     Save exact prompt templates and\n   and validation metrics explicitly.    cache outputs for publication.\n```\n\n---\n\n## Guidelines for Thesis Disclosure (APA & COPE)\n\nAccording to the **Committee on Publication Ethics (COPE)**:\n- **AI cannot be listed as an author** (it cannot assume legal responsibility).\n- Its use must be explicitly documented in your **Methods section**.\n\n### Example Methodology Statement:\n> *\"Open-ended survey responses were categorized into seven predefined themes using an open-source large language model (Gemma 4, e4b variant) executed locally via Ollama and the R ellmer package (temperature = 0). The prompt contained the full codebook (Appendix B). The model's classifications were validated against a benchmark sample of 100 responses coded independently by the primary author, yielding substantial inter-rater reliability (Accuracy = 82.0%, Cohen's $\\kappa = 0.78$).\"*\n\n---\n\n## Algorithmic Bias and Representativeness\n\nLLMs inherit the linguistic and cultural biases of their training corpora:\n\n- **Dialect Discrepancies**: Models often misinterpret regional idioms, non-native English phrasings, or vernacular expressions.\n- **Sentiment Asymmetry**: Subtle complaints from specific demographic subgroups may be downplayed or misinterpreted.\n\n### The Mitigation Protocol:\nAlways test your model's classification accuracy **across demographic strata** (e.g. domestic vs. international students, native vs. ESL speakers).\n\n---\n\n## Chapter Summary\n\n- **Qualitative Coding at Scale**: LLMs provide powerful assistance for categorizing text, bridging qualitative nuance and quantitative scale.\n- **Inter-Rater Reliability**: Raw agreement is distorted by high base rates. Always compute **Cohen's Kappa ($\\kappa$)** to evaluate agreement beyond chance.\n- **Prompt Engineering in R**: Provide explicit goals, tibble schemas (`glimpse`), and style constraints. Always test generated code with toy data.\n- **`ellmer` Architecture**: Seamlessly stream prompts and enforce strict schema types (`type_enum`) with cloud APIs or private local models (Ollama).\n- **Validation is Non-Negotiable**: Validate AI output against a human-coded benchmark sample before applying it to full datasets.\n- **Transparency & Integrity**: Disclose model versions, save prompt templates, freeze outputs, and protect participant anonymity.\n\n---\n\n## Recommended Exercises & Next Steps\n\n1. **Verify Base-Rate Impact**: Calculate Cohen's $\\kappa$ by hand for two coders who agree 90% of the time, where theme A occurs 90% of the time.\n2. **Dictionary vs LLM**: Add 3 keywords to the regex dictionary to capture multi-word phrases and test if $\\kappa$ improves.\n3. **Local LLM Setup**: Install Ollama, pull a lightweight model (`gemma4:e4b`), and test a basic text prompt using `chat_ollama()`.\n4. **Draft Methodology Disclosure**: Write the formal AI usage disclosure paragraph for your own master's or doctoral thesis.\n",
    "supporting": [
      "18-ai_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}