{
  "hash": "3b5c07a7c094131d8e2cd68bec9937a3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mixed-Effects Models\"\ndescription: \"Chapter 10: repeated measures and nested data, random intercepts and slopes, the intraclass correlation, growth models, persistence of the workshop effect, supervisors, and count outcomes.\"\nformat: deck-html\nexecute:\n  echo: false\n  freeze: auto\n---\n\n\n\n# Mixed-Effects Models\n\nWhen observations are not independent\n\n**Chapter 10**\n\nPolla Fattah\n\n---\n\n## By the end of today you can\n\n- recognise repeated-measures and nested data;\n- explain, with a simulation, why ordinary regression gets their uncertainty wrong;\n- fit random intercept and random slope models with lme4;\n- interpret fixed effects, random effects, and the intraclass correlation;\n- test whether an effect changes over time, and compare models;\n- model a count outcome with a generalised linear mixed model;\n- report a mixed-effects model in a thesis.\n\n---\n\n## Two kinds of structure\n\n| Structure | Example | Grouped within |\n|---|---|---|\n| repeated measures | four semesters per student | people |\n| nested data | students with the same supervisor | groups |\n\nObservations within a group are more alike than observations from different groups.\n\n---\n\n## Less information than the rows suggest\n\nA student who scores high this semester is likely to score high next semester.\n\nStudents of one supervisor share that supervisor's style.\n\nMethods that ignore this get the uncertainty wrong, sometimes badly.\n\n---\n\n## A simulated training course with no effect\n\n```r\nsimulate_clustered <- function() {\n  supervisor <- rep(1:20, each = 10)\n  trained    <- rep(rep(c(0, 1), 10), each = 10)   # no real effect\n  style      <- rnorm(20, sd = 5)[supervisor]      # shared by a supervisor's students\n  wellbeing  <- 60 + style + rnorm(200, sd = 10)\n  # ... test \"trained\" with lm() and with lmer()\n}\n```\n\n20 supervisors, 10 students each, half the supervisors trained. Repeated 500 times.\n\n---\n\n## Ignoring the grouping creates false alarms\n\n| Analysis | Share of studies \"significant\" |\n|---|---|\n| ordinary regression | 27% |\n| mixed-effects model | 7% |\n| a correct test should give | 5% |\n\nThe course went to 20 supervisors, not 200 independent students.\n\nThe mixed model is slightly above 5% because the quick p-value ignores that there are only 20 supervisors.\n\n---\n\n## A study of sleep deprivation\n\n```r\nhead(sleepstudy)\n```\n\nReaction times of 18 people over 10 days of sleep restriction, one measurement per person per day.\n\n180 rows, but only 18 people.\n\n---\n\n## Everyone gets slower, but differently\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-mixed-models_files/figure-html/unnamed-chunk-2-1.svg){width=864}\n:::\n:::\n\n\nPeople start at different levels (**intercepts**) and slow at different rates (**slopes**).\n\n---\n\n## Random intercepts\n\n```r\nsleep_ri <- lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)\nsummary(sleep_ri)\n```\n\n`(1 | Subject)`: one average line, but a separate starting level for each person.\n\n---\n\n## Fixed and random effects\n\n| Part | Describes | Here |\n|---|---|---|\n| fixed intercept | average reaction on day 0 | 251 ms |\n| fixed slope | average change per day | 10.5 ms |\n| SD of intercepts | how much people's starting levels differ | 37 ms |\n| residual SD | day-to-day variation within a person | 31 ms |\n\n---\n\n## The intraclass correlation\n\n$$\n\\text{ICC} = \\frac{\\text{variance between groups}}{\\text{variance between groups} + \\text{variance within groups}}\n$$\n\n```r\nvc <- as.data.frame(VarCorr(sleep_ri))\nvc$vcov[1] / sum(vc$vcov)\n```\n\nAbout 59% of the variation is stable differences between people.\n\nICC 0: the grouping does not matter. The higher it is, the more wrong an ordinary regression becomes.\n\n---\n\n## Random slopes\n\n```r\nsleep_rs <- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy)\n```\n\n`(Days | Subject)`: a separate intercept **and** slope for each person.\n\n| | Random intercept | Random slope |\n|---|---|---|\n| average slope | 10.5 ms | 10.5 ms |\n| its standard error | 0.80 | 1.55 |\n\nSlopes vary with SD ≈ 5.9 ms per day. Ignoring it made the average too confident.\n\n---\n\n## Is the random slope worth it?\n\n```r\nanova(sleep_ri, sleep_rs)\n```\n\nA **likelihood ratio test** compares the two models. The p-value is tiny: random slopes improve the model clearly.\n\n**AIC** agrees: it balances fit against complexity, and lower is better.\n\n---\n\n## The wellbeing panel\n\n```r\npanel <- semesters |>\n  left_join(students, join_by(student_id)) |>\n  mutate(time = semester - 1)\n```\n\nUp to four records per student, 2326 in all. `time` is 0 in semester 1.\n\n---\n\n## Students differ far more than they change\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-mixed-models_files/figure-html/unnamed-chunk-3-1.svg){width=864}\n:::\n:::\n\n\nThirty random students: each stays roughly at their own level.\n\n---\n\n## The ICC for wellbeing\n\n```r\nwb_null <- lmer(wellbeing ~ 1 + (1 | student_id), data = panel)\nvc_null <- as.data.frame(VarCorr(wb_null))\nvc_null$vcov[1] / sum(vc_null$vcov)\n```\n\nAbout 78% of all the variation in wellbeing lies between students.\n\n---\n\n## The design effect\n\n$$\n\\text{design effect} = 1 + (m - 1) \\times \\text{ICC}\n$$\n\n| | Value |\n|---|---|\n| records | 2326 |\n| design effect | 3.25 |\n| independent equivalent | about 716 |\n\n2326 records carry about as much information as 716 independent observations.\n\n---\n\n## Does wellbeing decline? The wrong way\n\n```r\nlm(wellbeing ~ time, data = panel)\n```\n\nSlope -0.38, standard error 0.22: not significant.\n\n---\n\n## The right way: a growth model\n\n```r\nwb_growth <- lmer(wellbeing ~ time + (time | student_id), data = panel)\n```\n\n| | Ordinary regression | Mixed model |\n|---|---|---|\n| slope per semester | -0.38 | -0.43 |\n| standard error | 0.22 | 0.11 |\n\nThe ordinary regression puts the large differences **between** students into its error, drowning the small change **within** each student.\n\n---\n\n## The error can go either way\n\n| Situation | Ignoring the structure |\n|---|---|\n| training course simulation | made a non-existent effect significant |\n| sleep study slopes | made the average look too certain |\n| wellbeing over time | made a real decline look uncertain |\n\nThe direction depends on the data. The error is always there.\n\n---\n\n## lme4 prints no p-values\n\n| Solution | How |\n|---|---|\n| confidence intervals | `confint(wb_growth, parm = \"beta_\", method = \"Wald\")` |\n| likelihood ratio test | compare models with `anova()` |\n| lmerTest | adds Satterthwaite p-values to `summary()` |\n\nThe `time` interval runs from -0.65 to -0.22: entirely below zero. Wellbeing declines, as RQ8 predicted.\n\n---\n\n## lmerTest in practice\n\n```r\nlibrary(lmerTest)\nwb_growth_p <- lmer(wellbeing ~ time + (time | student_id), data = panel)\nsummary(wb_growth_p)$coefficients\n```\n\nNew columns: degrees of freedom and `Pr(>|t|)`.\n\nModels fitted after loading lmerTest include a p-value for each fixed effect.\n\n---\n\n## Did the workshop effect last?\n\n```r\nwb_workshop <- lmer(wellbeing ~ factor(semester) * workshop +\n                      (time | student_id), data = panel)\n```\n\n`factor(semester)` gives each semester its own average; the interaction lets the gap differ by semester.\n\nEvery record is used, including the first year of students who later left.\n\n---\n\n## The effect fades\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-mixed-models_files/figure-html/unnamed-chunk-4-1.svg){width=768}\n:::\n:::\n\n\n| Semester | 1 | 2 | 3 | 4 |\n|---|---|---|---|---|\n| gap (points) | 0.4 | 5.3 | 4.1 | 2.6 |\n\n---\n\n## Predictions for the average student\n\n```r\npredicted <- expand.grid(semester = 1:4,\n                         workshop = c(\"Invited\", \"Not invited\")) |>\n  mutate(time = semester - 1)\npredicted$wellbeing <- predict(wb_workshop, newdata = predicted,\n                               re.form = NA)\n```\n\n`re.form = NA` ignores the random effects.\n\nEvery gap after semester 1 differs from the baseline gap (largest *p* = 0.001). A yearly follow-up session might keep the benefit going.\n\n---\n\n## A singular fit\n\n```r\ngpa_growth <- lmer(gpa ~ time + (time | student_id), data = panel)\n#> boundary (singular) fit: see help('isSingular')\n```\n\nThe model is more complex than the data supports: GPA slopes hardly vary.\n\nSimplify to a random intercept only.\n\n---\n\n## Grades stay stable\n\n```r\ngpa_growth <- lmer(gpa ~ time + (1 | student_id), data = panel)\n```\n\nThe slope of time is -0.000: almost exactly zero.\n\nWellbeing falls while grades hold. A non-change is a finding too.\n\n---\n\n## Students within supervisors\n\n```r\nwb_levels <- lmer(wellbeing ~ time + (1 | supervisor_id) +\n                    (1 | student_id), data = panel)\n```\n\n| Level | Share of variation |\n|---|---|\n| between supervisors | 13% |\n| between students, same supervisor | 65% |\n| within students, over semesters | 22% |\n\nUnique student IDs let R see the nesting. Who supervises a student makes a measurable difference.\n\n---\n\n## Other outcomes: `glmer()`\n\n| Outcome | Family | Coefficients become |\n|---|---|---|\n| yes or no | `binomial` | odds ratios |\n| counts | `poisson` | rate ratios |\n\nSupervisor meetings per semester are a count.\n\n---\n\n## A count model for meetings\n\n```r\nmeetings_model <- glmer(\n  supervisor_meetings ~ support + programme +\n    (1 | supervisor_id) + (1 | student_id),\n  data = panel |> left_join(support_scores, join_by(student_id)),\n  family = poisson)\nexp(fixef(meetings_model))\n```\n\nEach extra point of support: about 48% more meetings. PhD students: about 19% more.\n\nThe direction is uncertain: more meetings may also make students feel supported.\n\n---\n\n## Mixed models and missing data\n\nStudents who left after year 1 were not a random group (Chapter 6).\n\nMixed models use every record each student gave, instead of dropping them.\n\nThe results hold as long as leaving depends on things the model can see: **missing at random**.\n\n---\n\n## Reporting a mixed model\n\n- the fixed effects, with confidence intervals;\n- the random effects, as SDs or variance shares;\n- the number of observations and of groups;\n- which random effects were included.\n\n---\n\n## Writing it up\n\n> A linear mixed-effects model with random intercepts and slopes for students (2326 observations of 600 students) showed that wellbeing declined by 0.43 points per semester (95% CI [0.22, 0.65]). Students differed considerably in their overall wellbeing (*SD* of intercepts = 10.7); 78% of the variation was between students.\n\n---\n\n## In your field: agriculture\n\n```r\nchick_model <- lmer(weight ~ Time * Diet + (Time | Chick),\n                    data = ChickWeight)\n```\n\n50 chicks weighed from birth to 21 days on four diets: repeated measurements in groups.\n\nDiet 1: about 6.3 g a day. Diet 3 adds 5.1 g a day, 82% faster.\n\n---\n\n## Practical lab: the Chapter 10 playground\n\nWork through the playground exercises in your browser, with hints and solutions.\n\nlme4 runs in the browser; every exercise also runs in RStudio.\n\n---\n\n## Practical exercises 1–3: growth models\n\n1. A random intercept model for sleep over time: ICC and change.\n2. Add a random slope and compare with `anova()`.\n3. Does part-time students' wellbeing change at a different rate?\n\n---\n\n## Practical exercises 4–6: levels and simulation\n\n4. How much of the variation in study hours lies between supervisors?\n5. With supervisors who differ more, what happens to the false alarm rate?\n6. Explain to a fellow student why a regression of all semester records is wrong.\n\n---\n\n## Try this yourself\n\nLook at your own data for structure.\n\n- is anyone measured more than once?\n- do participants share a group: class, clinic, supervisor, site?\n- estimate the ICC with a null model;\n- calculate the design effect;\n- decide which random effects your model needs.\n\n---\n\n## Troubleshooting guide (Part 1)\n\n| Symptom | Likely cause |\n|---|---|\n| effects significant that should not be | grouping ignored; standard errors too small |\n| a real change not significant | between-person differences left in the error |\n| no p-values in `summary()` | lme4 by design; use lmerTest or intervals |\n| \"boundary (singular) fit\" | too many random effects for the data |\n\n---\n\n## Troubleshooting guide (Part 2)\n\n| Symptom | Likely cause |\n|---|---|\n| students not seen as nested | IDs repeated across supervisors |\n| predictions differ per student | random effects included; use `re.form = NA` |\n| Poisson coefficients hard to read | log scale; use `exp()` for rate ratios |\n| later semesters look better | attrition; mixed models use all records |\n\n---\n\n## Completion checklist\n\n- [ ] the grouping structure is identified;\n- [ ] the ICC and design effect are reported;\n- [ ] random intercepts are included for each grouping;\n- [ ] random slopes are tested with `anova()`;\n- [ ] singular fits are simplified;\n- [ ] fixed effects come with confidence intervals;\n- [ ] numbers of observations and groups are reported.\n\n---\n\n## Misconceptions to leave behind (Part 1)\n\n| Misconception | Better mental model |\n|---|---|\n| more rows means more evidence | grouped records repeat each other |\n| ignoring grouping costs a little precision | it can multiply false alarms or hide effects |\n\n---\n\n## Misconceptions to leave behind (Part 2)\n\n| Misconception | Better mental model |\n|---|---|\n| averaging each person's records solves it | it discards change and weights people unequally |\n| a singular fit means the model is wrong | simplify the random effects |\n\n---\n\n## The chapter in one sentence\n\n> **When observations share a person or a group, model that structure: mixed models separate differences between groups from change within them and get the uncertainty right.**\n\n---\n\n## Next: Chapter 11\n\nThe next chapter turns from explanation to prediction:\n\n- machine learning and generalisation;\n- overfitting;\n- a fair test with training and test data;\n- cross-validation and tuning;\n- the final test, and predictions about people.\n\n---\n\n## Questions\n\nWhat is the grouping structure in your own data?\n\nHow many truly independent units does your study have?\n",
    "supporting": [
      "10-mixed-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}