{
  "hash": "6634e59677140094947507afc44827ba",
  "result": {
    "engine": "knitr",
    "markdown": "# Comparing Two Groups {#sec-comparing-groups}\n\n::: {.callout-note appearance=\"simple\"}\n## Sample chapter\n\nThis short sample shows the structure every chapter will follow. In the full book, this material belongs to Chapter 6.\n:::\n\n\n\n## Elaf's question\n\nHalf of the 600 students in Elaf's study were invited, at random, to a six-week wellbeing workshop after their first semester. At the end of semester 2, Elaf wants to know:\n\n> **Did the workshop improve students' wellbeing?**\n\nThe invited students' average wellbeing is higher than the others'. But averages always differ a little between any two groups, even when nothing real is going on. The question is whether the difference is bigger than chance alone would produce. A **t-test** answers exactly that question.\n\n## The idea on a handful of numbers\n\nImagine only five students in each group, with these wellbeing scores (out of 100):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninvited     <- c(68, 72, 65, 75, 70)\nnot_invited <- c(62, 66, 60, 69, 64)\n\nmean(invited)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(not_invited)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64.2\n```\n\n\n:::\n:::\n\n\nThe invited group is 5.8 points higher on average. Is that more than chance? `t.test()` compares the two groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmall_test <- t.test(invited, not_invited)\nsmall_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  invited and not_invited\nt = 2.5099, df = 7.9411, p-value = 0.03658\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n  0.4642934 11.1357066\nsample estimates:\nmean of x mean of y \n     70.0      64.2 \n```\n\n\n:::\n:::\n\n\nThe important number is the **p-value**. It tells you how often a difference at least this large would appear by chance alone, if the workshop had no effect at all. Here it is 0.037: a difference this large would happen by chance about 4 times in 100. By convention, researchers call a result **statistically significant** when the p-value is below 0.05.\n\n## Elaf's data\n\nNow the same test on the real study. First, combine each student's workshop group (in `students`) with their semester 2 wellbeing score (in `semesters`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemester2 <- merge(students, semesters[semesters$semester == 2, ],\n                   by = \"student_id\")\nnrow(semester2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 600\n```\n\n\n:::\n:::\n\n\nAlways look at the data before testing it. @fig-workshop shows wellbeing in each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(semester2, aes(x = workshop, y = wellbeing, fill = workshop)) +\n  geom_boxplot(show.legend = FALSE, width = 0.5) +\n  labs(x = NULL, y = \"Wellbeing (0 to 100)\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Wellbeing at the end of semester 2, by workshop group. Each box shows the middle half of the students; the line inside is the median.](comparing-groups_files/figure-html/fig-workshop-1.png){#fig-workshop fig-alt='Box plot of wellbeing scores for invited and not-invited students. The invited group\\'s box sits a few points higher.' width=576}\n:::\n:::\n\n\nThe invited group sits a little higher, but the two groups overlap a lot. Now the test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- t.test(wellbeing ~ workshop, data = semester2)\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  wellbeing by workshop\nt = 5.469, df = 597.52, p-value = 6.66e-08\nalternative hypothesis: true difference in means between group Invited and group Not invited is not equal to 0\n95 percent confidence interval:\n 3.364699 7.135301\nsample estimates:\n    mean in group Invited mean in group Not invited \n                    65.47                     60.22 \n```\n\n\n:::\n:::\n\n\n\n\nInvited students scored 5.2 points higher on average (65.5 against 60.2), and the p-value is below 0.001. A difference this large would almost never appear by chance, so Elaf can conclude that the workshop improved wellbeing. Because students were invited **at random**, she can say the workshop *caused* the improvement, not just that it went with it.\n\n::: {.callout-tip}\n## Writing it up in a thesis\n\n\"Students invited to the wellbeing workshop reported higher wellbeing at the end of semester 2 (M = 65.5) than those not invited (M = 60.2), a difference of 5.2 points, *t*(598) = 5.47, *p* < .001.\"\n:::\n\nNotice that the numbers in that sentence are not typed in: they come from the code. If the data changed, the text would update itself.\n\n## Which test when?\n\nThe t-test is one of several tests for comparing groups. The diagram shows where it fits. Chapter 6 covers each of these.\n\n```{mermaid}\nflowchart TD\n  A[What are you comparing?] --> B{How many groups?}\n  B -->|Two| C{Same people measured twice?}\n  B -->|Three or more| F[ANOVA]\n  C -->|No, different people| D[Two-sample t-test]\n  C -->|Yes| E[Paired t-test]\n  D -.->|Data very skewed| G[Mann-Whitney U test]\n  E -.->|Data very skewed| H[Wilcoxon signed-rank test]\n```\n\n::: {.callout-note icon=\"false\"}\n## In your field: health research\n\nThe t-test was invented to analyse small medical experiments [@student1908]. R still includes one of the original datasets, `sleep`: the extra hours of sleep that 10 patients gained with each of two sleeping drugs. Because the *same* patients took both drugs, this calls for a **paired** t-test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug1 <- sleep$extra[sleep$group == 1]\ndrug2 <- sleep$extra[sleep$group == 2]\nt.test(drug2, drug1, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  drug2 and drug1\nt = 4.0621, df = 9, p-value = 0.002833\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.7001142 2.4598858\nsample estimates:\nmean difference \n           1.58 \n```\n\n\n:::\n:::\n\n\nPatients slept on average 1.6 hours longer with the second drug.\n:::\n\n## Chapter review\n\n**Summary**\n\n- Two group averages almost always differ a little. A t-test asks whether the difference is larger than chance would produce.\n- The p-value is how often a difference at least this large would appear by chance if there were no real effect. Below 0.05 is usually called statistically significant.\n- Always plot the groups before testing them.\n- Random assignment, as in Elaf's workshop, lets you draw causal conclusions.\n\n**Key terms**: t-test, p-value, statistically significant, paired t-test, random assignment.\n\n**Practise**: the exercises for this chapter will be in the [playground](../playground/index.html).\n",
    "supporting": [
      "comparing-groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}